### ISSUE TITLE
Save State Crashes My Game

### ISSUE THREAD

**Issue by Litbolt123** [Lime3DS/Lime-3DS-Emulator#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2109

### Description of Issue

To have the save state function work. I know its built into Lime but it hasn't worked for me, it just crashes the game. Could you get this working properly? Lemonade was going to get rid of it but they went down. Please don't get rid of it :) I think its a very nice feature.

It shows as it saved the state to a slot which is good, although, when i click the load that state, it instantly crashes Lime. I was playing Pokémon Rumble Blast but I don't think that is affecting it.

Also, where can I find the log/crash file I need to share with you guys? Just wanted to get it to you for the best problem solving.

### Expected Behavior

The saved state in its appropriate slot would load what was saved.

### Reproduction Steps

Open a game. Click save state. Play for any amount of time afterword. Try and Load that state. Crashes.

### Log File

[citra_log.txt.old.txt](https://github.com/Lime3DS/Lime3DS/files/15024261/citra_log.txt.old.txt)

### System Configuration

CPU: Ryzen 7 6800H
GPU/Driver: RTX 3070ti (Mobile)
RAM: 32gb ddr5
OS: Windows 11

**Comment by Litbolt123** [comment]
[citra_log.txt.old.txt](https://github.com/Lime3DS/Lime3DS/files/15024261/citra_log.txt.old.txt)

**Comment by OpenSauce04** [comment]
Have you only experienced crashes with a single specific saved state?
Have you tried creating a new save state and then loading from that?

**Comment by Litbolt123** [comment]
I have not. I will test that out right now. 👍

**Comment by Litbolt123** [comment]
So, its funky. I just save 2 more states and one of them worked, but then I went ahead in a level and tried to load that same state again and it was jumped forward in the game, not the original state I saved. And then I saved another state farther in the level but when I tried to load that, it crashed like it had with the save state I've been having problems with in the first place.

**Comment by OpenSauce04** [comment]
That's strange, I've never experienced any issues like that

**Comment by Litbolt123** [comment]
Does it save the crash log somewhere? I could send you that although I don't know where it is.

**Comment by rtiangha** [comment]
> Does it save the crash log somewhere? I could send you that although I don't know where it is.

File->Open Lime3DS Folder->Log

**Comment by Litbolt123** [comment]
[citra_log.txt.old.txt](https://github.com/Lime3DS/Lime3DS/files/15028371/citra_log.txt.old.txt)

**Comment by Litbolt123** [comment]
Hey, is there anything I need to do to help solve this?

**Comment by rtiangha** [comment]
Long shot, but does one of these builds help? I'm working off of PabloMK7's fork, but I've got more updated dependencies than his fork.

https://github.com/rtiangha/bravely-offline-citra/releases

From what I understand, save states mostly rely on Boost serialization libraries and zstd (for save state compression). I've got the latest Boost in my builds (1.85.0), so I wonder if that helps. That said, I noticed that there are also local Boost libraries that haven't been updated in a while, so when I have time, I'm going to see if those can be updated without breaking things (I've already noticed that things don't work with dropping in 1.85.0 versions) and see if that helps. Who knows. I'm just playing around.

**Comment by Litbolt123** [comment]
Ok, what would I need to get from your fork, if that's what you want me to try. Also, I could always wait I guess for Lime to add or fix it too.

**Comment by OpenSauce04** [comment]
> Also, I could always wait I guess for Lime to add or fix it too.

I can only assume that the point of the question was to see if those changes should be merged into Lime3DS, hence fixing the issue

**Comment by Litbolt123** [comment]
Yes.

**Comment by Litbolt123** [comment]
If that is what it took to fix it and if that was a viable solution.

**Comment by rtiangha** [comment]
> Ok, what would I need to get from your fork, if that's what you want me to try. Also, I could always wait I guess for Lime to add or fix it too.

Try the latest release and see if it fixes things (or makes things worse, lol).

**Comment by Litbolt123** [comment]
The latest release of Lime right?

**Comment by Litbolt123** [comment]
How to I update without losing all my data? I have downloaded the newest release but don't know how to update my current release.

**Comment by rtiangha** [comment]
Of this:
https://github.com/rtiangha/bravely-offline-citra/releases

And Lime too, while you're at it (2110).

**Comment by rtiangha** [comment]
> How to I update without losing all my data? I have downloaded the newest release but don't know how to update my current release.

You can have different instances on your computer as long as they're in different folders; they all pull from the same settings at the moment as Lime3DS still shares the stock Citra settings folder (Edit: Well, it does if you originally used the Citra installer; on Windows, that saved settings to the Roaming directory and Lime3DS pulls from that if it exists. Things may be saved to the Lime3DS local directory if you started with just Lime3DS, but it doesn't matter for testing; we just want to see if Save States work in general). So for now, just download a release, unzip it, and run the executable to test things.

**Comment by Litbolt123** [comment]
So, I was playing around in Pokemon Rumble Blast again and I again saved the state at the start of the level and then progressed in the level. I was able to load the state I had saved at the start of the level, so yay! But I had also saved a state farther in the level. When I tried to load that it crashed the game as usual. So thats not good.

**Comment by Litbolt123** [comment]
heres my log after the crash

**Comment by Litbolt123** [comment]
[citra_log.txt](https://github.com/Lime3DS/Lime3DS/files/15098732/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/Lime3DS/Lime3DS/files/15098733/citra_log.txt.old.txt)

**Comment by Litbolt123** [comment]
hmmmm, I just opened the game again and was off the bat able to load the first and second state, but when I tried to load the third state, it crashed as it had before :/

**Comment by Litbolt123** [comment]
Btw, I am playing on the Citra download you gave me in these comments (I also downloaded the newest release of Lime)

**Comment by rtiangha** [comment]
For the moment, just test creating new save states from this point on and opening them and see if that's working reliably; I wouldn't be surprised if older save states saved under older versions of Boost and zstd didn't work consistently. Also, don't be switching save states between Citra and Lime3DS; my builds use a different Boost version (I'm on 1.85.0 and I believe Lime3DS still uses what the last Citra Nightly did which is 1.82.0) and that could cause issues.

**Comment by Litbolt123** [comment]
Ok, I didnt switch saves between Citra and Lime. I only used Citra. I deleted my old save states and only created ones and tested them in the Citra you sent me.

**Comment by Litbolt123** [comment]
> hmmmm, I just opened the game again and was off the bat able to load the first and second state, but when I tried to load the third state, it crashed as it had before :/

This is the new saves on the Citra you sent me

**Comment by Litbolt123** [comment]
Anything else I need to do to help?

**Comment by rtiangha** [comment]
So wait, are things better now? If so, I'll make a Lime3DS version for you to test just to make sure. If not, then I'm out of ideas.

**Comment by Litbolt123** [comment]
Things are not better :/

**Comment by Litbolt123** [comment]
I save a state in a Pokémon Rumble Blast. Try and load the state. It crashes Lime. That's all I can find out.

**Comment by Litbolt123** [comment]
Okay, so i know you said you are out of ideas, but, have you tried saves states yourself? Does it crash any of your games?

**Comment by Litbolt123** [comment]
Alright, so what's the verdict? Are we removing save states from Lime or have been removed already? If not, we could still work on it.

**Comment by OpenSauce04** [comment]
@rtiangha Unless I'm interpreting your message wrong, you seemingly forgot to send the build you mentioned earlier in the thread? Do you still intend to do so?

> Are we removing save states from Lime or have been removed already?

We will not be removing save states

**Comment by Litbolt123** [comment]
Hey, it looks like the problem I was having isn't occurring anymore in 2117.1 

Thanks!
