### ISSUE TITLE
App crashes after pausing emulation

### ISSUE THREAD

**Issue by HFPasfho** [Lime3DS/Lime-3DS-Emulator#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2110

### Description of Issue

Pausing/resuming emulation crashes Lime3DS. Sometimes it takes two or three pauses to crash the app but sometimes it crashes immediately.

### Expected Behavior

Pausing and resuming emulation should not crash the app.

### Reproduction Steps

1. Start a game
2. Pause emulation
3. Resume emulation
4. Go to step 2 if the app didn't crash already

### Log File

This crash doesn't produce any new entries in logfile

### System Configuration

CPU: Exynos 9810
GPU/Driver:
RAM: 4 GB
OS: Android 10

**Comment by rtiangha** [comment]
Did it ever work under older Lime3DS releases? How about the last Citra nightly? Or even PabloMK7's fork?

**Comment by HFPasfho** [comment]
I don't know. 2110 was the first Lime3DS version I tried and I newer used Pablo's fork. I've never noticed this problem on Citra stable though.

**Comment by ghost** [comment]
@OpenSauce04 

This issue has gotten a lot worse

Just pasuing the emulator once on both OpenGL and Vulkan will crash the emulator instantly on my device 

On some games like Mario 3D Land

On other games like Maeio and Luigi, it crashes on the 2nd pause

**Comment by OpenSauce04** [comment]
I am now able to replicate the issue where I couldn't before, however on my end it happens after pausing, unpausing, then repausing.

Now that I can replicate the issue, I will investigate when I am able. I am unsure what could have changed between when this issue was made and now to make me able to replicate it.
