### ISSUE TITLE
The log file name contains the name Citra

### ISSUE THREAD

**Issue by HFPasfho** [Lime3DS/Lime-3DS-Emulator#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2110

### Description of Issue

Log file name produced by share log option contains name Citra.

### Expected Behavior

Probably it's wise to avoid using this brand.

### Reproduction Steps

1. Go to options
2. Tap share log
3. Save log file

### Log File

not applicable

### System Configuration

not applicable

**Comment by OpenSauce04** [comment]
This has now been fixed
