### ISSUE TITLE
Default landscape layout is not using whole screen

### ISSUE THREAD

**Issue by HFPasfho** [Lime3DS/Lime-3DS-Emulator#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2110

### Description of Issue

Default landscape layout (two screens one big and one small side-by-side) doesn't use whole screen area unlike single screen mode. Default layout leaves black bars on the top and on the bottom of the screen.

### Expected Behavior

Default landscape layout should use whole screen area.

### Reproduction Steps

1. Start a game in landscape mode
2. Change layout to Single Screen
3. Change layout back to Default
4. Compare screen space usage

### Log File

not applicable

### System Configuration

not applicable

**Comment by OpenSauce04** [comment]
On my phone, the whole screen is used
I am closing this issue as there is nothing else that can be done with the lacking information given in this issue

**Comment by HFPasfho** [comment]
@OpenSauce04 You may have requested these details before closing this ticket. Although I don't know what else I can provide except attach this screenshot.
![Lime3DS](https://github.com/Lime3DS/Lime3DS/assets/128609045/dbed01e2-885a-401d-b1d4-38ff035778d8)

**Comment by HFPasfho** [comment]
@OpenSauce04 I think this issue should be open. It contains a description of the bug, steps to be taken to reproduce it and the screenshot showing the bug. If you lack any information just ask. I'm willing to help.
