### ISSUE TITLE
One controller key can be bind to multiple virtual keys.

### ISSUE THREAD

**Issue by HFPasfho** [Lime3DS/Lime-3DS-Emulator#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2110

### Description of Issue

It could be intentional but one physical key on controller can be bind with multiple emulator keys.

### Expected Behavior

If it's not intentional then it shouldn't be possible.

### Reproduction Steps

1. Go to settings
2. Go to gamepad options
3. Start binding keys
4. You can bind one key to multiple buttons but not for all of them

### Log File

not applicable

### System Configuration

not applicable

**Comment by OpenSauce04** [comment]
I would consider this a non-issue, as the existing keys can easily be cleared if this was done on accident

**Comment by HFPasfho** [comment]
@OpenSauce04 It looks like this does not apply to all keys and some of them are cleared automatically when a duplicate is detected, which is why I wrote this report because it looks like a bug. Unfortunately, I can't check it in detail now and specify which keys it applies to, because I won't have access to the gamepad for some time.
