### ISSUE TITLE
Using left and right or up and down arrow keys on the "Emulation speed" slider moves it by five increments rather than one

### ISSUE THREAD

**Issue by NintendoManiac64** [Lime3DS/Lime-3DS-Emulator#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2110 - 2116

### Description of Issue

When using the arrow keys to move the slider for "Emulation speed", a single key press results in the slider moving by five increments rather than just a single increment.

### Expected Behavior

Using the arrow keys should make the slider only move by a single increment, hence the reason to use the arrow keys in the first place—to try to more easily achieve greater precision.

This would match other software that commonly behave this way (Avidemux is a random example that comes to mind where left/right arrow keys moves the slider by a single frame).

　
It might also be worth mentioning that pressing PageUp or PageDown moves the slider by 75% or 15 increments which seems a bit much does it not?

I also couldn't help but notice that the up/down directionality for not only the up & down arrow keys but also the scroll wheel as well as PageUp & PageDown keys seems reverse relative to the common shortcuts of Ctrl+PageUp/PageDown to switch tabs in browsers or file explorers, or Xfce's function to use the scroll wheel to change between open windows on the panel, but perhaps this is a Qt thing since even Avidemux's stock configuration has the same issue (though it includes a setting to invert this).

### Reproduction Steps

1. Launch the Lime3DS flatpak

2. Go to `Emulation` ▶ `Configure...`

3. On the "General" category, click on the slider for `Emulation speed`

4. Press the left or right arrow keys or, alternatively, the up or down arrow keys on your keyboard

5. Observe how every press of the left or right arrow keys or the up or down arrow keys results in the `Emulation speed` adding or subtracting 25% which equates to 5 increments

### Log File

I'm uncertain it really applies to this sort of thing—the log doesn't really seem to record simply interfacing with the UI and only records actual setting changes...

### System Configuration

**CPU:** Pentium G3258 @ 4.5GHz (essentially an overclockable Haswell i3 with a gimped iGPU and no SMT nor AVX)
**GPU/Driver:** "Intel HD Graphics" (the gimped version found on lower Haswell models); mesa v23.3.6 kisak1~f; Vulkan
**RAM:** 4x8GB Corsair Vengence @ DDR3-1600
**OS:** Linux Mint Xfce 20.3

**Comment by NintendoManiac64** [comment]
This issue still exists in 2118.1 (and by definition 2118.2).

**Comment by OpenSauce04** [comment]
This isn't really a bug. If you would like this behaviour to be changed you could make an enhancement issue, but in the mean time this can be easily resolved by editing the config file if you need a speed that precise.
