### ISSUE TITLE
Manually setting "frame_limit" in qt-config.ini to a non-integer value with multiple decimal places results in unthrottled emulation speed; program also subsequently crashes when stopping emulation

### ISSUE THREAD

**Issue by NintendoManiac64** [Lime3DS/Lime-3DS-Emulator#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2110 - 2116

### Description of Issue

When manually setting `frame_limit` inside of qt-config.ini to a non-integer value with multiple decimal places (e.g. a value of `98.7654321` will instead result in Lime3DS running games at unthrottled emulation speed, and the program itself will crash when you go to subsequently stop emulation.

### Expected Behavior

Much like Dolphin, DuckStation, and mGBA, Lime3DS should be able to handle running with non-integer values with multiple decimal places without issue, that being actually running at the specified fractional value specified as well as not crashing the program when you stop emulation.

### Reproduction Steps

1. Install the flatpak version of Lime3DSL

2. Launch Lime3DS

3. Go to  `Emulation` ▶ `Configure...`

4. Set emulation speed to 95 and click OK

5. Close Lime3DS

6. Open Lime3DS's corresponding qt-config.ini file

7. Locate the line `frame_limit=95` and replace the `95` with something like `98.7654321`

8. Save qt-config.ini

9. Launch a game in Lime3DS

10. Observe how Lime3DS runs at unthrottled speed (you can also confirm this via `Emulation` ▶ `Configure...`)

11. Go to `Emulation` ▶ `Stop` and wait a few seconds

12. Observe has an error will appear saying that Lime3DS has crashed

### Log File

[log.txt](https://github.com/Lime3DS/Lime3DS/files/15049927/log.txt)

All I did was launch Donkey Kong Country Returns 3D and then, after sitting at the title screen for a few seconds, I stopped emulation.

### System Configuration

**CPU:** Pentium G3258 @ 4.5GHz (essentially an overclockable Haswell i3 with a gimped iGPU and no SMT nor AVX)
**GPU/Driver:** "Intel HD Graphics" (the gimped version found on lower Haswell models); mesa v23.3.6 kisak1~f; Vulkan
**RAM:** 4x8GB Corsair Vengence @ DDR3-1600
**OS:** Linux Mint Xfce 20.3

**Comment by OpenSauce04** [comment]
I can't say it's surprising that changing a value that only accepts integers to a non-integer value by editing config files causes issues.
I would hesitate the call this a bug

**Comment by NintendoManiac64** [comment]
This issue still occurs in the current 2116 release.

**Comment by OpenSauce04** [comment]
Citing my initial response, I will be closing this as won't fix. Manually editing config files to use values which are not accepted and then observing undocumented behaviour is par for the course. I don't know why you would want to use a decimal framerate anyway.

**Comment by NintendoManiac64** [comment]
> I don't know why you would want to use a decimal framerate anyway.

There is something I like to do with emulators that cannot be replicated with real hardware, that being playing games at a slower-than-native speed.

While there was no F-Zero nor Fast Racing League game for the 3DS, these are still the easiest examples whereby, on Dolphin when playing local multiplayer with less-skilled people, I will run the games at either 30fps (half speed) or 40fps (2/3 speed) in conjunction with issue #121 so that the audio doesn't sound like absolute crap.

To clarify, the choices of 30fps and 40fps are due to being exact multiples of 60Hz and 120Hz, both which are commonly supported TV refresh rates.

But the problem is that 40fps is 66.666666666...% so, to have a perfectly judder-free experience, you can't do a flat 66% or 67% but rather a value with decimal places as is supported in all 3 of the previously-mentioned emulators.

**EDIT**: I also just remembered that, if you take advantage of the PAL refresh rates of 50Hz and 100Hz (commonly supported even on North American TVs), then you can have a few more more options with your game speed while still being judder-free—that is, 33.3333333...fps (1/3 of 100Hz) which is 55.5555555...%, or even a flat 50fps which is 83.33333333...%

Of course, I also just realized that all of the aforementioned values are under the assumption that the 3DS's native refresh is 60.00Hz rather than 60000/1001 (commonly referred to as 59.94Hz); if it's actually 59.94Hz then some of the decimal values could change depending on whether your TV's refresh is similarly set to 59.94Hz/119.88Hz or 60.00Hz/120.00Hz (and of course, the PAL rates of 50Hz and 100Hz don't have any drop-frame equivalents and are always 50.00Hz and 100.00Hz).

**Comment by OpenSauce04** [comment]
Ohhhh the config is stored as a percentage. 🤦🏻
Sorry, for some reason I thought that it was stored as the raw framerate, my bad.
I'll reopen this, I now see the use case.
