### ISSUE TITLE
Vulkan crash on android

### ISSUE THREAD

**Issue by GUWPPY** [Lime3DS/Lime-3DS-Emulator#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2110

### Description of Issue

Everytime i load a specific game like planet robobot or metroid samus returns it goes to the preload screen then crashes

### Expected Behavior

It would run any game without crashing

### Reproduction Steps

1.go to settings
2.go to graphics settings
3.change renderer to vulkan
4.start game

### Log File

[citra_log.txt.old.txt](https://github.com/Lime3DS/Lime3DS/files/15050373/citra_log.txt.old.txt)

### System Configuration

CPU:hisilicon kirin 990
GPU/Driver:mali-g76
RAM:8gb ram
OS:android 10

**Comment by Ivan951236** [comment]
mentioning your phone model would be really helpful

**Comment by GUWPPY** [comment]
> mentioning your phone model would be really helpful

Huawei mate 30 pro 5g lio-n29
