### ISSUE TITLE
Rendering Issue on Android Oppo Find X 3 Pro

### ISSUE THREAD

**Issue by jpen856** [Lime3DS/Lime-3DS-Emulator#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android 2110

### Description of Issue

Pokemon such as Mudkip and Froakie display incorrectly. very light blue colour. Happens on both OpenGL and Vulkan, With or without accurate Shader multiplication.

### Expected Behavior

Should display correctly using OpenGL and Accurate Shader Multiplication. Not the case on my oppo find x 3 pro

### Reproduction Steps

Play Pokemon Omega Ruby, Alpha Sapphire, X or y, and select Mudkip/Froakie at starter selection respectively.

### Log File
[citra_log.txt.old.txt](https://github.com/Lime3DS/Lime3DS/files/15051548/citra_log.txt.old.txt)

### System Configuration

CPU: Qualcomm Snapdragon 888 Octacore
GPU/Driver: Default
RAM: 12.0 GB
OS: Android 14

**Comment by OpenSauce04** [comment]
Please include your version number in the issue description as per the template
Also, upload your log as a file so the issue doesn't get flooded with text

**Comment by jpen856** [comment]
Updated as per request. Apologies, it's my first time doing this. Might be worth mentioning the Log File is still named citra_log.txt
