### ISSUE TITLE
android release on f-droid or izzyondroid

### ISSUE THREAD

**Issue by udbue** [Lime3DS/Lime-3DS-Emulator#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

an android release on f-droid or izzyondroid

### Why would this feature be useful?

easier for users to download and update the app, and an easy way to attract new users

**Comment by OpenSauce04** [comment]
We have investigated this already, and have decided that it isn't possible, or at the very least isn't practically viable
The use of Obtainium has been implemented in the place of F-Droid, check our readme for more information

**Comment by davidhedlund** [comment]
> We have investigated this already, and have decided that it isn't possible, or at the very least isn't practically viable The use of Obtainium has been implemented in the place of F-Droid, check our readme for more information

Hello. What is the reason behind this?
