### ISSUE TITLE
Proper Discord Rich Presence

### ISSUE THREAD

**Issue by jpen856** [Lime3DS/Lime-3DS-Emulator#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Discord rich presence showing which game is played Instead of saying "Playing Lime3DS"

### Why would this feature be useful?

Would make it easier to see what friends are playing.

**Comment by OpenSauce04** [comment]
This is already a feature to my knowledge

**Comment by TheRealWario** [comment]
What if we could make it so it displayed the game icon as well?

**Comment by OpenSauce04** [comment]
Unfortunately that isn't possible to my knowledge as a limitation of the rich presence API

**Comment by OpenSauce04** [comment]
I am going to close this as the original topic has been seemingly resolved
