### ISSUE TITLE
Segfault under Linux when built from source with Clang 18 when launching a game(every games affected), AppImage works.

### ISSUE THREAD

**Issue by ghost** [Lime3DS/Lime-3DS-Emulator#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Latest Git revision.

### Description of Issue

I'm experiencing segfault(segmentation fault(core dumped)) when launching a game, changing renderer to OpenGL instead of Vulkan didn't fix the issue, using X11 or Wayland did not change anything, but the AppImage works.

### Expected Behavior

I expect to be able to launch and play game on my linux system.

### Reproduction Steps

Fetch latest source, build from source with Clang 18, start a game(any game) and see the segfault.

### Log File

My log file is empty, despite trying to generate it...

### System Configuration

CPU : Ryzen 7 7840HS 8C/16T 5.1GHz.
RAM : 64GB DDR5 4800MHz.
GPU : Radeon 780M, 6GB VRAM taken from main system RAM.
OS : Fedora Linux 40 Beta KDE Spin.
Compiler : Clang 18.
GLIBC version : 2.39.

**Comment by rtiangha** [comment]
Maybe try reverting this one and see if it helps: https://github.com/Lime3DS/Lime3DS/commit/106a4a2ef4e677f4fcb4e7ccfa87c2604f74993c

msys2 under Windows uses Clang 18.1.4 and things have always worked fine (so I don't feel like it's a Clang 18 issue) so unless the new Linux container is missing some libraries or something, things should work in theory.

Edit: although I'm not sure what makes the appimage build different from the regular build so I could be talking out of my butt.

**Comment by OpenSauce04** [comment]
Closing as there is not enough information and the user deleted their GitHub account
