### ISSUE TITLE
It doesnt work ironfall invasion

### ISSUE THREAD

**Issue by mcoldani** [Lime3DS/Lime-3DS-Emulator#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Version 2110

### Description of Issue

Hi im on snapdragon 665 and the emulator just crash when im trying this game, I updated the game and trying using drivers but nothing seems to works.

### Expected Behavior

Enter to the game

### Reproduction Steps

Just open the game and it shows the intro but then crashes

### Log File

[citra_log.txt](https://github.com/Lime3DS/Lime3DS/files/15053349/citra_log.txt)

### System Configuration

CPU:snap 665
GPU/Driver: Qualcomm v744.19 vulkan
RAM:4gb
OS:android 11

**Comment by YGOmod** [comment]
Do you have aes_keys.txt in sysdata folder??

**Comment by mcoldani** [comment]
Yes I hav, im using the menu, I tried .3ds and .cia and it's the same result.
