### ISSUE TITLE
Immersive mode for VR

### ISSUE THREAD

**Issue by Tenk1** [Lime3DS/Lime-3DS-Emulator#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Adding an immersive for VR like CitraVR has, meaning expanding the game window to 180 or 360 degrees around us  

### Why would this feature be useful?

To play 3DS games in VR more immersively like on quest but with PC performance

**Comment by InitialXKO** [comment]
There is another fork CitraVR

**Comment by Tenk1** [comment]
I know but quest 3 isn't powerful enough to play with correct performances

**Comment by OpenSauce04** [comment]
> I know but quest 3 isn't powerful enough to play with correct performances

I am unsure why you think that us including our own VR mode would change this

While this is a cool suggestion, it is out of the scope of this project. Please use the aforementioned CitraVR instead
