### ISSUE TITLE
Tomodachi Life Miis not loading properly

### ISSUE THREAD

**Issue by Im-tan** [Lime3DS/Lime-3DS-Emulator#144]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Lime3DS 2210

### Description of Issue

Whenever I try to use miis in tomodachi life, no matter if i create them from scratch or use the one that is preloaded when i select mii maker, the mii always appears as a red cross on a square of the skin tone - this square is see-though from behind.
<img width="209" alt="Screenshot 2024-04-22 at 22 14 54" src="https://github.com/Lime3DS/Lime3DS/assets/93826419/4671bb52-1bc1-4bcf-a1a4-d5e97814dde6">
<img width="209" alt="Screenshot 2024-04-22 at 22 15 27" src="https://github.com/Lime3DS/Lime3DS/assets/93826419/a81b62ba-3dc7-443c-9a1d-40e84819ba30">
<img width="209" alt="Screenshot 2024-04-22 at 22 16 26" src="https://github.com/Lime3DS/Lime3DS/assets/93826419/1847be74-a40a-48ad-acb4-bc33eb9a2bec">
<img width="209" alt="Screenshot 2024-04-22 at 22 16 31" src="https://github.com/Lime3DS/Lime3DS/assets/93826419/4f7ce24f-4d8d-4901-a024-4cb3b3e86e5f">
<img width="584" alt="Screenshot 2024-04-22 at 22 17 06" src="https://github.com/Lime3DS/Lime3DS/assets/93826419/148f778c-9696-4fe9-af0c-d72008eedd7f">
<img width="584" alt="Screenshot 2024-04-22 at 22 17 15" src="https://github.com/Lime3DS/Lime3DS/assets/93826419/3f6adeab-ddd6-4cb4-81cd-ca0ad0b98c0d">

### Expected Behavior

supposed to show normal miis

### Reproduction Steps

i just loaded my file and this happened

### Log File

i dont know how to get log files

### System Configuration

CPU: Apple M3
GPU/Driver: Apple 10-core GPU
RAM: 8GB
OS: macOS Sonoma Version 14.4.1

**Comment by Im-tan** [comment]
I can add log files in a comment when i know how to

**Comment by Coderst1** [comment]
You have to dump specific system files to fix that.
Using threesd to do so is one of the main methods.

**Comment by OctocatBoi** [comment]
i have the same issue. tried using the mii data on this website (github) but whenever i put it on the user folder, it doesnt work

**Comment by Olimon7661** [comment]
uh, i have the same issue, how do i actually dump the files, and which ones?

**Comment by Zora-Z0** [comment]
For anyone else wondering how to fix this you need to use the Azahar Artic Setup Tool. Which you have to install on a modded 3Ds. Here is the link for the tool

https://github.com/azahar-emu/ArticSetupTool

Just follow the steps and make sure both devices are on the same network, e.g. your 3ds and emulation device.

**Comment by BloodReddSky** [comment]
so you just cant use the miis unless you have a 3ds
what a great emulator

**Comment by Mangl3dd** [comment]
I know this was a question asked almost 2 years ago, but! I have the solution for any other person needing an answer! (at least it's worked for me on multiple emulators on Linux Mint.) follow this link https://www.mediafire.com/file/3bv7u3ehwl49ae1/MiiFix.3ds/file and download the file, put it into the same folder that you have the game in, launch it as if it's a game, let it run it's code. exit and then re-open Tomodachi Life on a new save state and your mii's should have faces! I'm sorry if this was confusing, I am entirely new to the computer world haha.

**Comment by RisingPhoinex** [comment]
> I know this was a question asked almost 2 years ago, but! I have the solution for any other person needing an answer! (at least it's worked for me on multiple emulators on Linux Mint.) follow this link https://www.mediafire.com/file/3bv7u3ehwl49ae1/MiiFix.3ds/file and download the file, put it into the same folder that you have the game in, launch it as if it's a game, let it run it's code. exit and then re-open Tomodachi Life on a new save state and your mii's should have faces! I'm sorry if this was confusing, I am entirely new to the computer world haha.

This worked for me perfectly, thanks!
