### ISSUE TITLE
Online

### ISSUE THREAD

**Issue by mcoldani** [Lime3DS/Lime-3DS-Emulator#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

To implement online on lime3ds hope some day it work, i could install pretendo (the servers for 3ds) on the menu and works, but the emulator just dont connect to internet, so that would be uselfull just able to connect and using pretendo.

### Why would this feature be useful?

To get a better experiencie on some titles.

**Comment by themaster567** [comment]
Gonna assume you didn't mean to mark your own ticket as complete the moment you submitted it

**Comment by mcoldani** [comment]
Haha I didnt see that this was already ask for so thats why, hope it will implement some day.
