### ISSUE TITLE
android: Attempting to swap screens or change layout forces Portrait layout

### ISSUE THREAD

**Issue by Arkwelder** [Lime3DS/Lime-3DS-Emulator#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2110 and previous

### Description of Issue

It is important to note from the outset that I am running the app on an on an Orange Pi 5—an SBC similar to something like a Raspberry Pi—connected to a TV and not a phone or tablet. I am happy to report the app runs perfectly on my device except for one small matter: Any attempt to to swap screens or change the screen layout will result in the layout switching and locking to portrait mode. It cannot be switched back except if you close and reopen the app. However, upon reopening the app, the desired layout (the one selected before closing the app) will be displayed correctly. I believe this may be an issue with the app (or the OS more broadly) not knowing whether it is in portrait or landscape orientation (given that the device is outputting to a TV that is presumably always in landscape mode). This is a minor issue, aside from the fact that the swap screens feature is rendered completely useless as a result. Therefore, I am submitting this issue FYI as a courtesy. This issue was also present in Citra Nightly and Lemonade, but not MMJ, where both features worked as expected.

### Expected Behavior

The expected behavior, of course, is that the swap screens and change layout setting will apply instantly, not lock itself into portrait mode, and that the app will not need to be restarted in order to have the desired changes take effect.

### Reproduction Steps

1. Open Lime3DS android app.
2. Select any game from your library.
3. Open the menu and select "Landscape Screen Layout" and select any of the available options, or
4. select "swap screens" from the menu for an identical result.

### Log File

A log file could not be generated at this time.

### System Configuration

CPU: Rockchip rk3588
GPU/Driver: Mali g610
RAM: 4 GB
OS: Android 12
Device: Orange Pi 5

**Comment by Illynir** [comment]
Same problem on 2114.1, tested on Ayaneo Pocket S.

**Comment by intelliaim** [comment]
Same issue for me as well on the Ayaneo Pocket S (Android 13). Only happens in landscape where layout swap button only changes between one layout (top/bottom screen stacked). Interestingly, if I hold the device vertically, the swap layout does work and cycles all layouts properly! It's just landscape that has the issue.

https://github.com/Lime3DS/Lime3DS/assets/16974249/4e8115ef-dbdf-4b36-9155-125bb7c62ca4

My workaround is to rotate to vertical orienation, then the swap layout hotkey works properly :)
It doesn't do all the layouts while in horizontal orientation.

**Comment by intelliaim** [comment]
Uploading PXL_20240621_115506119 (1).mp4…

**Comment by acarrizosa** [comment]
Same problem on the RG405V using version 2115

**Comment by OpenSauce04** [comment]
I am unable to replicate this issue on 2117. Can someone confirm that this issue still happens?

**Comment by Illynir** [comment]
It's fixed since 2116 for me.

**Comment by acarrizosa** [comment]
I was still getting this issue in 2116 in my RG405V

**Comment by Nate0714** [comment]
I am confirming this issue still exists in 2116 I am using a retroid pocket 2s and selecting Landscape Screen Layout does not adjust the screens it is just stuck vertically one on top of the other. I can swap which screen is on top and vice Versa but not the layout and that is with both the in app selector on the left of the screen and the hot key I assign this function to. This does work sort of when I switch to horizontal screen rotating my physical device, but in the normal orientation of the physical device this does not work. This is in contrast to melon ds which I can hotkey change layout and when I press that button there are a variety of layouts not just vertically two screens displayed.
