### ISSUE TITLE
(android) option to move and resize screens/ custom screen sizes and positions

### ISSUE THREAD

**Issue by Coderst1** [Lime3DS/Lime-3DS-Emulator#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Add two more options in the game menu options. One would be called custom screen size and the other would be called custom screen position

### Why would this feature be useful?

it would allow users who want it to be able to further customize their gameplay on android

**Comment by OpenSauce04** [comment]
If my understanding of the request is correct, this has been added since this issue was opened.
