### ISSUE TITLE
Android: Make available to save files in the private space

### ISSUE THREAD

**Issue by BestShijun** [Lime3DS/Lime-3DS-Emulator#152]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What feature are you suggesting?

Suggest to add an option allowing to save all files into the private folder (Android/[PackageName]/files/). 

### Why would this feature be useful?

Due to the storage permission of Android, saving nand, sdmc, and other files in an external folder may slow down the speed of emulator, for which I suggest that it can be an option to choose either saving files into a private folder or an external folder.

**Comment by YGOmod** [comment]
is there any evidence on that it slowers emulator?  🤔

**Comment by BestShijun** [comment]
> is there any evidence on that it slowers emulator?  🤔

This.
Also, it always get a stuck when loading SD card on my phone. So I think it might be this reason.
I also tried Citra-MMJ, which provides both storage mode, and compare both. It is actually faster.
I'm not a developer, and this suggestion is only based on my using experience. I'll say sorry if it is not true.
![Screenshot_2024-04-28-18-29-45-855_io.github.lime3ds.android.jpg](https://github.com/Lime3DS/Lime3DS/assets/119794761/9ed7f163-a7cb-47aa-8313-e5619f3e73f0)

**Comment by OpenSauce04** [comment]
The text in this screenshot does not appear to be related. It mentions that having multiple versions of the system files installed will cause slowdowns, with nothing to do with the location.
If you want this change, come with numbers to back it up

**Comment by BestShijun** [comment]
> The text in this screenshot does not appear to be related. It mentions that having multiple versions of the system files installed will cause slowdowns, with nothing to do with the location.
> If you want this change, come with numbers to back it up

Ok, I understand. Thank you. I'll close this issue.
