### ISSUE TITLE
easier access for log sharing on pc

### ISSUE THREAD

**Issue by Coderst1** [Lime3DS/Lime-3DS-Emulator#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Make it so people can easily share the correct log for their issue with a menu option

### Why would this feature be useful?

This is so that logs can be more easily shared for support and make less of a headache for anyone involved in the process (everyone who asks for people to get logs knows what I'm talking about lmao)

**Comment by rtiangha** [comment]
Just throwing an idea out there, but an easy way to do this would be to clone the `File->Open Citra Folder` function and modify it to make an `Open Logs folder` option and perhaps put it under the Help menu. Easier than coding a QT text log viewer, anyway.
