### ISSUE TITLE
Cut the Rope: Triple Treat - Major graphical glitches

### ISSUE THREAD

**Issue by mcoldani** [Lime3DS/Lime-3DS-Emulator#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime 2110

### Description of Issue

The games presents a visual glitch, its unplayable

### Expected Behavior

![Screenshot_20240428-032437](https://github.com/Lime3DS/Lime3DS/assets/66690821/277a4aec-9b2f-49dd-af69-764a568ebeae)

### Reproduction Steps

Opening and trying to play the game

### Log File

[citra_log.txt.old.txt](https://github.com/Lime3DS/Lime3DS/files/15161172/citra_log.txt.old.txt)

### System Configuration

CPU:snapdragon 665
GPU/Driver:
RAM:4gb
OS:android 11

**Comment by OpenSauce04** [comment]
Have you tried using the OpenGL renderer?

**Comment by mcoldani** [comment]
![Screenshot_20240430-083027](https://github.com/Lime3DS/Lime3DS/assets/66690821/f63ee791-9f3f-4ca5-94b9-70e9601fad26)
 I just tried, its the same result
