### ISSUE TITLE
Mario Kart 7 crash on new version

### ISSUE THREAD

**Issue by HFPasfho** [Lime3DS/Lime-3DS-Emulator#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2111

### Description of Issue

Mario Kart 7 crash on new version (2111). On 2110 it worked fine.

### Expected Behavior

To not crash.

### Reproduction Steps

1. Open game
2. Tap Single Player
3. Experience immediate crash

or

1. Open game (tap OK to show menu)
2. Do absolutely nothing
3. Experience crash after several seconds

### Log File

I'm unable to attach it this time

### System Configuration

CPU: Exynos 9810
RAM: 4 GB
OS: Android 10

**Comment by OpenSauce04** [comment]
We are unable to investigate the issue without a log file. If you can reproduce the crash, please open a new issue with the log attached

**Comment by HFPasfho** [comment]
@OpenSauce04 Does this mean you can't reproduce this bug on your device? English is not my first language, but it sounds like you wouldn't even try to follow the steps I described. And for the error to occur, all you need to do is run the game.
