### ISSUE TITLE
Visual glutches (mario party star rush)

### ISSUE THREAD

**Issue by mcoldani** [Lime3DS/Lime-3DS-Emulator#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime 2110

### Description of Issue

Play on vulkan and it happends

### Expected Behavior

Hope to ger fixed

### Reproduction Steps

Play on vulkan and with cpu drivers 
![Screenshot_20240501-004334](https://github.com/Lime3DS/Lime3DS/assets/66690821/1b01da09-b9b8-43bf-8523-be3ae09a976a)

### Log File

Idk how to do it

### System Configuration

CPU: snapdragon 665
GPU/Driver: adreno 610
RAM:4gb
OS:android 11

**Comment by OpenSauce04** [comment]
Nearly none of the sections in this issue are formatted properly. Please submit a report with the required information

**Comment by mcoldani** [comment]
What's missing?

**Comment by mcoldani** [comment]
The cpu driver versión I think, Im now able to get the log file if its need it

**Comment by OpenSauce04** [comment]
You didn't describe the issue, describe the expected result, describe how to reproduce the issue, or attach a log file
