### ISSUE TITLE
question android version

### ISSUE THREAD

**Issue by B-Nerd** [Lime3DS/Lime-3DS-Emulator#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

not really a Feature Request but what is the exact name of the android app so that people can add this manually esde this esde i mean https://es-de.org/

### Why would this feature be useful?

for help with esde on android

**Comment by OpenSauce04** [comment]
For questions like this, the Discord is a better place to ask
