### ISSUE TITLE
Request for Addition of Qt VNC Server to Enable Direct Touch Input from 3DS

### ISSUE THREAD

**Issue by Vyacguru** [Lime3DS/Lime-3DS-Emulator#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Dear Lime3DS developers,
I hope this message finds you well. I am writing as a dedicated user and enthusiast of Lime3DS, and I would like to express my gratitude for the ongoing efforts you have made to maintain and enhance the emulator. It has provided me with countless hours of entertainment and enjoyment.

I would like to bring to your attention a specific request related to the functionality of Lime3DS: the addition of Qt VNC server support. This would enable direct touch input from the Nintendo 3DS to the Lime3DS emulator through the TinyVNC client for 3DS.

While I understand that implementing this feature may require time and resources, I strongly believe it would be a valuable addition to Lime3DS, improving its functionality and user experience for everyone who uses it.
Your consideration of this request would greatly benefit me and other Lime3DS users. I look forward to hearing about any progress or updates regarding the possibility of integrating Qt VNC server support for direct touchscreen input from the Nintendo 3DS into Lime3DS.
Thank you for taking the time to consider this matter.

TinyVNC: <https://gbatemp.net/threads/release-tinyvnc-vnc-viewer-for-nintendo-3ds.574242/>

### Why would this feature be useful?

As a user who uses the TinyVNC client on the 3DS for dedicated control experience, this feature would greatly improve the user experience. It would allow for seamless transmission of touchscreen inputs, streamlining the control process and opening up new possibilities for interaction and gameplay. By incorporating Qt VNC Server functionality, users like me would be able to directly transmit touchscreen input to the Lime3DS emulator, eliminating the need for additional hardware or complicated setup procedures. This improvement would undoubtedly enhance the emulation experience for all users who use external controllers or touchscreens.

**Comment by USMP-lancer** [comment]
i feel like this would defeat the point of the emulator, since if you have a modded 3ds, its likely that you can simply play the games on the console itself, but thats just my take on it.

**Comment by rtiangha** [comment]
I suspect they want to play on a bigger screen but keep the second screen on the 3DS.

Anyway, they may want to keep an eye out on PabloMK7's latest project **Artic Base** which will allow for streaming games from the 3DS to Citra without dumping them first, which might solve the issue. Not sure if it allows for input from the touchscreen at the same time, though.

https://twitter.com/Pablomf6/status/1787246255002853480

Edit: Looks like it won't be long now, but it also looks like it won't be able to use the 3DS as a controller right away. Technically, it should be possible, but who knows if he'll get around to implementing it. That said, it's pretty amazing as it is.

https://github.com/PabloMK7/citra/pull/105

**Comment by Vyacguru** [comment]
> i feel like this would defeat the point of the emulator, since if you have a modded 3ds, its likely that you can simply play the games on the console itself, but thats just my take on it.

In fact, I would like to have this feature because it would make streaming and recording my gameplay easier. For example, my girlfriend and I love the Zelda series of games. We have played most of them together, except for those released on the DS and 3DS, which are difficult to play on one small screen. It is also inconvenient to use an emulator with a gamepad and mouse, so I need this feature to have an easy way to control and see the gameplay on my PC's large screen.

**Comment by OpenSauce04** [comment]
I believe this was somewhat addressed with the addition of Artic Base to the extent that adding this functionality would be redundant.
