### ISSUE TITLE
(Android) Allow for the menu to be controlled using the mapped controller

### ISSUE THREAD

**Issue by bevans10037** [Lime3DS/Lime-3DS-Emulator#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

At the moment, when I'm in a game, and then press the Android back button to open the menu, my mapped controls still control the game in the background rather than the menu in the foreground.

### Why would this feature be useful?

Would make it significantly easier to navigate when using e.g. a docked setup with an external controller.

**Comment by OpenSauce04** [comment]
This is definitely something worth implementing. I will look into it.
