### ISSUE TITLE
Proposal: Executable filename updates

### ISSUE THREAD

**Issue by OpenSauce04** [Lime3DS/Lime-3DS-Emulator#171]
### Issue

This issue is a request for comment on a proposed rename of the executable filenames of Lime3DS.

The proposed updates are as follows: (Windows executables used as example)
`lime.exe` --> `lime3ds-cli.exe`
`lime-qt.exe` --> `lime3ds-gui.exe`
`lime-room.exe` --> `lime3ds-room.exe`

These changes intend to improve brand consistency by referring to the emulator by its full name, as well as helping uninformed users to understand which executable does what, as most users don't know what Qt is and are therefore unaware that it is the executable containing the GUI, possibly causing the conception of the emulator being buggy.

A misconception may be made that the basic `lime` executable is called by the `lime-qt` executable as a backend, but this in fact not the case from my testing, and instead these two executables seem to be able to work independently of each other. This can be evidenced by simply deleting the `lime` executable and observing `lime-qt` still emulating games fine. This further supports the case for these two executables being more distinguished from one another, hence the new `-cli` and `-gui` suffixes.

If enacted, this change is to be made only to the filenames of the final executables, and not to be implemented as a change to the directory names of the codebase itself; This is to prevent unnecessary complexity in the code source tree.

This change passing requires written approval from all current maintainers

**Comment by BlurrySquire** [comment]
I agree however I'm a bit on the fence with ``lime3ds-cli.exe`` because I think it is pretty self explanatory if you see one that says ``lime3ds.exe`` and one that then says ``lime3ds-gui.exe``. However, both work for me.

Edit: I re-read @OpenSauce04's message again. I think it would be better with ``lime3ds-cli.exe`` and ``lime3ds-gui.exe``.

**Comment by ayrudev** [comment]
That would be a welcome change, since we've had a fair share of people wondering why it kept "crashing" when it was just a case of them opening the wrong ``.exe``. (not blaming them since i've made the same when using citra in the past)
