### ISSUE TITLE
[Request] Pause emulation when open menu & save states ss

### ISSUE THREAD

**Issue by imadeput0287** [Lime3DS/Lime-3DS-Emulator#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

- Automatic pause emulation when open emulation menu
- Save & load states in separate list when click displaying list of Screen shot

### Why would this feature be useful?

When we go menu and emulation keep run, for action game will be bad. So please pause emulation and change pause emulation in menu to ne resume emulation

It will be more convenience

Thank you.

**Comment by OpenSauce04** [comment]
Thank you for your suggestion, however this will not be implemented as it would likely have a negative impact on the emulator's user experience. If you wish, you can simply pause emulation from the same menu when needed.
