### ISSUE TITLE
improve performance in super mario 3d land em GPU Mali please

### ISSUE THREAD

**Issue by LuisPerss** [Lime3DS/Lime-3DS-Emulator#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime 3ds 2110

### Description of Issue

The game is currently bad on my cell phone, at low FPS and with lag when in versions prior to Lime it was between 48 to 50 fps (in the previous versions of Citra) my cell phone has a bad GPU and I know it is difficult but the old developers They were able to do it, make the game playable in low-end Mali, but that optimization was broken and they did not solve it, please improve the performance of this game for Mali CPU.

### Expected Behavior

the game was based on the fact that it used to go at 48 and almost 55 fps in the past on my mali gpu cell phone, and now that this new version (lime) has been presented, it should be equal to that old performance or better, I would like it to recover its 50 fps performance at almost or all the time please

### Reproduction Steps

![Screenshot_20240319_144409_Citra](https://github.com/Lime3DS/Lime3DS/assets/154714667/fd63ef5f-89d3-4f96-883e-9efccc9ab192)

This is what its fps were like in previous versions of Citra, I managed to play the game little by little because in those versions the cell phone heated up a bit and I think it was due to the version, since I have tried several and there were some that heated the cell phone more and others not so much.

### Log File

![Screenshot_20240319_144409_Citra](https://github.com/Lime3DS/Lime3DS/assets/154714667/2b62f2ac-87f8-43c2-bdb1-c53b7c0c4135)

This is how its fps were in previous versions of Citra, it was exactly the Nighttli 2061, it had the best performance on Mali GPU or in my case and that performance was lost.

### System Configuration

CPU:Exynos 850
GPU/Driver:Mali GPU
RAM:4GB
OS:Android 13

**Comment by LuisPerss** [comment]
The FPS is almost not visible because of the white background that the game has, but they were around 55 or 56 fps more or less and in the game it was more or less around 43 or 48 and suddenly it changed to 55 depending on the area

**Comment by OpenSauce04** [comment]
There isn't much that can realistically be done to make the emulator run better on hardware which it is barely capable of running on. Looking at the list of devices which contain the Exynos 850, I am not surprised at the performance being poor.
Only thing I can suggest is trying the vulkan renderer if you haven't already.

**Comment by LuisPerss** [comment]
> De manera realista, no se puede hacer mucho para que el emulador funcione mejor en hardware en el que apenas es capaz de ejecutarse. Al mirar la lista de dispositivos que contienen el Exynos 850, no me sorprende que el rendimiento sea deficiente. Lo único que puedo sugerir es probar el renderizador vulkan si aún no lo has hecho.

I tested the lime 3ds emulator in version 2110 using vulkan and the 3d land was terrible, something that didn't happen before in the previous updates from the old developers, however the performance achieved in those updates was lost, that's why I ask you to please Optimize the game back on Mali GPU, since before it was better and now it isn't, and I tried the game several times on Vulkan and nothing.
