### ISSUE TITLE
External Display Feature!!!

### ISSUE THREAD

**Issue by DroidlyMobile** [Lime3DS/Lime-3DS-Emulator#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Add external display feature like Drastic has for devices that support OTG!

### Why would this feature be useful?

I was recently tinkering with Drastic and a project I'm working on, and realized I can use my OTG usb connection to conenct a second display with my Android and view whatever screen whether it's the top or bottom screen using Drastic for DS!!!  This means big things for my creation that I'm working on and if you can figure out the SDK that was used or someone can, to make this possilbe this would be the most epic aspect of Lime3DS.  The performance of it is amazing on multiple devices I own as well, but having Dual Display my golly would that be the most amazing feature of 2024!

**Comment by OpenSauce04** [comment]
Superseded by #351
