### ISSUE TITLE
Support for DirectX 11 and 12

### ISSUE THREAD

**Issue by Felipefpl** [Lime3DS/Lime-3DS-Emulator#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Support for DirectX 11 and 12

### Why would this feature be useful?

More backends to run any emulator is always good. Also, for some ppl the DirectX backend runs faster.

**Comment by OpenSauce04** [comment]
This would take an ungodly amount of time and resources for almost no gain
It's not as simple as just "adding more backends"
