### ISSUE TITLE
game shortcuts for android

### ISSUE THREAD

**Issue by Coderst1** [Lime3DS/Lime-3DS-Emulator#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Make it so that long pressing a game gives an option for cheats or making a shortcut

### Why would this feature be useful?

A little bit more ease of access to the games people play often

**Comment by ghost** [comment]
This feature might be added soon (it's incomplete and has bugs for now), so no promises
