### ISSUE TITLE
After I upgraded the application from version 2111 to version 2112, the instant save file in the game could not be read and an error occurred.

### ISSUE THREAD

**Issue by chy06201** [Lime3DS/Lime-3DS-Emulator#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v2112

### Description of Issue

After I upgraded the application from version 2111 to version 2112, the instant save file in the game could not be read and an error occurred.

### Expected Behavior

File read successfully

### Reproduction Steps

Read and save instantly

### Log File

![微信图片_20240514105952](https://github.com/Lime3DS/Lime3DS/assets/31204604/59c1d734-ad3c-44a6-8a57-6855129fbafc)
![微信图片_20240514105958](https://github.com/Lime3DS/Lime3DS/assets/31204604/bebc9d47-78ed-42b6-8bcc-5961b713841f)

### System Configuration

CPU: 8GEN3
GPU/Driver:
RAM:16G
OS: Xiaomi ThePaper OS

**Comment by Coderst1** [comment]
By "instant save file" do you mean save states?
If this is the case, then that was bound to happen as usually trying to load save states on another version will break the save state

**Comment by chy06201** [comment]
> By "instant save file" do you mean save states? If this is the case, then that was bound to happen as usually trying to load save states on another version will break the save state

Yes, as you said about saving the state, is there a way to solve this problem?

**Comment by Coderst1** [comment]
> > By "instant save file" do you mean save states? If this is the case, then that was bound to happen as usually trying to load save states on another version will break the save state
> 
> Yes, as you said about saving the state, is there a way to solve this problem?

You'd need to revert back to version 2111 and save in game

**Comment by OpenSauce04** [comment]
I will close this issue under user error; Using save states displays a warning for a reason.
They are not to be used as a substitute for regular saves, and are only to be used for cases such as re-attempting a certain section of a game or rewinding time.
