### ISSUE TITLE
lime crashes with custom textures

### ISSUE THREAD

**Issue by thidguy** [Lime3DS/Lime-3DS-Emulator#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3DS 2112

### Description of Issue

lime crashes with custom textures  only on new super mario bros 2. just on the latest Lime3DS 2112 version but dosent with Lime3DS 2111

### Expected Behavior

its just supost to load textures and work 

### Reproduction Steps

[000400000007AE00.zip](https://github.com/Lime3DS/Lime3DS/files/15340118/000400000007AE00.zip)
here are the textures im trying to use

### Log File

[lime3ds_log.txt](https://github.com/Lime3DS/Lime3DS/files/15340133/lime3ds_log.txt)

### System Configuration

CPU:i7 14th gen 
GPU/Driver: 4080 driver ver 552.44
RAM:
OS:win 11

**Comment by OpenSauce04** [comment]
The log seems to indicate that some of the images in the texture pack are corrupted. Have you tried another game/ texture pack?

**Comment by thidguy** [comment]
using opengl kinda work but messes up the textures also using a diffrent version works perfectly
