### ISSUE TITLE
Mario and Donkey Kong Minis on the Move Create & Share - Crash

### ISSUE THREAD

**Issue by Fernando11101** [Lime3DS/Lime-3DS-Emulator#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3DS 2112

### Description of Issue

Mario and Donkey Kong Minis on the Move crashes after pressing Create & Share, Tested With OpenGL, Vulkan and Software renderer. OpenGL and Vulkan crash the emulator but on Software renderer doesn't crash the emulator but freezes the game completely.

### Expected Behavior

OpenGL: ![Captura de pantalla 2024-05-16 203541](https://github.com/Lime3DS/Lime3DS/assets/44506229/2936851f-9f3d-4e26-8677-d920c947bc8d)
Vulkan: ![Captura de pantalla 2024-05-16 204247](https://github.com/Lime3DS/Lime3DS/assets/44506229/d6f878cd-b1a5-47fd-b342-d0d8d990eeb5)
Software: ![Captura de pantalla 2024-05-16 210804](https://github.com/Lime3DS/Lime3DS/assets/44506229/88ca0d9b-da53-488f-ada3-7ba413be0838)

### Reproduction Steps

1. Load Mario and Donkey Kong Minis on the Move.
2. Wait for load the menu.
3. After loaded the menu just click on Create & Share.

### Log File

OpenGL: [lime3ds_log.txt](https://github.com/Lime3DS/Lime3DS/files/15343357/lime3ds_log.txt)
Vulkan: [lime3ds_log.txt](https://github.com/Lime3DS/Lime3DS/files/15343370/lime3ds_log.txt)
Software: [lime3ds_log.zip](https://github.com/Lime3DS/Lime3DS/files/15343585/lime3ds_log.zip)

### System Configuration

CPU: AMD A4-9125
GPU/Driver: AMD Radeon(TM) R3 Graphics
RAM: 8GB 3200MHz
OS: Windows 10

**Comment by YGOmod** [comment]
you can bypass it by hex editing savefile.. it tries to call function which handles your username.. after you give username, it proceed later
![Screenshot_20240613_202030_Lime3DS](https://github.com/Lime3DS/Lime3DS/assets/130164085/aeb49249-1832-4fa7-ba18-6ce2f25aa8d6)
