### ISSUE TITLE
add Orientation option

### ISSUE THREAD

**Issue by Deka710** [Lime3DS/Lime-3DS-Emulator#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Orientation option
![Screenshot_2024-05-17-16-12-23-657_org yuzu yuzu_emu](https://github.com/Lime3DS/Lime3DS/assets/97207704/fc71d915-3bc7-4c92-b8d0-81659fb0b2a6)

### Why would this feature be useful?

u don't have to rotate your phone everytime because its pretty annoying.

**Comment by OpenSauce04** [comment]
One of our contributors is planning a pull request which will implement this feature. It will hopefully debut in either 2113 or 2114
