### ISSUE TITLE
Monster Hunter Stories Weapon Upgrade Bug

### ISSUE THREAD

**Issue by Onre64** [Lime3DS/Lime-3DS-Emulator#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2112

### Description of Issue

![image](https://github.com/Lime3DS/Lime3DS/assets/111638647/4a99003c-86f0-428d-bf61-3993e10252a0)
![image](https://github.com/Lime3DS/Lime3DS/assets/111638647/eb07306a-427a-4147-8914-47ab6e88e442)
After Upgrading a Weapon the Game ist not responding anymore  but the Emulation is Fine

I can restart or Close but the Game has no response 
music is fine
Its like the Game is in a loading loop or waiting for something to progress 

### Expected Behavior

Game should go on after Upgrade a Weapon

### Reproduction Steps

Upgrade a Weapon  and you get stuck 

### Log File

[   0.109599] Input <Info> input_common/udp/client.cpp:StartCommunication:206: Starting communication with UDP input server on 127.0.0.1:26760
[   0.381099] Frontend <Info> lime_qt/main.cpp:GMainWindow:222: Lime3DS Version: 2112 | HEAD-467afbb
[   0.381111] Frontend <Info> lime_qt/main.cpp:GMainWindow:237: Host CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz | AVX2 | FMA
[   0.381246] Frontend <Info> lime_qt/main.cpp:GMainWindow:239: Host OS: Windows 10 Version 22H2 (Build 19045.4412)
[   0.381255] Frontend <Info> lime_qt/main.cpp:GMainWindow:242: Host RAM: 31.93 GiB
[   0.381255] Frontend <Info> lime_qt/main.cpp:GMainWindow:243: Host Swap: 4.75 GiB
[   0.481447] Frontend <Info> lime_qt/main.cpp:CheckForUpdates:1022: Update check started
[   2.595176] Frontend <Info> lime_qt/main.cpp:BootGame:1270: Lime3DS starting...
[   2.595309] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   2.595316] Frontend <Info> lime_qt/main.cpp:BootGame:1293: Loading per game config file for title 00040000001BC600
[   2.601170] Config <Info> common/settings.cpp:LogSettings:83: Lime3DS Configuration:
[   2.601174] Config <Info> common/settings.cpp:operator():80: Core_UseCpuJit: true
[   2.601175] Config <Info> common/settings.cpp:operator():80: Core_CPUClockPercentage: 100
[   2.601175] Config <Info> common/settings.cpp:operator():80: Renderer_UseGLES: false
[   2.601175] Config <Info> common/settings.cpp:operator():80: Renderer_GraphicsAPI: Vulkan
[   2.601176] Config <Info> common/settings.cpp:operator():80: Renderer_AsyncShaders: true
[   2.601176] Config <Info> common/settings.cpp:operator():80: Renderer_AsyncPresentation: true
[   2.601176] Config <Info> common/settings.cpp:operator():80: Renderer_SpirvShaderGen: true
[   2.601177] Config <Info> common/settings.cpp:operator():80: Renderer_Debug: false
[   2.601177] Config <Info> common/settings.cpp:operator():80: Renderer_UseHwShader: true
[   2.601177] Config <Info> common/settings.cpp:operator():80: Renderer_ShadersAccurateMul: true
[   2.601178] Config <Info> common/settings.cpp:operator():80: Renderer_UseShaderJit: true
[   2.601178] Config <Info> common/settings.cpp:operator():80: Renderer_UseResolutionFactor: 3
[   2.601178] Config <Info> common/settings.cpp:operator():80: Renderer_FrameLimit: 100
[   2.601179] Config <Info> common/settings.cpp:operator():80: Renderer_VSyncNew: false
[   2.601179] Config <Info> common/settings.cpp:operator():80: Renderer_PostProcessingShader: none (builtin)
[   2.601179] Config <Info> common/settings.cpp:operator():80: Renderer_FilterMode: true
[   2.601180] Config <Info> common/settings.cpp:operator():80: Renderer_TextureFilter: MMPX
[   2.601180] Config <Info> common/settings.cpp:operator():80: Renderer_TextureSampling: Linear
[   2.601182] Config <Info> common/settings.cpp:operator():80: Stereoscopy_Render3d: 0
[   2.601183] Config <Info> common/settings.cpp:operator():80: Stereoscopy_Factor3d: 0
[   2.601184] Config <Info> common/settings.cpp:operator():80: Stereoscopy_MonoRenderOption: 0
[   2.601184] Config <Info> common/settings.cpp:operator():80: Layout_LayoutOption: 3
[   2.601185] Config <Info> common/settings.cpp:operator():80: Layout_SwapScreen: false
[   2.601185] Config <Info> common/settings.cpp:operator():80: Layout_UprightScreen: false
[   2.601186] Config <Info> common/settings.cpp:operator():80: Layout_LargeScreenProportion: 4
[   2.601186] Config <Info> common/settings.cpp:operator():80: Utility_DumpTextures: false
[   2.601186] Config <Info> common/settings.cpp:operator():80: Utility_CustomTextures: false
[   2.601187] Config <Info> common/settings.cpp:operator():80: Utility_PreloadTextures: false
[   2.601187] Config <Info> common/settings.cpp:operator():80: Utility_AsyncCustomLoading: true
[   2.601187] Config <Info> common/settings.cpp:operator():80: Utility_UseDiskShaderCache: true
[   2.601188] Config <Info> common/settings.cpp:operator():80: Audio_Emulation: HLE
[   2.601188] Config <Info> common/settings.cpp:operator():80: Audio_OutputType: 0
[   2.601188] Config <Info> common/settings.cpp:operator():80: Audio_OutputDevice: auto
[   2.601190] Config <Info> common/settings.cpp:operator():80: Audio_InputType: 0
[   2.601190] Config <Info> common/settings.cpp:operator():80: Audio_InputDevice: auto
[   2.601191] Config <Info> common/settings.cpp:operator():80: Audio_EnableAudioStretching: true
[   2.601191] Config <Info> common/settings.cpp:operator():80: Camera_OuterRightName: blank
[   2.601191] Config <Info> common/settings.cpp:operator():80: Camera_OuterRightConfig: 
[   2.601192] Config <Info> common/settings.cpp:operator():80: Camera_OuterRightFlip: 0
[   2.601192] Config <Info> common/settings.cpp:operator():80: Camera_InnerName: blank
[   2.601192] Config <Info> common/settings.cpp:operator():80: Camera_InnerConfig: 
[   2.601192] Config <Info> common/settings.cpp:operator():80: Camera_InnerFlip: 0
[   2.601193] Config <Info> common/settings.cpp:operator():80: Camera_OuterLeftName: blank
[   2.601193] Config <Info> common/settings.cpp:operator():80: Camera_OuterLeftConfig: 
[   2.601193] Config <Info> common/settings.cpp:operator():80: Camera_OuterLeftFlip: 0
[   2.601194] Config <Info> common/settings.cpp:operator():80: DataStorage_UseVirtualSd: true
[   2.601194] Config <Info> common/settings.cpp:operator():80: DataStorage_UseCustomStorage: false
[   2.601194] Config <Info> common/settings.cpp:operator():80: System_IsNew3ds: true
[   2.601195] Config <Info> common/settings.cpp:operator():80: System_LLEApplets: false
[   2.601195] Config <Info> common/settings.cpp:operator():80: System_RegionValue: -1
[   2.601195] Config <Info> common/settings.cpp:operator():80: System_PluginLoader: false
[   2.601196] Config <Info> common/settings.cpp:operator():80: System_PluginLoaderAllowed: true
[   2.601196] Config <Info> common/settings.cpp:operator():80: Debugging_DelayStartForLLEModules: true
[   2.601196] Config <Info> common/settings.cpp:operator():80: Debugging_UseGdbstub: false
[   2.601197] Config <Info> common/settings.cpp:operator():80: Debugging_GdbstubPort: 24689
[   2.697406] Audio.DSP <Info> audio_core/hle/aac_decoder.cpp:AACDecoder:27: Created FAAD2 AAC decoder.
[   2.715384] Audio.Sink <Info> audio_core/cubeb_sink.cpp:StateCallback:135: Cubeb Audio Stream Started
[   2.715394] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:14: Starting RPC server.
[   2.715519] RPC_Server <Info> core/rpc/rpc_server.cpp:HandleRequestsLoop:104: Request handler started.
[   2.716727] Common.Filesystem <Error> ./core/file_sys/cia_common.h:GetSignatureSize:36: Tried to read ticket with bad signature 1066286284
[   2.716729] Service.FS <Error> core/file_sys/title_metadata.cpp:Load:27: Failed to load TMD from file C:\Users\Onre\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004008c/001bc600/content/00000000.tmd!
[   2.717873] Service.HTTP <Error> core/hle/service/http/http_c.cpp:DecryptClCertA:1974: ClCertA file missing
[   2.726423] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():433: Enabling extension: VK_KHR_swapchain
[   2.726426] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():433: Enabling extension: VK_KHR_image_format_list
[   2.726427] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:operator():442: Extension VK_EXT_shader_stencil_export unavailable.
[   2.726428] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():433: Enabling extension: VK_EXT_external_memory_host
[   2.726429] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():433: Enabling extension: VK_EXT_tooling_info
[   2.726430] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():433: Enabling extension: VK_KHR_timeline_semaphore
[   2.726431] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:operator():442: Extension VK_KHR_portability_subset unavailable.
[   2.726431] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():433: Enabling extension: VK_EXT_extended_dynamic_state
[   2.726432] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():433: Enabling extension: VK_EXT_custom_border_color
[   2.726433] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():433: Enabling extension: VK_EXT_index_type_uint8
[   2.726433] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:operator():438: Extension VK_EXT_fragment_shader_interlock has been blacklisted because it is broken on Nvidia drivers
[   2.726434] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:operator():438: Extension VK_EXT_pipeline_creation_cache_control has been blacklisted because it is broken on Nvidia drivers
[   2.726435] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:operator():433: Enabling extension: VK_KHR_fragment_shader_barycentric
[   2.793762] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:CreateFormatTable:303: Format B8G8R8Unorm unsupported, falling back unconditionally to R8G8B8A8Unorm
[   2.793766] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:CreateFormatTable:303: Format R5G5B5A1UnormPack16 unsupported, falling back unconditionally to R8G8B8A8Unorm
[   2.793767] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_instance.cpp:CreateFormatTable:303: Format R4G4B4A4UnormPack16 unsupported, falling back unconditionally to R8G8B8A8Unorm
[   2.793787] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:CollectToolingInfo:670: VK_DRIVER: NVIDIA 536.23.0.0
[   2.793787] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:CollectToolingInfo:671: VK_DEVICE: NVIDIA GeForce GTX 1660 Ti
[   2.793788] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:CollectToolingInfo:672: VK_VERSION: 1.3.242
[   2.801955] Render.Vulkan <Info> video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:178: Creating Stream buffer with size 128 KiB with flags { DeviceLocal | HostVisible | HostCoherent }
[   2.899265] Render.Vulkan <Info> video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:178: Creating Upload buffer with size 524288 KiB with flags { HostVisible | HostCoherent }
[   2.900172] Render.Vulkan <Info> video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:178: Creating Download buffer with size 16384 KiB with flags { HostVisible | HostCoherent | HostCached }
[   2.923026] Render.Vulkan <Info> video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:178: Creating Stream buffer with size 65536 KiB with flags { DeviceLocal | HostVisible | HostCoherent }
[   2.923686] Render.Vulkan <Info> video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:178: Creating Stream buffer with size 4096 KiB with flags { DeviceLocal | HostVisible | HostCoherent }
[   2.929808] Render.Vulkan <Info> video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:178: Creating Stream buffer with size 2048 KiB with flags { DeviceLocal | HostVisible | HostCoherent }
[   2.952370] Render.Vulkan <Info> video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:178: Creating Stream buffer with size 2048 KiB with flags { DeviceLocal | HostVisible | HostCoherent }
[   2.978005] Loader <Info> core/loader/ncch.cpp:Load:270: Program ID: 00040000001BC600
[   2.978124] Service.FS <Warning> core/file_sys/ncch_container.cpp:OpenFile:126: Failed to open C:\Users\Onre\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/001bc600/content/00000000.app
[   3.023513] Loader <Info> core/hle/kernel/process.cpp:ParseKernelCaps:196: ExHeader kernel version: 2.50
[   3.035046] Core.Cheats <Warning> core/cheats/gateway_cheat.cpp:SetEnabled:434: Cheats enabled. This might lead to weird behaviour or crashes
[   3.035053] Core.Cheats <Warning> core/cheats/gateway_cheat.cpp:SetEnabled:434: Cheats enabled. This might lead to weird behaviour or crashes
[   3.035073] Core.Cheats <Warning> core/cheats/gateway_cheat.cpp:SetEnabled:434: Cheats enabled. This might lead to weird behaviour or crashes
[   3.035075] Core.Cheats <Warning> core/cheats/gateway_cheat.cpp:SetEnabled:434: Cheats enabled. This might lead to weird behaviour or crashes
[   3.043320] Service.CAM <Info> lime_qt/camera/qt_multimedia_camera.cpp:ResumeCameras:50: Resuming all cameras
[   3.043695] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:LoadDiskCache:166: Loading pipeline cache with size 12248 KB
[   3.043736] Core <Warning> core/savestate.cpp:ValidateSaveState:82: Save state file C:\Users\Onre\AppData\Roaming/Citra/states/00040000001BC600.01.cst created from a different build Nightly 2104 with revision 0ff3440232d6bc9226e37c41c05c5aead03f37fd
[   3.043803] Core <Warning> core/savestate.cpp:ValidateSaveState:82: Save state file C:\Users\Onre\AppData\Roaming/Citra/states/00040000001BC600.02.cst created from a different build Nightly 2095 with revision 5e02be75a38de316f0cf47182edf38ad6e9526fd
[   3.130477] Service.SRV <Warning> core/hle/service/sm/srv.cpp:RegisterClient:63: (STUBBED) called. Caller PID=11
[   3.493234] Service.SRV <Warning> core/hle/service/sm/srv.cpp:EnableNotification:85: (STUBBED) called
[   3.498120] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:OverrideDefaultDaemons:186: (STUBBED) bit_mask=0x0000000F
[   3.498257] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:SuspendDaemons:74: (STUBBED) bit_mask=0x00000006
[   3.499191] Service.FS <Warning> core/hle/service/fs/fs_user.cpp:InitializeWithSdkVersion:1062: (STUBBED) called, version: 0x0B0400C8
[   3.500019] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:209: Delay generator was not initalized. Using default
[   3.505989] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:209: Delay generator was not initalized. Using default
[   3.865113] Service.CFG <Info> core/hle/service/cfg/cfg.cpp:UpdatePreferredRegionCode:674: Preferred region code set to 2
[   3.865654] Service.APT <Warning> core/hle/service/apt/apt.cpp:SetAppCpuTimeLimit:710: (STUBBED) called, must_be_one=1, value=25
[   4.336788] Service.SRV <Warning> core/hle/service/sm/srv.cpp:Subscribe:212: (STUBBED) called, notification_id=0x207
[   4.336911] Service.SRV <Warning> core/hle/service/sm/srv.cpp:Subscribe:212: (STUBBED) called, notification_id=0x209
[   4.574260] Service.APT <Warning> core/hle/service/apt/apt.cpp:NotifyToWait:338: (STUBBED) app_id=768
[   4.576155] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:689: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001
[   4.576395] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:689: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[   4.576835] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:689: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[   4.577018] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:168: unknown / unimplemented function 'GetAppletProgramInfo': port='APT:A' cmd_buf={[0]=0x4d0080 (0x004D, 2, 0), [1]=0x301, [2]=0x11}
[   4.578028] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:168: unknown / unimplemented function 'Initialize': port='nim:aoc' cmd_buf={[0]=0x210000 (0x0021, 0, 0)}
[   4.579116] Service.APT <Warning> core/hle/service/apt/apt.cpp:SetAppCpuTimeLimit:710: (STUBBED) called, must_be_one=1, value=30
[   4.724475] Service.IR <Info> core/hle/service/ir/ir_user.cpp:InitializeIrNopShared:303: called, shared_buff_size=4096, recv_buff_size=82, recv_buff_packet_count=1, send_buff_size=18, send_buff_packet_count=1, baud_rate=4
[   4.726369] Service.IR <Info> core/hle/service/ir/ir_user.cpp:GetConnectionStatusEvent:374: called
[   4.727145] Service.IR <Info> core/hle/service/ir/ir_user.cpp:RequireConnection:330: called, device_id = 1
[   4.727935] Service.IR <Info> core/hle/service/ir/ir_user.cpp:GetReceiveEvent:339: called
[   4.729442] Service.IR <Info> core/hle/service/ir/ir_user.cpp:Disconnect:365: called
[   4.729605] Service.IR <Info> core/hle/service/ir/ir_user.cpp:FinalizeIrNop:389: called
[   4.730752] Service.IR <Info> core/hle/service/ir/ir_user.cpp:InitializeIrNopShared:303: called, shared_buff_size=4096, recv_buff_size=3280, recv_buff_packet_count=160, send_buff_size=768, send_buff_packet_count=32, baud_rate=4
[   4.730954] Service.IR <Info> core/hle/service/ir/ir_user.cpp:GetConnectionStatusEvent:374: called
[   4.730965] Service.IR <Info> core/hle/service/ir/ir_user.cpp:RequireConnection:330: called, device_id = 1
[   4.731267] Service.IR <Info> core/hle/service/ir/ir_user.cpp:GetReceiveEvent:339: called
[   4.731439] Service.IR <Info> core/hle/service/ir/ir_user.cpp:GetSendEvent:348: called
[   5.028969] Service.FS <Error> core/file_sys/archive_extsavedata.cpp:OpenFile:139: C:\Users\Onre\AppData\Roaming/Citra/nand/data/00000000000000000000000000000000/extdata/00048000/F000000B/user/ubll.lst not found
[   5.056399] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:460: Firmware hash: 0xdcdb8c683bf28fdd
[   5.056402] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:464: Structures hash: 0x228655de1258d999
[   5.056403] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:LoadComponent:192: called size=0xC25C, prog_mask=0x00FF, data_mask=0x00FF
[   5.057092] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:RegisterInterruptEvents:259: Registered interrupt=2, channel=2, event=event-00801ab8
[   5.057270] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:GetSemaphoreEventHandle:275: (STUBBED) called
[   5.057441] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphoreMask:285: (STUBBED) called mask=0x2000
[   5.057683] Audio.DSP <Info> audio_core/hle/hle.cpp:PipeWrite:224: Application has requested initialization of DSP hardware
[   5.057804] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
[   5.058838] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
[   7.017786] Service.NFC <Info> core/hle/service/nfc/nfc.cpp:Initialize:28: called, communication_mode=2
[   7.018135] Service.NFC <Info> core/hle/service/nfc/nfc.cpp:GetActivateEvent:240: called
[   7.018428] Service.NFC <Info> core/hle/service/nfc/nfc.cpp:GetDeactivateEvent:257: called
[  30.563519] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenArchive:677: failed to get a handle for archive archive_id=0x00000006 archive_path=[Binary: 010000005b18000000000000]
[  39.875716] Frontend <Info> lime_qt/main.cpp:OnUpdateFound:1035: No updates found
[  50.783115] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:209: Delay generator was not initalized. Using default
[  50.797769] Service.FS <Error> ./core/file_sys/file_backend.h:GetReadDelayNs:51: Delay generator was not initalized. Using default

### System Configuration

CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
GPU/Driver: NVIDIA GeForce GTX 1660 Ti
RAM: 32692 MB
OS: Win 10

**Comment by Mert879** [comment]
I lost three hours of progress, becouse of this. The game runs perfectly fine, like you can see your character/sword move but you just can't leave the upgrades tab.

![Unbenannt](https://github.com/user-attachments/assets/946d521b-8572-438b-bdc4-298826ca3aae)

**Comment by OpenSauce04** [comment]
Please upload the log as a file and edit out the wall of text in your issue
