### ISSUE TITLE
Luigi's Mansion 1 Co-op not working

### ISSUE THREAD

**Issue by Reskell** [Lime3DS/Lime-3DS-Emulator#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2112

### Description of Issue

Coop mode of LM1 not working,  we cant find each other 

### Expected Behavior

When it work, Luigi and Gooigi cant do the story together

### Reproduction Steps

2 player with same version of Citra/Lime, same rom, same setting, Hamachi for emulate the lan/local connexion (on the real game, both player need to be in local)
After tutorial both player choose to play with other but it not working.

### Log File

None

### System Configuration

CPU: Ryzen 7 
GPU/Driver: RTX 3080
RAM: 64Go
OS: windows 10

**Comment by OpenSauce04** [comment]
> 2 player with same version of Citra/Lime

Are you both using the same emulator? This message implies that you were using two different forks

**Comment by Reskell** [comment]
Oh yes sorry my bad, we use the same version of Lime.

**Comment by JomSpoons** [comment]
This same issue still occurs in Azahar 2120.3. We have confirmed that Tri Force Heroes works properly using the emulator's multiplayer room feature, but when trying to play Luigi's Mansion we are unable to find each other while the game is attempting to search for other players. I'd like to request this issue be reopened if that's alright.
