### ISSUE TITLE
LM1 COOP DOESNT WORK'

### ISSUE THREAD

**Issue by LITTLECHOPT8** [Lime3DS/Lime-3DS-Emulator#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2113

### Description of Issue

coop gives error instantly

### Expected Behavior

should connect succsesfully and start game as luigi and gooigi

### Reproduction Steps

just try to do coop and it will error

### Log File

dont have one atm

### System Configuration

CPU: i7 12 gen
GPU/Driver: rtx 3050ti
RAM: 16gb
OS: windows 11

**Comment by OpenSauce04** [comment]
This issue does not contain nearly enough information. Please fill out the fields properly, including the type of error you are experiencing alongside the log file
