### ISSUE TITLE
Fix Windows MSYS2 Build

### ISSUE THREAD

**Issue by ryzendew** [Lime3DS/Lime-3DS-Emulator#21]

**Comment by rtiangha** [comment]
It's as simple as a `git revert 667800f` unless there's more that needs to be done.

**Comment by ayrudev** [comment]
> It's as simple as a `git revert 667800f` unless there's more that needs to be done.

it isn't, I've commented it out since it was throwing errors when building

**Comment by ayrudev** [comment]
closing since we already have it on the to-do list
