### ISSUE TITLE
LEGO City Undercover - breaking glitch (not present in older builds) - Tony Knuckles stops on the roof

### ISSUE THREAD

**Issue by michaljuris** [Lime3DS/Lime-3DS-Emulator#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2113

### Description of Issue

LEGO City Undercover Chase Begins - decrypted version (tested both US and Europe)
In Chapter 1 - Mission "Taking Out The Trash" during the chase on the roof with Tony Knuckles he just stops running and nothing triggers his run again - so it is impossible to finish the mission.
<img width="1394" alt="image" src="https://github.com/Lime3DS/Lime3DS/assets/391000/ef82836f-3248-45a5-a30f-f2f2ad8a1ce2">

### Expected Behavior

Knuckles keeps running when I approach him.

### Reproduction Steps

Start mission "Taking Out The Trash" - start chasing Knuckles on the roof.
sdmc and states included
[sdmc.zip](https://github.com/Lime3DS/Lime3DS/files/15440831/sdmc.zip)
[states.zip](https://github.com/Lime3DS/Lime3DS/files/15440928/states.zip)

### Log File

[lime3ds_log.txt](https://github.com/Lime3DS/Lime3DS/files/15440926/lime3ds_log.txt)

### System Configuration

It was tested on SteamDeck, MacOS, Android, OpenGL/Vulkan with the same behavior.

**Comment by michaljuris** [comment]
I've managed to download nightly-1795 for Android (couldn't get any other Appimage or Mac version) and can confirm that the bug is not present in that version and I was able to transfer savegame to the recent version.

**Comment by EinTim23** [comment]
This issue still exists these days

**Comment by michaljuris** [comment]
> This issue still exists these days

The only way around it for me was to play the game using an Android emulator, beyond this point, and then transferring the savegame file. The rest of the game worked fine.
