### ISSUE TITLE
Bug the level and cutscenes

### ISSUE THREAD

**Issue by YohannGuihard** [Lime3DS/Lime-3DS-Emulator#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Dans la version 2113

### Description of Issue

When I play games, the English cutscenes are out of sync and glitch, and sometimes during levels, the image glitches.

### Expected Behavior

When I play games, the English cutscenes are out of sync and glitch, and sometimes during levels, the image glitches.

### Reproduction Steps

When I play games, the English cutscenes are out of sync and glitch, and sometimes during levels, the image glitches.

### Log File

It bugs every day. When I press the game, it can take a long time to launch and the main menu images can bug. And when I go into a game, the cinematic bugs and the sound and music bug and are out of sync. And when I play levels or launch games, the images start to bug every time I launch the game.

### System Configuration

My RAM the phone and 4GO

**Comment by OpenSauce04** [comment]
This issue does not correctly follow the format. Please follow out each field with distinct content rather than copy-pasting the same message 3 times. The game in which the issue occurs, your full system specifications, and a log file will also be required.
