### ISSUE TITLE
Bug of cutscenes, game and image 

### ISSUE THREAD

**Issue by YohannGuihard** [Lime3DS/Lime-3DS-Emulator#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

version 2113

### Description of Issue

When I play games, the cutscenes are out of sync and glitch, and sometimes during levels, the image glitches.

### Expected Behavior

When I play games, the cutscenes are out of sync and glitch, and sometimes during levels, the image glitches.

### Reproduction Steps

When I play games, the cutscenes are out of sync and glitch, and sometimes during levels, the image glitches.

### Log File

It bugs every day. When I press the game, it can take a long time to launch and the main menu images can bug. And when I go into a game, the cinematic bugs and the sound and music bug and are out of sync. And when I play levels or launch games, the images start to bug every time I launch the game.

### System Configuration

My RAM the phone and 4GO

**Comment by fallingSparr0w** [comment]
Regression of #213

**Comment by OpenSauce04** [comment]
Duplicate of #213
