### ISSUE TITLE
Choose language

### ISSUE THREAD

**Issue by YohannGuihard** [Lime3DS/Lime-3DS-Emulator#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I'would like that for all games, we can choose multiple languages that will allow us to read subtitles and hear voices in French or other languages. When we exit the game and come back, we shouldn't have to choose the game language again; it should be set permanently (because I am French translating into English). In some games, the voices are not in my language."

### Why would this feature be useful?

It will be useful so that everyone can discover or play games in their native language without jealousy

**Comment by fallingSparr0w** [comment]
We cannot change in-game voices to different languages - that is what community patches are for. As for different languages, the emulator already supports a multitude of them.

**Comment by OpenSauce04** [comment]
This is outside of the scope of an emulator
