### ISSUE TITLE
VVVVVV - Performance Issue

### ISSUE THREAD

**Issue by Fernando11101** [Lime3DS/Lime-3DS-Emulator#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3DS 2113

### Description of Issue

When you start the game, the performance worsens a lot, having extremely low FPS.

### Expected Behavior

![Captura de pantalla 2024-05-25 201119](https://github.com/Lime3DS/Lime3DS/assets/44506229/a4b7953d-74a3-4a13-8b41-3244406b10cc)

### Reproduction Steps

1. Just start VVVVVV.

### Log File

[lime3ds_log.txt](https://github.com/Lime3DS/Lime3DS/files/15445956/lime3ds_log.txt)

### System Configuration

CPU: AMD A4-9125
GPU/Driver: AMD Radeon(TM) R3 Graphics
RAM: 8GB 3200MHz
OS: Windows 10

**Comment by Riot20058** [comment]
CPU low end one for 2018 try on s23 plus was no bugs with slowdown after start the game sure not just hardware bug.
