### ISSUE TITLE
Make the unified source tarball related to the version only

### ISSUE THREAD

**Issue by arthsmn** [Lime3DS/Lime-3DS-Emulator#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Make the name of the unified source tarball related only to the version, so it's easy to be scripted when updating versions.

### Why would this feature be useful?

Better for packagers and it'll make it more consistent.

**Comment by OpenSauce04** [comment]
I am fine with this. It will be included in 2114

**Comment by OpenSauce04** [comment]
Addressed in 9ac1d33f1e90c6c10f07f13f6caec625cf30ab92
