### ISSUE TITLE
Android: Crash when starting a game

### ISSUE THREAD

**Issue by Morningstar20009** [Lime3DS/Lime-3DS-Emulator#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2114

### Description of Issue

Every time I try to start a game it indicates that there is a bug or that I need to clear the cache or that I have to wait for an update to fix it.  the characteristics of my phone are:  8g ram  128 GB memory it's a Samsung A55  

https://github.com/Lime3DS/Lime3DS/assets/170994877/75b5c0fe-2290-4d1c-ab09-c5eb272eae70

### Expected Behavior

normally it should start and I wonder if I'm the only one in this situation  

### Reproduction Steps

. 

### Log File

.

### System Configuration

Android 14
Ram 8go
128go

**Comment by Dwisantosobk** [comment]
same problem with samsung galaxy a71

**Comment by OpenSauce04** [comment]
Please test if this issue has been fixed in 2114.1

**Comment by Morningstar20009** [comment]
> Please test if this issue has been fixed in 2114.1


unfortunately it still doesn't work 

https://github.com/Lime3DS/Lime3DS/assets/170994877/7c05fd97-54dd-4e73-9981-c71cc0df5823

**Comment by YGOmod** [comment]
are you able to produce a .log file and upload it? there should be 2 files in inside log folder, lime3ds_log.txt and lime3ds_log.old.txt.. upload both 👍🏻

**Comment by Morningstar20009** [comment]
> are you able to produce a .log file and upload it? there should be 2 files in the log folder, lime3ds_log.txt and lime3ds_log.old.txt.. download both 👍🏻

 I tried with my old phone less with it's 4GB ram efficient it's an infinix note 7 and there the games start without problem even if it's slow the problem comes from the phone

**Comment by Morningstar20009** [comment]
> same problem with the Samsung Galaxy A71

 it works on your phone and if you have a solution don't hesitate to tell us 😅

**Comment by Dwisantosobk** [comment]
Im just install new update

**Comment by Silver5664** [comment]
Updated to latest build. Running on Raspberry Pi 5 with Android 14. Same issue. Here are the log dumps.

Seems to be related to files not being found and content URI errors.

Note: I was also getting this issue with version 2112 and Citra, so it may be a possibility that while the visual result is similar, the underlying cause is different.

[lime3ds_log.old.txt](https://github.com/Lime3DS/Lime3DS/files/15498856/lime3ds_log.old.txt)
[lime3ds_log.txt](https://github.com/Lime3DS/Lime3DS/files/15498857/lime3ds_log.txt)

**Comment by whateverlior** [comment]
Have you tried switching to vulkan? for me it worked. with the same phone here btw

**Comment by rtiangha** [comment]
Does removing the spaces from the rom's file name help? Try renaming it to something simple with just regular letters like MonsterHunter4.3ds. This is just a sanity test to see if it's an issue with special characters or file name length.
