### ISSUE TITLE
Shin Megami Tensei 4 Apocalypse crash at the transition to the final area of the game

### ISSUE THREAD

**Issue by reallitup2** [Lime3DS/Lime-3DS-Emulator#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v2113

### Description of Issue

Hello! A friend of mine was playing Shin Megami Tensei 4 Apocalypse when the emulator would crash on the final dungeon of the game after touching the monolith every time without fail. We tried deleting shader caches and even switching up from OpenGL to Vulkan, but the whole emulator would crash upon entering the final dungeon, which is reportedly very buggy on a lot of emulators. 

### Expected Behavior

Normally you're supposed to just go into the final dungeon, but it always crashes the emulator once the transition finishes.

### Reproduction Steps

Reproduction is pretty simple. Just play through the game until Steven creates the Monolith and then proceed to enter the dungeon. Predictably, the emulator will crash and we have not found any fixes online.

### Log File

[lime3ds_log.txt](https://github.com/user-attachments/files/15518976/lime3ds_log.txt)

### System Configuration

CPU: Intel i7
GPU/Driver: Nvidia 1660 super
RAM: 16 GB
OS: Windows

**Comment by OpenSauce04** [comment]
Please upload the log file. You appear to have only uploaded the first few lines, which are not helpful.

Additionally, please ensure to upload it as a file, and not just copy paste the contents into the issue message.

**Comment by reallitup2** [comment]
> Please upload the log file. You appear to have only uploaded the first few lines, which are not helpful.
> 
> Additionally, please ensure to upload it as a file, and not just copy paste the contents into the issue message.

[lime3ds_log.txt](https://github.com/user-attachments/files/15518976/lime3ds_log.txt)


right. I don't know why I chose to copy & paste. This should work.

Edit: Put it in the post.

**Comment by PicoleGamer6969** [comment]
Hey man, I had the same issue playing in my phone, I had to download the PabloMK7 version of Citra to fix it, it runs an bit slower but it didn't crash. Btw in my case the problem wasn't just only when I touched the Monolith, the entire dungeon was almost unplayable, It would crash almost everytime I enter an new area or after an battle

**Comment by OpenSauce04** [comment]
Can one of you please test [this](https://github.com/Lime3DS/Lime3DS/actions/runs/10285054763) build and see if the issue is fixed?

**Comment by PicoleGamer6969** [comment]
Playing on android, It worked, the game hasn't crashed in any of the situations I described, I didn't tested it in the last areas, but I believe it's fixed. Ty
