### ISSUE TITLE
Linux Build instructions

### ISSUE THREAD

**Issue by username227** [Lime3DS/Lime-3DS-Emulator#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Arch package - if you provide detailed build instructions for linux I can attempt to create an arch package and publish to the AUR. Since it's a fork of citra, I attempted to follow citra's build instructions but was not successful. If you are able to update the readme, I could try to start working on this.

### Why would this feature be useful?

It would provide a package for arch-based linux distributions which would hopefully also get your program more publicized.

**Comment by BlurrySquire** [comment]
Once we have an arch build working and/or arch build instructions I will work towards adding them to the [GitHub page](https://lime3ds.github.io/). Also, one of the devs will get back to you tomorrow hopefully since most of the devs are signing off for today. We have done lots of work today.

**Comment by ayrudev** [comment]
we have the [Linux Build](https://lime3ds.github.io/pages/building/linux.html) steps on our website now @username227

**Comment by username227** [comment]
thanks @Polarzincomfrio i was able to build and install. I will begin working on a pkgbuild hopefully next week if nobody beats me to it.

**Comment by ayrudev** [comment]
sure, thanks for ur commitment on helping out our project!

**Comment by username227** [comment]
FYI, I just published an AUR git package which should update automatically with each commit. An appimage AUR package was already created by someone else. My package is here:  https://aur.archlinux.org/packages/lime3ds-git.

If anybody notices any issues please don't hesitate to reach out, I am not truly a developer. Thanks for your work on this project.

**Comment by username227** [comment]
Funny, just got banned from the discord server, supposedly for posting spam links. I don't have an explanation for that, because I have done absolutely nothing of the sort, and especially after what i've done for you guys with the arch packaging. discord username is plentyboot4220. I tried to reach out on discord directly but didn't find any way to do so. If I could at least have some sort of explanation, i'd appreciate it.

**Comment by username227** [comment]
FYI just added authy authenticator to my discord account for extra layer of protection in case i was hacked. If you guys are able and willing to unban me i'd appreciate it.

**Comment by ayrudev** [comment]
deleted the comments since the situation was solved and it's not within the topic :D
