### ISSUE TITLE
 IN GENERAL - Microphone Issues

### ISSUE THREAD

**Issue by agabeluga** [Lime3DS/Lime-3DS-Emulator#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2114.1

### Description of Issue

When I blow into my microphone, the game doesn't register it. I have set my microphone device in the settings. Yes, I checked, my microphone is working correctly outside of the game.

### Expected Behavior

It should register the blowing.

### Reproduction Steps

1. Go to World 3 of Minigame Land or whatever it's called
2. Enter the first minigame
3. Try to blow to start the game
4. Fail

### Log File

https://pastebin.com/05vZeUMF

### System Configuration

CPU: AMD Ryzen 7 5700X 8-Core
GPU/Driver: NVIDIA GeForce RTX 4070
RAM: 32 GB
OS: Windows 11

**Comment by YGOmod** [comment]
I was playing Balloons Buster game and I haven't noticed any problems.. I'm on Android btw 👍🏻

**Comment by BlurrySquire** [comment]
Are you able to recreate this bug in other games? Have you tried using a different audio backend? On the Windows build of Lime3DS I can choose between Cubeb and OpenAL. I just checked and I have the option on the mobile build as well.

Does the game(s) that you encountered the bug in work when you set the audio input to static noise?

You can set the microphone input in the audio settings.

**Comment by agabeluga** [comment]
1. Yes. It doesn't worki in other titles, such as: "Wario Ware Gold". I did try using a different backend.
 2. No, they don't work.
 3. I know. Tried it, nothing worked
