### ISSUE TITLE
Fire Emblem Fates: Special Edition Ganglari Texture crashing the game

### ISSUE THREAD

**Issue by ZeroInt01** [Lime3DS/Lime-3DS-Emulator#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3DS 2114.1

### Description of Issue

Whenever you play through Fire Emblem Fates, you cannot progress past Chapter 2. That is when the Ganglari sword is acquired, and the emulator cannot render the sword or texture. This doesn't happen on previous Citra builds before Lime3DS was created nor does it not occur on Lime3DS 2106. 
This also happens no matter what renderer you use (Vulkan, OpenGL or Software).

### Expected Behavior

Whenever battling or a cutscene happens, sword should render properly without the game crashing.

### Reproduction Steps

1. Start Fire Emblem Fates
2. Progress to Chapter 2 "Gift of Ganglari"
3. Watching the cutscene for Chapter 2 will crash the game, Skipping the cutscene but getting into a battle will also crash the game. Turning off all animations and clearing the chapter and watching subsequent cutscene will also crash the game.

### Log File

[lime3ds_log.txt](https://github.com/user-attachments/files/15541437/lime3ds_log.txt)

### System Configuration

CPU: i9-13900k
GPU/Driver: RTX 3080
RAM: 32 GB
OS: Windows 10 Pro

**Comment by stormakill** [comment]
Hi, I have exactly the same problem. Sombedoy told me to try this emulator : 
https://github.com/PabloMK7/citra

Edit : it still doesnt't work, i guess it's just a problem with emulating this specific game :(

**Comment by Diabolo48** [comment]
Same problem here. At a loss as to what to do...
It seems to not happen to me on Software, but the game runs at like 3 FPS on this, so it's impossible.
Awakening is perfectly fine in comparison.

**Comment by svetlyo** [comment]
Same here.

System Configuration

CPU: Apple M3 Max
GPU/Driver: Apple M3 Max (Vulkan)
RAM: 36 GB
OS: macOS Sonoma 14.5

The crash also does not happen on the latest Citra from https://github.com/PabloMK7/citra/releases/tag/r518f723

**Comment by svetlyo** [comment]
If it is of any help, I've bisected it and this is the diff that fixed the crash:

https://github.com/PabloMK7/citra/compare/rde1f082...r4f174f1

I bet this is the actual fix:  https://github.com/PabloMK7/citra/commit/4f174f1c0b81266170aa8dac226be1b772f4c94d

**Comment by OpenSauce04** [comment]
> If it is of any help, I've bisected it and this is the diff that fixed the crash

Thank you for your investigation. I will pull in this code in time for the 2117 update. I will verify with you that it addresses the crash before it makes its way to the master branch.

**Comment by OpenSauce04** [comment]
Someone here please download and try the build [here](https://github.com/Lime3DS/Lime3DS/actions/runs/10273610447?pr=339) and leave a comment verifying if the issue is resolved.

**Comment by svetlyo** [comment]
> Someone here please download and try the build [here](https://github.com/Lime3DS/Lime3DS/actions/runs/10273610447?pr=339) and leave a comment verifying if the issue is resolved.

It is fixed!
