### ISSUE TITLE
can add a option : build all shader before game start

### ISSUE THREAD

**Issue by weisimin** [Lime3DS/Lime-3DS-Emulator#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

can add a option : build all shader before game start

### Why would this feature be useful?

can speed up the emulator ,and less speed down

**Comment by YGOmod** [comment]
I wonder how you think to do that? shaders are generated when you play games, they are not inside the game.. if it was possible, they would already do that

**Comment by OpenSauce04** [comment]
This is impossible
