### ISSUE TITLE
Keeps closing

### ISSUE THREAD

**Issue by SV911-git** [Lime3DS/Lime-3DS-Emulator#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2114.1

### Description of Issue

The emulator keeps closing when i try to open it.
I don't know if it's my coputer or the emulator.
It keeps hapening all the time.
I want to use the lime emulator because my citra emulator won't work anymore, and now this keeps crashing too.
I'll put a video here

https://github.com/Lime3DS/Lime3DS/assets/171863668/6ee68d5b-6680-41e9-ad1f-b995a977689d

### Expected Behavior

I did not work the first time and i don't know how to fix this.

### Reproduction Steps

I'm not able to open the emulator and i don't know if it's my computer's fault or not.

### Log File

sorry i couldn't find the file

### System Configuration

CPU:AMD Ryzen 3 5425U with Radeon Graphics
GPU/Driver: 
RAM:8,00 GB (7,31 used)
OS: Windows 11

**Comment by OpenSauce04** [comment]
A log file is required to get help with your issue. You can find it in Citra's data folder

**Comment by OpenSauce04** [comment]
Closing this due to lack of response from the author
