### ISSUE TITLE
change lime 3ds working folder

### ISSUE THREAD

**Issue by darkuser89** [Lime3DS/Lime-3DS-Emulator#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Currently lime3ds uses the old Citra folder.
~/Library/Application Support/Citra

It would be better if lime3ds created its own folder and no longer used the old citra folders.
~/Library/Application Support/Lime3DS

Rename the Gui App to make it look better lime3ds-gui to Lime3DS

### Why would this feature be useful?

you can use old and new versions on one without crashes because of the cache

**Comment by OpenSauce04** [comment]
This behaviour is intended to maintain backwards compatibility with Citra. If you wish to make a different working folder, you can change it manually
