### ISSUE TITLE
Migrate to a new data directory on desktop platforms

### ISSUE THREAD

**Issue by OpenSauce04** [Lime3DS/Lime-3DS-Emulator#239]
### Issue

Currently, the old Citra data directory is used. This was done to make the onboarding process for users moving from Citra as effortless as possible in the early stages of the project.

Now that it has been a while since the split off from Citra and other forks have emerged such as Citra Enhanced and PabloMK7's fork, now is the time for a migration to a Lime3DS-specific user directory.

It is a requirement of this move to a new directory that a migration popup is implemented to allow users to easily migrate data from the Citra data directory to Lime3DS's new directory. This popup's functionality should also be available as a menu option so that users can migrate later if they don't choose to initially.

**Comment by rtiangha** [comment]
Changing the dir is pretty easy; feel free to cherry-pick this commit; I was going to submit a PR for a previous issue, but then I noticed it got closed before I could submit it:
https://github.com/rtiangha/Lime3DS/commit/59b16537d0368495ca442890ce3656e0419bb696

The popup is something someone else will have to do.
