### ISSUE TITLE
TEXTURE BUG ~ Mario Party Star Rush

### ISSUE THREAD

**Issue by HatInLime** [Lime3DS/Lime-3DS-Emulator#240]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Lime 3DS 2114.1

### Description of Issue

Whilst playing the King Bob-Omb boss fight, the floor texture appears to glitch out and go entirely transparent in some areas.

https://github.com/Lime3DS/Lime3DS/assets/102345177/f3d8bf81-46d1-4a47-93ad-44df021cda0a

### Expected Behavior

It is expected that the texture is not transparent. Here is a link to a YouTube video displaying how the texture should look;

https://www.youtube.com/watch?v=t_q36-CJSSY

### Reproduction Steps

I am running the US release of Mario Party Star Rush. Just loading into the boss fight will reproduce the bug. It is very consistent, so reproducing the bug should be of no issue. The preview I uploaded up above should simplify the process by selecting the boss from the Minigame selection.

### Log File

[   0.089153] Input <Info> input_common/udp/client.cpp:StartCommunication:206: Starting communication with UDP input server on 127.0.0.1:26760
[   0.145365] Input <Error> input_common/gcadapter/gc_adapter.cpp:CheckDeviceAccess:243: libusb_control_transfer failed with error= -9
[   0.145444] Input <Info> input_common/gcadapter/gc_adapter.cpp:Setup:228: GC adapter is now connected
[   0.349525] Frontend <Info> lime_qt/main.cpp:GMainWindow:222: Lime3DS Version: 2114.1 | HEAD-ab99fff
[   0.349538] Frontend <Info> lime_qt/main.cpp:GMainWindow:237: Host CPU: 13th Gen Intel(R) Core(TM) i5-13600KF | AVX2 | FMA
[   0.349636] Frontend <Info> lime_qt/main.cpp:GMainWindow:239: Host OS: Windows 11 Version 23H2 (Build 22631.3593)
[   0.349644] Frontend <Info> lime_qt/main.cpp:GMainWindow:242: Host RAM: 15.82 GiB
[   0.349645] Frontend <Info> lime_qt/main.cpp:GMainWindow:243: Host Swap: 10.50 GiB
[   0.502881] Frontend <Warning> lime_qt/main.cpp:CheckForUpdates:1030: Unable to start check for updates
[  10.917067] Frontend <Info> lime_qt/main.cpp:BootGame:1276: Lime3DS starting...
[  10.917163] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[  10.917169] Frontend <Info> lime_qt/main.cpp:BootGame:1299: Loading per game config file for title 000400000019BD00
[  10.919857] Config <Info> common/settings.cpp:LogSettings:83: Lime3DS Configuration:
[  10.919861] Config <Info> common/settings.cpp:operator():80: Core_UseCpuJit: true
[  10.919862] Config <Info> common/settings.cpp:operator():80: Core_CPUClockPercentage: 100
[  10.919862] Config <Info> common/settings.cpp:operator():80: Renderer_UseGLES: false
[  10.919863] Config <Info> common/settings.cpp:operator():80: Renderer_GraphicsAPI: OpenGL
[  10.919863] Config <Info> common/settings.cpp:operator():80: Renderer_AsyncShaders: false
[  10.919863] Config <Info> common/settings.cpp:operator():80: Renderer_AsyncPresentation: true
[  10.919863] Config <Info> common/settings.cpp:operator():80: Renderer_SpirvShaderGen: true
[  10.919864] Config <Info> common/settings.cpp:operator():80: Renderer_Debug: false
[  10.919864] Config <Info> common/settings.cpp:operator():80: Renderer_UseHwShader: true
[  10.919864] Config <Info> common/settings.cpp:operator():80: Renderer_ShadersAccurateMul: true
[  10.919864] Config <Info> common/settings.cpp:operator():80: Renderer_UseShaderJit: false
[  10.919865] Config <Info> common/settings.cpp:operator():80: Renderer_UseResolutionFactor: 3
[  10.919865] Config <Info> common/settings.cpp:operator():80: Renderer_FrameLimit: 95
[  10.919865] Config <Info> common/settings.cpp:operator():80: Renderer_VSyncNew: false
[  10.919865] Config <Info> common/settings.cpp:operator():80: Renderer_PostProcessingShader: none (builtin)
[  10.919866] Config <Info> common/settings.cpp:operator():80: Renderer_FilterMode: true
[  10.919866] Config <Info> common/settings.cpp:operator():80: Renderer_TextureFilter: None
[  10.919866] Config <Info> common/settings.cpp:operator():80: Renderer_TextureSampling: GameControlled
[  10.919868] Config <Info> common/settings.cpp:operator():80: Stereoscopy_Render3d: 0
[  10.919868] Config <Info> common/settings.cpp:operator():80: Stereoscopy_Factor3d: 0
[  10.919869] Config <Info> common/settings.cpp:operator():80: Stereoscopy_MonoRenderOption: 0
[  10.919870] Config <Info> common/settings.cpp:operator():80: Layout_LayoutOption: 4
[  10.919870] Config <Info> common/settings.cpp:operator():80: Layout_SwapScreen: false
[  10.919870] Config <Info> common/settings.cpp:operator():80: Layout_UprightScreen: false
[  10.919877] Config <Info> common/settings.cpp:operator():80: Layout_LargeScreenProportion: 4
[  10.919878] Config <Info> common/settings.cpp:operator():80: Utility_DumpTextures: false
[  10.919878] Config <Info> common/settings.cpp:operator():80: Utility_CustomTextures: false
[  10.919878] Config <Info> common/settings.cpp:operator():80: Utility_PreloadTextures: false
[  10.919878] Config <Info> common/settings.cpp:operator():80: Utility_AsyncCustomLoading: true
[  10.919879] Config <Info> common/settings.cpp:operator():80: Utility_UseDiskShaderCache: true
[  10.919879] Config <Info> common/settings.cpp:operator():80: Audio_Emulation: HLE
[  10.919879] Config <Info> common/settings.cpp:operator():80: Audio_OutputType: 0
[  10.919880] Config <Info> common/settings.cpp:operator():80: Audio_OutputDevice: auto
[  10.919881] Config <Info> common/settings.cpp:operator():80: Audio_InputType: 0
[  10.919881] Config <Info> common/settings.cpp:operator():80: Audio_InputDevice: auto
[  10.919881] Config <Info> common/settings.cpp:operator():80: Audio_EnableAudioStretching: true
[  10.919882] Config <Info> common/settings.cpp:operator():80: Audio_EnableRealtime: false
[  10.919882] Config <Info> common/settings.cpp:operator():80: Camera_OuterRightName: blank
[  10.919882] Config <Info> common/settings.cpp:operator():80: Camera_OuterRightConfig: 
[  10.919882] Config <Info> common/settings.cpp:operator():80: Camera_OuterRightFlip: 0
[  10.919882] Config <Info> common/settings.cpp:operator():80: Camera_InnerName: blank
[  10.919883] Config <Info> common/settings.cpp:operator():80: Camera_InnerConfig: 
[  10.919883] Config <Info> common/settings.cpp:operator():80: Camera_InnerFlip: 0
[  10.919883] Config <Info> common/settings.cpp:operator():80: Camera_OuterLeftName: blank
[  10.919883] Config <Info> common/settings.cpp:operator():80: Camera_OuterLeftConfig: 
[  10.919884] Config <Info> common/settings.cpp:operator():80: Camera_OuterLeftFlip: 0
[  10.919884] Config <Info> common/settings.cpp:operator():80: DataStorage_UseVirtualSd: true
[  10.919885] Config <Info> common/settings.cpp:operator():80: DataStorage_UseCustomStorage: true
[  10.919886] Config <Info> common/settings.cpp:operator():80: DataStorage_SdmcDir: C:/Users/madel/OneDrive/Desktop/3DS/sdmc/
[  10.919889] Config <Info> common/settings.cpp:operator():80: DataStorage_NandDir: C:/Users/madel/OneDrive/Desktop/3DS/nand/
[  10.919889] Config <Info> common/settings.cpp:operator():80: System_IsNew3ds: true
[  10.919889] Config <Info> common/settings.cpp:operator():80: System_LLEApplets: false
[  10.919889] Config <Info> common/settings.cpp:operator():80: System_RegionValue: -1
[  10.919890] Config <Info> common/settings.cpp:operator():80: System_PluginLoader: false
[  10.919890] Config <Info> common/settings.cpp:operator():80: System_PluginLoaderAllowed: true
[  10.919890] Config <Info> common/settings.cpp:operator():80: Debugging_DelayStartForLLEModules: true
[  10.919890] Config <Info> common/settings.cpp:operator():80: Debugging_UseGdbstub: false
[  10.919891] Config <Info> common/settings.cpp:operator():80: Debugging_GdbstubPort: 24689
[  11.083525] Audio.DSP <Info> audio_core/hle/aac_decoder.cpp:AACDecoder:27: Created FAAD2 AAC decoder.
[  11.095367] Audio.Sink <Info> audio_core/cubeb_sink.cpp:StateCallback:135: Cubeb Audio Stream Started
[  11.095378] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:14: Starting RPC server.
[  11.095489] RPC_Server <Info> core/rpc/rpc_server.cpp:HandleRequestsLoop:104: Request handler started.
[  11.128251] Service.HTTP <Error> core/hle/service/http/http_c.cpp:DecryptClCertA:1984: NormalKey in KeySlot 0x0D missing
[  11.128310] Render.OpenGL <Info> video_core/renderer_opengl/gl_driver.cpp:ReportDriverInfo:133: GL_VERSION: 4.3.0 NVIDIA 531.68
[  11.128312] Render.OpenGL <Info> video_core/renderer_opengl/gl_driver.cpp:ReportDriverInfo:134: GL_VENDOR: NVIDIA Corporation
[  11.128313] Render.OpenGL <Info> video_core/renderer_opengl/gl_driver.cpp:ReportDriverInfo:135: GL_RENDERER: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2
[  11.147302] Loader <Info> core/loader/ncch.cpp:Load:270: Program ID: 000400000019BD00
[  11.147369] Service.FS <Warning> core/file_sys/ncch_container.cpp:OpenFile:126: Failed to open C:/Users/madel/OneDrive/Desktop/3DS/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/0019bd00/content/00000000.app
[  11.170996] Loader <Info> core/hle/kernel/process.cpp:ParseKernelCaps:196: ExHeader kernel version: 2.50
[  11.182091] Service.CAM <Info> lime_qt/camera/qt_multimedia_camera.cpp:ResumeCameras:50: Resuming all cameras
[  11.209577] Render.OpenGL <Info> video_core/renderer_opengl/gl_shader_disk_cache.cpp:LoadTransferable:175: Found a transferable disk cache with 1227 entries
[  11.244330] Render.OpenGL <Info> video_core/renderer_opengl/gl_shader_disk_cache.cpp:LoadPrecompiledFile:282: Found a precompiled disk cache with 1227 decompiled entries and 1227 binary entries
[  12.079422] Service.SRV <Warning> core/hle/service/sm/srv.cpp:RegisterClient:63: (STUBBED) called. Caller PID=11
[  12.130814] Service.SRV <Warning> core/hle/service/sm/srv.cpp:EnableNotification:85: (STUBBED) called
[  12.133866] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:OverrideDefaultDaemons:186: (STUBBED) bit_mask=0x0000000F
[  12.133923] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:SuspendDaemons:74: (STUBBED) bit_mask=0x00000006
[  12.134579] Service.APT <Warning> core/hle/service/apt/apt.cpp:SetAppCpuTimeLimit:710: (STUBBED) called, must_be_one=1, value=30
[  12.135444] Service.APT <Warning> core/hle/service/apt/apt.cpp:NotifyToWait:338: (STUBBED) app_id=768
[  12.136516] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:689: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001
[  12.136656] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:689: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[  12.136979] Service.FS <Warning> core/hle/service/fs/fs_user.cpp:InitializeWithSdkVersion:1062: (STUBBED) called, version: 0x0B0400C8
[  12.179530] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:209: Delay generator was not initalized. Using default
[  12.184104] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:209: Delay generator was not initalized. Using default
[  12.251469] Service.CFG <Info> core/hle/service/cfg/cfg.cpp:UpdatePreferredRegionCode:674: Preferred region code set to 1
[  12.262138] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:209: Delay generator was not initalized. Using default
[  12.836708] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:468: Firmware hash: 0xdcdb8c683bf28fdd
[  12.836712] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:472: Structures hash: 0x228655de1258d999
[  12.836713] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:LoadComponent:192: called size=0xC25C, prog_mask=0x00FF, data_mask=0x00FF
[  12.837122] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:RegisterInterruptEvents:259: Registered interrupt=2, channel=2, event=event-00135f38
[  12.837223] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:GetSemaphoreEventHandle:275: (STUBBED) called
[  12.837322] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphoreMask:285: (STUBBED) called mask=0x2000
[  12.837469] Audio.DSP <Info> audio_core/hle/hle.cpp:PipeWrite:227: Application has requested initialization of DSP hardware
[  12.837538] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
[  12.838154] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
[  13.213182] Service.LDR <Warning> core/hle/service/ldr_ro/ldr_ro.cpp:LoadCRR:155: (STUBBED) called, crr_buffer_ptr=0x0844C000, crr_size=0x00005000
[  13.232967] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:689: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[  13.282625] Service.LDR <Info> core/hle/service/ldr_ro/cro_helper.cpp:ApplyStaticAnonymousSymbolToCRS:555: CRO "mod_boot" exports 0 static anonymous symbols
[  13.282734] Service.LDR <Info> core/hle/service/ldr_ro/ldr_ro.cpp:LoadCRO:331: CRO "mod_boot" loaded at 0x00924000, fixed_end=0x00928000
[  13.732266] Service.FS <Warning> core/file_sys/archive_other_savedata.cpp:Open:74: (stubbed) Unimplemented media type GameCard
[  13.732279] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenArchive:677: failed to get a handle for archive archive_id=0x567890B4 archive_path=[Binary: 020000005f1a000000ff4300]
[  13.732396] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenArchive:677: failed to get a handle for archive archive_id=0x567890B4 archive_path=[Binary: 010000005f1a000000ff4300]
[  13.794149] Service.FS <Warning> ./core/file_sys/archive_backend.h:Control:201: (STUBBED) called, archive=SaveDataArchive: C:/Users/madel/OneDrive/Desktop/3DS/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/0019bd00/data/00000001/, action=00000000, input_size=00000001, output_size=00000001
[  13.794498] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:209: Delay generator was not initalized. Using default
[  13.794786] Service.FS <Warning> ./core/file_sys/archive_backend.h:Control:201: (STUBBED) called, archive=SaveDataArchive: C:/Users/madel/OneDrive/Desktop/3DS/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/0019bd00/data/00000001/, action=00000000, input_size=00000001, output_size=00000001
[  16.045950] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:76: Non-existing file C:/Users/madel/OneDrive/Desktop/3DS/nand/data/00000000000000000000000000000000/sysdata/00010034/00000000/BOSS_SV.db can't be open without mode create.
[  16.045978] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:76: Non-existing file C:/Users/madel/OneDrive/Desktop/3DS/nand/data/00000000000000000000000000000000/sysdata/00010034/00000000/BOSS_SS.db can't be open without mode create.
[  16.045980] Service.BOSS <Error> core/hle/service/boss/online_service.cpp:InitializeSession:104: Could not open BOSS database.
[  16.046145] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:ResumeDaemons:89: (STUBBED) bit_mask=0x00000002
[  16.188481] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:GetStorageInfo:105: (STUBBED) called
[  16.188887] Service.BOSS <Warning> core/hle/service/boss/online_service.cpp:UnregisterTask:171: TaskId 'preport ' not in list
[  16.327624] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:209: Delay generator was not initalized. Using default
[  16.328338] Service.FS <Warning> ./core/file_sys/archive_backend.h:Control:201: (STUBBED) called, archive=SaveDataArchive: C:/Users/madel/OneDrive/Desktop/3DS/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/0019bd00/data/00000001/, action=00000000, input_size=00000001, output_size=00000001
[  17.101819] Service.LDR <Info> core/hle/service/ldr_ro/ldr_ro.cpp:UnloadCRO:369: Unloading CRO "mod_boot"
[  17.277843] Service.LDR <Info> core/hle/service/ldr_ro/cro_helper.cpp:ApplyStaticAnonymousSymbolToCRS:555: CRO "mod_menu2" exports 0 static anonymous symbols
[  17.281286] Service.LDR <Info> core/hle/service/ldr_ro/ldr_ro.cpp:LoadCRO:331: CRO "mod_menu2" loaded at 0x00924000, fixed_end=0x0098B000
[  20.446700] Service.FS <Warning> core/hle/service/fs/file.cpp:OpenLinkFile:376: (STUBBED) File command OpenLinkFile Path: [Binary: 000000000000000000000000]
[  59.791378] Service.LDR <Info> core/hle/service/ldr_ro/ldr_ro.cpp:UnloadCRO:369: Unloading CRO "mod_menu2"
[  59.897490] Service.LDR <Info> core/hle/service/ldr_ro/cro_helper.cpp:ApplyStaticAnonymousSymbolToCRS:555: CRO "mod_mgn702" exports 0 static anonymous symbols
[  59.898771] Service.LDR <Info> core/hle/service/ldr_ro/ldr_ro.cpp:LoadCRO:331: CRO "mod_mgn702" loaded at 0x00924000, fixed_end=0x00952000
[  78.057438] RPC_Server <Info> core/rpc/server.cpp:NewRequestCallback:36: Received end packet
[  78.057621] Audio.DSP <Info> audio_core/hle/aac_decoder.cpp:~AACDecoder:35: Destroyed FAAD2 AAC decoder.
[  78.057869] Audio.Sink <Info> audio_core/cubeb_sink.cpp:StateCallback:138: Cubeb Audio Stream Stopped
[  78.070191] Kernel <Info> core/hle/kernel/process.cpp:~Process:634: Cleaning up process 11
[  78.070191] Kernel <Info> core/hle/kernel/process.cpp:~Process:634: Cleaning up process 11

### System Configuration

CPU: 13th Gen Intel(R) Core(TM) i5-13600KF  5GHz average
GPU/Driver: NVIDIA GeForce RTX 3070 Ti
RAM: 16GB
OS: Windows

**Comment by YGOmod** [comment]
wanna add, same bug exists in Mega Monty Mole's in the Hole stage

**Comment by HatInLime** [comment]
Update: Glitch also occurs during the Piranha Plantemonium minigame.
(and I'm going to second what YGOmod said, it also occurs in Monty Mole's boss fight)

**Comment by YGOmod** [comment]
I haven't notice it in Petey Piranha's game 🤔 but I found another one in Bowser Jr.'s Pound game

![Screenshot_20240611_005644_Lime3DS](https://github.com/Lime3DS/Lime3DS/assets/130164085/cb6f1184-d7d8-4c3b-977a-97242b36e2f1)

**Comment by HatInLime** [comment]
Just to do away with any potential confusion, by 'Piranha Plantemonium' I was referring to the minigame 'Piranha Plantemonium', not Petey Piranha's boss fight. Here's a screenshot to show what I mean. :)

![ඞ](https://github.com/Lime3DS/Lime3DS/assets/102345177/73a7a7d9-d1b7-4563-9bee-1f27a2077903)
