### ISSUE TITLE
Touch Screen Calibration slightly off

### ISSUE THREAD

**Issue by Yorisoft** [Lime3DS/Lime-3DS-Emulator#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3DS 2114.1

### Description of Issue

When clicking button on the bottom touch screen I have to click on the upper portion of the buttons always. The lower half of the buttons do not register as being pressed, as if tho the touch screen isnt calibrated correctly. 

### Expected Behavior

Button press when clicking it on second screen 

### Reproduction Steps

not sure. Im playing pokemon X

### Log File

where is it? 

### System Configuration

CPU: i5-9600k
GPU/Driver: 1660 
RAM: 32 GB
OS: Windows 11

**Comment by BlurrySquire** [comment]
I've had a very similar issue with citra in the past. I recall fixing it but I'm not sure how. Maybe try looking at the Citra forums on the wayback machine?
