### ISSUE TITLE
Cannot map the joystick of a real gamepad, whether switching to XBOX mode or Android HID mode. I can map with citra

### ISSUE THREAD

**Issue by ljam2000** [Lime3DS/Lime-3DS-Emulator#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2114.1

### Description of Issue

Cannot map the joystick of a real gamepad, whether switching to XBOX mode or Android HID mode. I can map with citra

### Expected Behavior

nothing

### Reproduction Steps

 nothing

### Log File

 nothing

### System Configuration

 
nothing

**Comment by OpenSauce04** [comment]
Please fill out the form properly if you want help
