### ISSUE TITLE
Secondary Screen Support

### ISSUE THREAD

**Issue by DroidlyMobile** [Lime3DS/Lime-3DS-Emulator#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The feature I'm requesting allows for a second display to be added on Android just like Drastic DS emulation I know how to implement this in Android myself but I'm not sure how the screens render to the surfaceview if this could be shared I could add this feature.

### Why would this feature be useful?

True DUAL SCREEN that is why this would be useful!

**Comment by BlurrySquire** [comment]
I'm not sure myself, we would have to do some digging as to how it is rendered. If you wanted to, you could do some digging at the android code to see how it renders.

**Comment by DroidlyMobile** [comment]
I have dug into it a bit and I know where the surfaces render but not sure how each display (top/bottom) renders.  I even went back to old builds of the Citra source code I'll keep digging.

**Comment by VictrB** [comment]
LG V50(S) & V60 Dual Screen (& Surface Duo 1/2?) support are key examples of where this would be useful

**Comment by OpenSauce04** [comment]
Duplicate of #351
