### ISSUE TITLE
No audio in red viper 

### ISSUE THREAD

**Issue by Riot20058** [Lime3DS/Lime-3DS-Emulator#248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3DS 2114.1

### Description of Issue

Problem no DSP firmware basic homebrew get audio without it red viper any sound test it on see audio work batter native android vitural Boy emulator 

### Expected Behavior

Should sound in app if place thing right folder

### Reproduction Steps

1. Install red viper by CIA

2. Open file error look this
![Screenshot_20240618_235835_Lime3DS](https://github.com/Lime3DS/Lime3DS/assets/128275823/315da3ce-245b-4137-a7ed-d30f2740f6df)

3. Proof game do work before say red viper not run 

![Screenshot_20240618_235909_Lime3DS](https://github.com/Lime3DS/Lime3DS/assets/128275823/d39a473d-f25d-4563-b46e-97497e749bf2)

### Log File

User error ask how one get dsp framware file on lime3ds that bug in question 

### System Configuration

CPU: snapdragon 8 gen 2
GPU/Driver: stock
RAM: 8gb ram
OS: android 14

**Comment by OpenSauce04** [comment]
Given the lack of information in this issue, I can only assume that the error is to be believed and you didn't dump the required firmware to use the emulator.
