### ISSUE TITLE
Could not be located in the dynamic link library

### ISSUE THREAD

**Issue by MoonlightCoffee** [Lime3DS/Lime-3DS-Emulator#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Every build atempted

### Description of Issue

After download, when trying to launch a error displays saying "The procedure entry point CreateDXGIFactory2 could not be located in the dynamic link library dxgi.dll."

### Expected Behavior

It is expected to open a menu which you insert a file a run a game

### Reproduction Steps

Windows 7, download and extract the zip file. Then attempt to open the emulator. 

### Log File

Idk what a log file is, sorry

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by OpenSauce04** [comment]
Lime3DS does not support Windows 7. Please upgrade to Windows 10 or later if you intend to use the emulator. You should probably be doing so anyway as Windows 7 has been out of support for over 4 years
