### ISSUE TITLE
Lime simply doesn't start.

### ISSUE THREAD

**Issue by mildfever** [Lime3DS/Lime-3DS-Emulator#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2115

### Description of Issue

Whenever i run lime3ds-gui.exe nothing happens, no new window, nothing at all.
First time using Lime, so no experience of previous vers.
I do have the latest Citra (Nightly 2104) and that works fine.

### Expected Behavior

.

### Reproduction Steps

.

### Log File

.

### System Configuration

CPU: i3 12100F
GPU/Driver: RTX3060
RAM: 32Gb
OS: Win 10

**Comment by OpenSauce04** [comment]
Please fill out the issue form properly
