### ISSUE TITLE
Link for "Lime3DS is missing keys to download system files." links to the defunct Citra Website

### ISSUE THREAD

**Issue by vawgahan** [Lime3DS/Lime-3DS-Emulator#262]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Lime3DS 2115

### Description of Issue

When you go into Emulation > Configure > System and you do not have the keys mentioned when you click on the hyperlink ("How to get keys?") under "Lime3DS is missing keys to download system files.", it sends you to a link (https://citra-emu.org/wiki/aes-keys/) at the now defunct Citra website. I apologize if this issue has already been addressed somewhere other than the issues here or something

### Expected Behavior

The link would lead to a newly made, up and running website or just provide the information in some way

### Reproduction Steps

Go into Emulation > Configure > System
Press the hyperlink titled "How to get keys?" under "Lime3DS is missing keys to download system files." to open the defunct Citra link in your browser

### Log File

[lime3ds_log.txt](https://github.com/user-attachments/files/16058983/lime3ds_log.txt)

### System Configuration

CPU: AMD Ryzen 5 7600X
GPU/Driver: Gigabyte GAMING OC Radeon RX 6750 XT
RAM: 32 GB
OS: Windows 11

**Comment by OpenSauce04** [comment]
This has been fixed for 2116
