### ISSUE TITLE
An option to use the hotkeys with a controller

### ISSUE THREAD

**Issue by salamandercc37** [Lime3DS/Lime-3DS-Emulator#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I want to be able to swap screens and close the game with a controller (for windows)

### Why would this feature be useful?

 it would be great to be able to swap screens directly on the controller and not on the computer keyboard

**Comment by Ploggy** [comment]
Yes please, this would be very handy feature to have.. especially for Swap Screens and Fullscreen Toggle.

**Comment by OpenSauce04** [comment]
Sounds fine to me

**Comment by OpenSauce04** [comment]
Duplicate of #119
