### ISSUE TITLE
Remove Option to View Game on GameDB or Port to Another Address

### ISSUE THREAD

**Issue by zcraftelite9495** [Lime3DS/Lime-3DS-Emulator#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

 Due to the Citra servers that the "Navigate to GameDB Entry" being down, you should either:

A) Remove the "Navigate to GameDB Entry" option from the right click context menu entirely.

B) Rework the "Navigate to GameDB Entry" option to redirect to the public archive of the Citra website (citra-emulator.com)

C) Create an Lime3DS Mirror to host that data (this would be the most time-consuming option)

### Why would this feature be useful?

This is just a QoL (Quality of Life) improvement to help clean up the right click context menus inside of Lime.

**Comment by OpenSauce04** [comment]
Thanks for bringing this up. We will likely opt for the first option and simply remove the context menu entry.
