### ISSUE TITLE
Better UI Settings Menu Design for Lime3DS

### ISSUE THREAD

**Issue by zcraftelite9495** [Lime3DS/Lime-3DS-Emulator#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Similar to Issue #226, I suggest that we rework the settings menu design on desktop to a sidebar with Icons, similar to how it is currently displayed on Android. Instead of having the default styled tabs at the top of the settings menu, and the small menu on the left of the menu area, we can completely replace both with a dropdown-styled system with a similar design interface to how windows designed their settings menu in Windows 11, but with dropdowns to select the options that would previously be displayed above the menu area.

### Why would this feature be useful?

Would enable a more user  friendly expirience, and provide an more exciting visual way to browse the settings menu on the desktop versions of Lime3DS.

**Comment by OpenSauce04** [comment]
The changes proposed here seem as though they would impact the UX of the settings menu in a negative way. 

Moving the sidebar to a dropdown menu would make less of the settings navigation visible at once while requiring twice as many clicks to navigate to any other section. Additionally, moving the context-sensitive tabs which are currently at the top of the window to a side menu is simply unintuitive when compared to typical desktop interface design conventions.

For the reasons listed above, I will be closing this issue.
