### ISSUE TITLE
Could someone add support for quest 2 and 3 devices?

### ISSUE THREAD

**Issue by XxUndrscor54xX** [Lime3DS/Lime-3DS-Emulator#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Quest 2 and 3 support so we can use our quests to use the 3d gobbledygook here.

### Why would this feature be useful?

Citravr is dead, so there really is no other option other than these forks.

**Comment by OpenSauce04** [comment]
I would consider this out of scope for the main project as of now.
As we do not plan to support this officially at this time, the best approach would likely be a dedicated fork similar to CitraVR.
