### ISSUE TITLE
[Feature Request] Game file streaming

### ISSUE THREAD

**Issue by pacoa-kdbg** [Lime3DS/Lime-3DS-Emulator#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Similar to what Artic Base (from PabloMK7) does, allow to stream game files from a different configured device and use the rendering capabilities of the current device to play the game .

### Why would this feature be useful?

Avoid copying/syncing/messing with files on multiple devices.

This would be useful on : android setup for on the go (as server) + PC when at home (as client) 

And similar setups with portable PCs/laptops.

**Comment by OpenSauce04** [comment]
The sheer complexity of implementing a feature like this into the emulator itself as opposed to simply using Artic Base makes it just not worth the effort. I would recommend just using your 3DS as a hub for your games and save files

**Comment by pacoa-kdbg** [comment]
@OpenSauce04 
Using the 3DS creates really high loading times
