### ISSUE TITLE
Bring Back the "ARM Dissassembly" view that existed in older versions.

### ISSUE THREAD

**Issue by Andrew900460** [Lime3DS/Lime-3DS-Emulator#274]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What feature are you suggesting?

From doing a bit of googling, I have found various image of old versions of Citra that has a Disassembly view and a Callstack view.
Example: https://gbatemp.net/attachments/019-png.7625/

But all the latest builds I could find of either Lime3DS or Citra do not have these options available in the "debugging" menu.
I have even asked on the discord to see if maybe the feature was just extra hidden, and I've made a post about this in the discords support forum channel, which has had no responce for almost a month.
So assuming this feature had been disabled and forgotton for some reason, I think it would be really helpful if this feature was brought back.

### Why would this feature be useful?

I think this would help a lot with research related projects. Where one may want to look closely at how part of a 3ds game works; seeing what kinds of algorithms are used, learn about tricks that were used to help performance, etc.
Emulators like FCEUX have an assembly view which is very handy for doing such things with NES games.

Currently, right now, I am actually using Cheat Engine with its assembly view to try and do basically this, but because it's showing me native x86/64 assmebly (not the assembly of the 3ds' ARM processor) it represents another layer of seperation from what the actual game code looks like, and makes it harder to analyse and understand what the game is doing. Along with any other "tricks" that might be going on.

_(Though, I have learned that due to being able to use Cheat Engine in this way, this implies that Lime3DS is converting the ARM assembly to native x86, it seems)_

**Comment by OpenSauce04** [comment]
Unfortunately, the code for this feature was removed back in 2017 due to a licensing conflict. This feature relied on code published under the Apache 2.0 license, which is not compatible with GPLv2, the license used by Citra and therefore Lime3DS.
For this reason, it is not possible to reintroduce the feature.
You can read more on this here: https://web.archive.org/web/20201217081037/https://github.com/citra-emu/citra/issues/1280
