### ISSUE TITLE
Advance frame functionality is unintuitive

### ISSUE THREAD

**Issue by OpenSauce04** [Lime3DS/Lime-3DS-Emulator#276]
### Issue

When assigned to a key, attempting to use the Advance Frame hotkey either while the emulator is paused or during any other point in time seems to have no effect

When working as intended, this hotkey should progress emulation by a single frame when emulation is paused

**Comment by OpenSauce04** [comment]
Ah, it appears that I misunderstood how this feature works
It seems that it is intended(?) for this feature to not work while emulation is paused, and instead there is a special "Frame Advance" mode under Tools in the menu bar
This behaviour is not very intuitive. I will investigate why this is the case to determine if it is appropriate to make this behaviour apply the emulator is paused normally

**Comment by TheRealWario** [comment]
Yea, I claimed it as broken because I thought it was like other emulators, where you can use it anytime and resume by pressing pause. Indeed, it is very unintuitive.

**Comment by BlurrySquire** [comment]
We could scrap it but it would limit our ability to debug broken games (I mean games that are broken because of an emulation error). I also think it might be best to modify it to behave like other emulators.

**Comment by OpenSauce04** [comment]
Why would we scrap it? Fixing this isn't hard at all.
