### ISSUE TITLE
Link for "How to get keys?" in the Android App links to the defunct Citra Website

### ISSUE THREAD

**Issue by vawgahan** [Lime3DS/Lime-3DS-Emulator#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2115

### Description of Issue

In the system files section of the Android app, if you click the "How to get keys?" hyperlink it links to the defunct Citra website, specifically https://citra-emu.org/wiki/aes-keys/

### Expected Behavior

The link would lead to a new page that displays the information

### Reproduction Steps

Click "Options" in the bottom panel
Click "System Files"
Click the "How to get keys?" link

### Log File

N/A

### System Configuration

Samsung Galaxy S20 FE

**Comment by OpenSauce04** [comment]
This will be addressed in the next update, thanks for the report
