### ISSUE TITLE
Disney Magical World 

### ISSUE THREAD

**Issue by MasaMike** [Lime3DS/Lime-3DS-Emulator#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2115

### Description of Issue

I played the first few minutes on my red magic 8 pro until it got to a letter scene after which afterwards it had a loading screen then crashed. I tried tweaking the settings multiple times and nothing changed. What should I do?
![IMG_0355](https://github.com/user-attachments/assets/c48b95c9-583b-4c37-91c7-64ae656695d6)
![IMG_0356](https://github.com/user-attachments/assets/0f9d743d-9888-4eef-a118-df8a3abe3649)
![IMG_0357](https://github.com/user-attachments/assets/7527797f-cb97-4e6a-92bd-976e97911e69)

### Expected Behavior

Crashes at the same point right around the start.

### Reproduction Steps

Starting the game and playing through the beginning parts.

### Log File

![IMG_0358](https://github.com/user-attachments/assets/9f43ee90-495e-4d38-a93b-4d6624b45fa3)

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:
Red magic 8 pro(Android Version)

**Comment by OpenSauce04** [comment]
From the log it seems that the game dump is bad. Try redumping or dumping using the CIA format
