### ISSUE TITLE
Add an option to import and export Save Data

### ISSUE THREAD

**Issue by JamesAk475styles345** [Lime3DS/Lime-3DS-Emulator#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I am suggesting this feature to add an option to import and export Save Data to not Start the game all over again from Scratch. Because when I use Save States the game crashes. So it would be useful to add the option I requested for.

### Why would this feature be useful?

This feature would make Lime3ds be even better to not start your game all over again. Save states is not useful in my opinion because when I use Save states the game crashes so Lime3ds needs to have an import and export Save Data option

**Comment by OpenSauce04** [comment]
You can already copy save data just fine? What are you suggesting here.

**Comment by JamesAk475styles345** [comment]
How

**Comment by DinoSour69** [comment]
blatant necrobump but i'm also wondering what the process is for copying save files and am unable to find anything through google any help or direction would be appreciated tysm

**Comment by yamgomes** [comment]
sorry for also necrobumping but if anyone ends up here like I did and is still clueless, in the folder you chose for the system files on first app startup there should be a `sdmc` folder, where the in game save files (NOT the save states) are stored. if you come from Lime3DS (and other Citra forks), you can just copy this folder from the original emulator's system folder to Azahar's and open the game and it should load the in game saves correctly (again, NOT the save states)
