### ISSUE TITLE
Put Key Buttons in Android Version

### ISSUE THREAD

**Issue by RonildoGamer** [Lime3DS/Lime-3DS-Emulator#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

it would be a good suggestion to create the option to create mixed controls like (1= Y+A, 2=Y+B)

### Why would this feature be useful?

an example of a game that would fit this would be Monster Hunter Xx where Y+B your character does a Special Attack, However, this is very difficult on Android Touch, that's all Just a suggestion from me

**Comment by OpenSauce04** [comment]
This issue doesn't describe what you are requesting in enough detail to be understandable. Please open a new issue with a more substantial description of what you are asking for
