### ISSUE TITLE
Distribute Lime3DS via an installer on Windows

### ISSUE THREAD

**Issue by ItachiSan** [Lime3DS/Lime-3DS-Emulator#297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I want to be able to install and update Lime3DS via an installer.

### Why would this feature be useful?

That would make it user friendly to update and possible to update via e.g. winget.

**Comment by ItachiSan** [comment]
Adding here for personal future reference:
https://cmake.org/cmake/help/latest/cpack_gen/innosetup.html

**Comment by OpenSauce04** [comment]
We plan to bring over the old Citra installer if possible, we just haven't gotten around to it yet

**Comment by SilverGreen93** [comment]
I am just curious. Why would you need an installer? A portable version seems more flexible. An internal updater would be good though.

**Comment by OpenSauce04** [comment]
The current version isn't portable. Your emulator data is stored in your local app data or Mac/Linux equivalent

**Comment by ItachiSan** [comment]
> I am just curious. Why would you need an installer? A portable version seems more flexible. An internal updater would be good though.

WinGet has a Lime3DS package but installs it weirdly.
An InnoSetup installer solves the issue having a nice user shortcut.

**Comment by OpenSauce04** [comment]
From discussions which occurred in the development channel on Discord, it has been decided that Lime3DS will only receive an installer on Windows.

**Comment by ItachiSan** [comment]
Hello again, have been silent since I wanted to see how the conversation would evolve. 😀

I think I will create a MR with my work so that you are free to use it in case 😉
