### ISSUE TITLE
Screen Sizing

### ISSUE THREAD

**Issue by sp11111111** [Lime3DS/Lime-3DS-Emulator#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

A feature/option that allows a user to size the screen of the emulator on pc by 1x, 1.5x, 2x, 2.5x, etc..

### Why would this feature be useful?

This feature would be useful because users can choose a screen size that suits their preferences or needs with just a few clicks.

**Comment by OpenSauce04** [comment]
I'm not sure exactly what you're asking for here? If you're talking about the size of the window itself you can simply resize the window as you would with anything else, and if you're talking about internal resolution, this feature already exists.
Could you please clarify?

**Comment by sp11111111** [comment]
I'm talking about the window size. But as I stated above as to why this feature would be because it would be easier for users to resize the windows in just a few clicks. It would also be another option along with the ability to resize by dragging the edge of the window. This feature would also let users have consistent windows sizes across all instances when playing multiplayer.

**Comment by OpenSauce04** [comment]
Adding a setting for something that can be achieved with a single click as a native part of the operating system can't really be justified. Doing so will simply add unnecessary menu clutter.

I will be closing this as not planned.
