### ISSUE TITLE
Updates in Lime Window

### ISSUE THREAD

**Issue by Gabrielcnnunes** [Lime3DS/Lime-3DS-Emulator#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

How about too add an online update to Lime in menus.

### Why would this feature be useful?

Quick way to update the emulator.

**Comment by OpenSauce04** [comment]
Automatic updates are not planned, however automatic update checking will be implemented in the future once the installer is implemented

**Comment by OpenSauce04** [comment]
Superseded by #321
