### ISSUE TITLE
Games keep crashing on MACos (Lime3ds 2116)

### ISSUE THREAD

**Issue by vongolarch** [Lime3DS/Lime-3DS-Emulator#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3ds 2116

### Description of Issue

I tried running several games, but they all crashed after reaching a certain point (ex. Monster Hunter Stories crashed after the first cutscene). I tried to turn off the cache driver but with no success.  I think it's a problem related with Vulkan.

### Expected Behavior

Should run the games smoothly 

### Reproduction Steps

Run a game with the graphic set on Vulkan 

### Log File

<img width="861" alt="Screenshot 2024-07-26 alle 15 05 52" src="https://github.com/user-attachments/assets/25ba1d60-1cd2-4691-8cd4-e3bdb922c283">
<img width="861" alt="Screenshot 2024-07-26 alle 15 05 52" src="https://github.com/user-attachments/assets/65bd0f86-185b-4dfb-93a3-b7e6bd33dae3">
<img width="876" alt="Screenshot 2024-07-26 alle 15 06 04" src="https://github.com/user-attachments/assets/f18d2cbb-a06c-4662-bdcf-a4a9dc20fae3">
<img width="859" alt="Screenshot 2024-07-26 alle 15 06 42" src="https://github.com/user-attachments/assets/4e030010-2a4a-4fbb-b411-6ee85a4ffc86">

### System Configuration

CPU: M1
GPU/Driver:
RAM: 8gb
OS: MACos 14.5

**Comment by rtiangha** [comment]
This isn't Lime3DS but the Vulkan bits are updated to support the latest vulkan-sdk (1.3.290); does [this build](https://github.com/rtiangha/bravely-offline-citra/actions/runs/10101773727/artifacts/1741558114) work on your machine (artifact expires in about a week)?

Edit: And did things ever work correctly on previous versions of Lime3DS? If so, which one(s)?

**Comment by OpenSauce04** [comment]
@vongolarch Please follow the above comment
