### ISSUE TITLE
Sleep Mode

### ISSUE THREAD

**Issue by sp11111111** [Lime3DS/Lime-3DS-Emulator#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The implementation of the 3DS sleep mode on Lime3DS

### Why would this feature be useful?

This feature would be useful because Lime3DS would better emulate the 3DS and at the same time have more features for the users. This would also bring more joy for the users.

**Comment by OpenSauce04** [comment]
What benefit does this have over simply pausing emulation?

**Comment by sp11111111** [comment]
It would let you streetpass with another instance of lime3ds.

**Comment by OpenSauce04** [comment]
Streetpass isn't even implemented in Lime3DS, and even if it was you wouldn't be able to actually receive real streetpass hits.
I'll be closing this as not planned, as there is seemingly no valid use case.

**Comment by sp11111111** [comment]
Excuse me/I apologize for opening another issue but what I was trying to say ask something kind of different which is the following question. Is StreetPass not possible to emulate in the first place? StreetPass would be part of 3DS emulation.
