### ISSUE TITLE
Alguns jogos nao funcionando em vulkan!!

### ISSUE THREAD

**Issue by Gilyusuke** [Lime3DS/Lime-3DS-Emulator#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

99f8259

### Description of Issue

Ao ultilizar a vulkan alguns jogos quebram e nao iniciao apos o menu 

### Expected Behavior

Jogos como resident e asphalt estao normais 

### Reproduction Steps

Menu crashando ao tentar abrir algums games 

### Log File

[lime3ds_log.txt](https://github.com/user-attachments/files/16433656/lime3ds_log.txt)
[lime3ds_log.old.txt](https://github.com/user-attachments/files/16433658/lime3ds_log.old.txt)

### System Configuration

CPU:8
GPU/Driver:mali
RAM:4
OS:android 11

**Comment by OpenSauce04** [comment]
Some games being less compatible than others is entirely expected and is not a bug. If you wish, you can make reports for specific games.
