### ISSUE TITLE
Vulkan crashando o emulador

### ISSUE THREAD

**Issue by Gilyusuke** [Lime3DS/Lime-3DS-Emulator#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

99f8259

### Description of Issue

Alguns jogos nao abrem ao ultilizar vulkan

https://github.com/user-attachments/assets/d09ac93d-abf0-4964-af45-72dd521910bf

### Expected Behavior

Jogos como resident estao abrindo mas alguns ocorrem de nao execultar apos abrir o menu

### Reproduction Steps

Ao inicia o menu o emulador tem uma queda beusca na performance fechando o emulador 

### Log File

[lime3ds_log.old.txt](https://github.com/user-attachments/files/16435762/lime3ds_log.old.txt)
[lime3ds_log.txt](https://github.com/user-attachments/files/16435763/lime3ds_log.txt)

### System Configuration

CPU:8
GPU/Driver:mali
RAM:4
OS:android 12

**Comment by OpenSauce04** [comment]
Your game's ROM is bad and the emulator cannot load it correctly. Please redump it.
