### ISSUE TITLE
Cannot run on the EMUI  Android10.0 system

### ISSUE THREAD

**Issue by a442509097** [Lime3DS/Lime-3DS-Emulator#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3DS 2116

### Description of Issue

When in "Select User" tab, Because the system File Manager cannot be found, Can you add a Storage Permission?

### Expected Behavior

.

### Reproduction Steps

.

### Log File

.

### System Configuration

CPU:
GPU/Driver:
RAM:
OS: EMUI 10.1.0, Android 10

**Comment by OpenSauce04** [comment]
Please fill out the issue form properly.
