### ISSUE TITLE
Friend request button

### ISSUE THREAD

**Issue by SpanioHack** [Lime3DS/Lime-3DS-Emulator#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

There is no friend requesting button so how can we play with friends you should bring the feature

### Why would this feature be useful?

We can play with friends and it will be fun

**Comment by OpenSauce04** [comment]
This is out of the scope of the emulator. Multiplayer is achieved through hosted rooms.
