### ISSUE TITLE
Building for Arch AUR package fails

### ISSUE THREAD

**Issue by username227** [Lime3DS/Lime-3DS-Emulator#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Latest commit from github.

### Description of Issue

Hi, My arch package no longer builds as of today. I'm unsure what changed. I have updated the dynarmic submodule information based on today's commit. However, I still cannot get it to get through the preparation. I am attaching a log of the build. The Arch package pkgbuild is on the AUR. 

[build log.txt](https://github.com/user-attachments/files/16459958/build.log.txt)

### Expected Behavior

To build properly

### Reproduction Steps

See above

### Log File

See the attached file

### System Configuration

CPU: AMD
GPU/Driver: AMD/Nvidia
RAM: 16
OS: Arch

**Comment by OpenSauce04** [comment]
It doesn't seem like the git submodules have been downloaded correctly. Please bring this up with the AUR package maintainer.

**Comment by username227** [comment]
right, except that the same thing happens when I build directly. This is after downloading all submodules recursively.

[build log.txt](https://github.com/user-attachments/files/16460240/build.log.txt)

**Comment by OpenSauce04** [comment]
Not sure what's going on here. I'll try configuring from a fresh clone on my system using the same commands

**Comment by OpenSauce04** [comment]
Works fine on my end. No idea what's going on with your system
```
-- Configuring done (52.4s)
-- Generating done (0.9s)
-- Build files have been written to: /tmp/Lime3DS/build
```

**Comment by OpenSauce04** [comment]
My cmake version is slightly older than yours [3.28.5<3.30.1], so I'll try updating to your version and see what happens

**Comment by OpenSauce04** [comment]
Also, it's worth noting that the error in your personal compilation and the error in the AUR package is different. The AUR maintainer likely still needs to be informed of the original issue.

**Comment by username227** [comment]
which submodule in the AUR package isn't loading properly?

**Comment by OpenSauce04** [comment]
`Lime3DS/externals/dynarmic/externals/mcl` is the module which threw the error, but there may be others as I don't know if a single error would stop other subsequent errors from being thrown.

**Comment by OpenSauce04** [comment]
I have configured a fresh clone using cmake 3.30.1 and am still able to finish just fine. Genuinely clueless as to what is happening here. The error specific to your system seems to be the following:
```
CMake Error at externals/dynarmic/CMakeLists.txt:188 (install):
  install TARGETS given target "robin_map" which does not exist.
 ```
 I'm going to open a new issue to track this in case others discover it and will leave this issue to refer to the AUR packaging mistake

**Comment by username227** [comment]
robin-map is a submodule of the new dynarmic, so it likely has to do with that as well. 

OK I think I see the problem with the AUR package. It would appear that your new dynarmic repo has a bunch of submodules of its own which were 100% not present in the old dynarmic. Let me see if I can fix that.

**Comment by OpenSauce04** [comment]
The missing submodule issue is definitely on the AUR packaging end, but the `robin_map` issue doesn't appear to be so, as it happens for you without using the AUR and *doesn't* happen for me.

**Comment by username227** [comment]
yes, you are right about the AUR package. I am working on testing the fix right now. My bad - I should have checked to see if the new dynarmic had submodules, but I didn't imagine it would be different from the old one in that regard.

I will take a closer look at the robin-map error and see if I can figure anything out.
