### ISSUE TITLE
Lime3DS fails to create game shortcuts on desktop and applications menu in Linux

### ISSUE THREAD

**Issue by Windows7Pro2009** [Lime3DS/Lime-3DS-Emulator#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2116

### Description of Issue

Whenever I try to create a shortcut for a game in Lime3DS, it shows an error for creating a shortcut for desktop and application menu.
![Screenshot_20240807_161844](https://github.com/user-attachments/assets/b795eb46-4983-4ea1-9e42-4db67d7ee3dd)
![Screenshot_20240807_161931](https://github.com/user-attachments/assets/19f7a2f7-aab7-4626-aeee-e66e210b6e6e)
 

### Expected Behavior

It should create a direct game shortcut on the desktop or in the application menu, i.e when you open the shortcut, it should directly launch the game.

### Reproduction Steps

1. Open Lime3DS
2. Right click on any 3DS game, then Create Shortcut>Add to Desktop/ Add to Application Menu

https://github.com/user-attachments/assets/942f1042-480e-4c58-b577-f7e3ae37fd97

### Log File

[lime3ds_log.txt](https://github.com/user-attachments/files/16523531/lime3ds_log.txt)

### System Configuration

Laptop: ASUS TUF Gaming A15 FA506IHRB-HN080W
CPU: AMD Ryzen 5 4600H 6C/12T 3.0GHz
GPU/Driver: NVIDIA GeForce GTX 1650 Mobile 4GB GDDR6 (using the proprietary nvidia-driver-550, a.k.a Nvidia-G06 driver in openSUSE)
RAM: Samsung 8GB single channel DDR4 RAM at 3200 MHz
OS: openSUSE Tumbleweed 20240806 on Linux 6.10 kernel
DE: KDE Plasma 6.1.3
WM: X11

**Comment by OpenSauce04** [comment]
I think I know what's going on here from the logs.
Thanks for the report, I will add this to the roadmap for the 2117 update.
