### ISSUE TITLE
Cant download system files

### ISSUE THREAD

**Issue by ollietheotter983** [Lime3DS/Lime-3DS-Emulator#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Latest

### Description of Issue

Getting an error whenever i try to download system files, no matter which, no matter how good the connection, mobile data or wifi.
![Screenshot_20240808_093003_Lime3DS](https://github.com/user-attachments/assets/f4d5d6db-4586-46ff-9d63-187ca6295529)

### Expected Behavior

Files download normally

### Reproduction Steps

Try to download system files

### Log File

It wont let me share it for some reason

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by daodov** [comment]
same issue (Redmi Pad SE 6/128GB, Android 14/HyperOS 1.0.2.0)

seems to be a common issue, I saw multiple people with various devices have it on multiple versions of Citra

**Comment by ollietheotter983** [comment]
Apparently I just had bad keys nvm(replying by email so cant close rn)

**Comment by BlurrySquire** [comment]
Another person in the discord experienced this issue. When they redumped their AES keys the issue was gone. Please try redumping your AES keys and see if that fixes the issue.

**Comment by OpenSauce04** [comment]
Closing as user error as the author resolved the issue themselves.
