### ISSUE TITLE
Enable cheat codes 

### ISSUE THREAD

**Issue by David8566** [Lime3DS/Lime-3DS-Emulator#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Enable the use of cheat codes on the android version 

### Why would this feature be useful?

Because it allows you to  cuatomize the gameplay, in unique ways that the standard game doesn't allow,  and it's more fun to play with that option.

**Comment by OpenSauce04** [comment]
You can open the cheat menu by long pressing on a game entry.
