### ISSUE TITLE
'enable gamemode' option does nothing

### ISSUE THREAD

**Issue by WinterWolfGames** [Lime3DS/Lime-3DS-Emulator#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2116 flatpak

### Description of Issue

the option 'enable gamemode' under emulation>configure>general does nothing. I have installed gamemode as well as an extension for GNOME that adds an indicator to the top bar that turns green when gamemode is active. the indicator does not change no matter what I do in the configuration or individual game.

### Expected Behavior

gamemode working 

### Reproduction Steps

open lime, check the 'enable gamemode' option on, launch game (I tried fire emblem awakening and fates, as well as pokemon mystery dungeon: gates to infinity)

### Log File

[lime3ds_log.txt](https://github.com/user-attachments/files/16604291/lime3ds_log.txt)

### System Configuration

CPU: intel i7 10700k
GPU/Driver: nvidia rtx 3060
RAM: 16gb
OS: Pop!_os

**Comment by OpenSauce04** [comment]
Have you verified that this functionality works when using a non-flatpak build such as the AppImage or built from source?

**Comment by WinterWolfGames** [comment]
I tried running the appimage but its giving an error in the terminal that im missing GLIBC_2.36. 2115 gives the same error. from a quick search glibc is OS based and I cant change it

**Comment by ghost** [comment]
You can spin up a disteobox or live usb and test there?

**Comment by directentis1** [comment]
> I tried running the appimage but its giving an error in the terminal that im missing GLIBC_2.36. 2115 gives the same error. from a quick search glibc is OS based and I cant change it

Same problem... The AppImages need to build in older version of Ubuntu (with lower version of glibc) to be able to use in more distributions.

**Comment by ghost** [comment]
Why was this closed?
