### ISSUE TITLE
Games don't work when Realtime audio is Enabled

### ISSUE THREAD

**Issue by ghost** [Lime3DS/Lime-3DS-Emulator#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3DS 2116

### Description of Issue

Games no longer work after enabling the 'Realtime Audio' option from Audio setting. Games either get stuck on black screen or don't boot at all. Games work fine if the option is Disabled but the audio is distorted and I don't like it. I'm still using the Lime3DS version 2115 because it doesn't have this issue on that version.

### Expected Behavior

Games should work fine after Enabling the Realtime Audio option.

### Reproduction Steps

Enable 'Realtime Audio' from the Audio setting and Boot a Game.

### Log File

Log file would contain the old software-version, hence it's not provided.

### System Configuration

CPU:
GPU/Driver: Vulkan
RAM: 4GB
OS: Android

**Comment by OpenSauce04** [comment]
Please open a new issue and attach a log as required by the issue template alongside more information about your device

**Comment by ghost** [comment]
Okay, Pardon me!
