### ISSUE TITLE
Particles (light/rain etc...) disable ingame

### ISSUE THREAD

**Issue by federicorosso1993** [Lime3DS/Lime-3DS-Emulator#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The ability to disable ingame graphical effects like light ray from the sun and rain.

### Why would this feature be useful?

I've noticed that in games like Mario Kart 7 these types of effects cause the frame rate to plummet, if these graphical effects could somehow be disabled the performance would improve a lot for a lot of people since most track on Mario Kart 7 (for example) without this effect got a stable and really good framerate... You can see this problem in any level where it rain or like in the first track only when the sun ray is visible (for most of the track is not but during the initial cutscene it is).

**Comment by BlurrySquire** [comment]
It isn't possible for the emulator to disable these features. Unfortunately you will have to find a cheat code to disable these as they are part of the game and not the emulator.

**Comment by federicorosso1993** [comment]
Ah ok I was thinking that maybe it could be done since it is possible to change the internal resolution of games and other things. If it's not possible thanks anyway for letting me know.
