### ISSUE TITLE
Hotkeys don't function after changing settings

### ISSUE THREAD

**Issue by TheRealWario** [Lime3DS/Lime-3DS-Emulator#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime 2117

### Description of Issue

Like it says in the title. This is essentially the same issue as #277, but the difference is that its for the Mute function, and that it never works no matter what window is clicked on.

### Expected Behavior

The mute hotkey shouldn't break from using the settings window, yes?

### Reproduction Steps

enter the emulator in a fresh boot, open up the settings window and simply press "ok", and the mute hotkey will refuse to function.

### Log File

[lime3ds_log.txt](https://github.com/user-attachments/files/16632068/lime3ds_log.txt)

### System Configuration

CPU: AMD Ryzen 5 5600H
GPU/Driver: NVIDIA GTX 1650
RAM: 24 GB
OS: Win 11 23H2

**Comment by ghost** [comment]
All QShortcuts are broken since https://github.com/Lime3DS/Lime3DS/pull/333 

Specifically the for loop in hotkey.cpp  that is supposed to update the hotkeys in-runtime does nothing

**Comment by OpenSauce04** [comment]
This is super my bad, I'll look at it now. Should be very easy to fix.

**Comment by ghost** [comment]
> This is super my bad, I'll look at it now. Should be very easy to fix.

I looked at it, wasn't too easy

Didn't have time to go through

**Comment by OpenSauce04** [comment]
> Specifically the for loop in hotkey.cpp that is supposed to update the hotkeys in-runtime does nothing

This seems like a false trail. The much more likely explaination is that I just forgot to disconnect existing shortcuts in `connect_shortcut` and it caused an ambiguous shortcut overload, exactly the same as the Citra team did with the original shortcut issue.

**Comment by OpenSauce04** [comment]
Turns out everything I said above was utterly wrong, and it was instead caused by a subtle mistake I made in an earlier commit. Whoops 🙃
