### ISSUE TITLE
Flatpak Support

### ISSUE THREAD

**Issue by dnet890** [Lime3DS/Lime-3DS-Emulator#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I wish there is a flatpak support like other similar software

### Why would this feature be useful?

I hope I can run this app on Steam Deck and enjoyed it

**Comment by OpenSauce04** [comment]
Flatpak support is already planned as soon as we begin full releases. We have the manifests ready

**Comment by AsciiWolf** [comment]
https://flathub.org/apps/io.github.lime3ds.Lime3DS
