### ISSUE TITLE
Auto Language detection error

### ISSUE THREAD

**Issue by Bubsb** [Lime3DS/Lime-3DS-Emulator#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2117.1

### Description of Issue

![tttttt](https://github.com/user-attachments/assets/3a772f48-305f-4945-8d7e-9171210b6914)

The program auto detects my language incorrectly, despite this being listed as having been fixed in the dev notes. 

### Expected Behavior

It should autodetect my language as English.

### Reproduction Steps

Download the build? I really don't know what caused this, my system only has one locale.

### Log File

I don't know how to pull this the entire UI is in a language I can't read, and I can't find instructions on how to change it manually.

### System Configuration

CPU:7800x3D
GPU/Driver: 4070TI Super
RAM:64gb
OS:Win10

**Comment by ghost** [comment]
I tested with language set to English,  and secondary languages were german and Spain 

Before it would get German by the default, now it gets English as default 

Can you show the Windows settings menu for languages, and also, did you use a new user folder or the same one?

**Comment by BlurrySquire** [comment]
> did you use a new user folder or the same one?

A simple thing you could do is in the folder where you have Lime3DS create and empty folder named ``user``. When you next open Lime3DS it will write all the configuration files there. Don't worry it won't delete your previous ones in ``%appdata%/Lime3DS``. Then we can see if it works correctly after changing windows settings.

**Comment by ghost** [comment]
Since this is still a common bug even after the attempted fix, i re-opened the original issue https://github.com/Lime3DS/Lime3DS/issues/242
