### ISSUE TITLE
Android version Lime3ds 2117.1 C-stick not smooth !!

### ISSUE THREAD

**Issue by Hellogamesart** [Lime3DS/Lime-3DS-Emulator#377]
### Issue

Android version Lime3ds 2117.1 C-stick not smooth !!

**Comment by ghost** [comment]
Bro, what?

A video recording would be nice

**Comment by ghost** [comment]
And please refrain from spamming the same issue 3 times again

**Comment by OpenSauce04** [comment]
Please choose the Bug issue form and fill out the form fully.
