### ISSUE TITLE
Android version Lime3ds 2117.1 C-stick not smooth !!

### ISSUE THREAD

**Issue by Hellogamesart** [Lime3DS/Lime-3DS-Emulator#378]
### Issue

Android version Lime3ds 2117.1 C-stick not smooth !!

Dragon quest VII VIII XI

**Comment by ghost** [comment]
https://github.com/user-attachments/assets/48b72b71-99a1-49cf-8dc8-02e467c0d4d4

**Comment by OpenSauce04** [comment]
Duplicate of #377
