### ISSUE TITLE
Android version Lime3ds 2117.1 C-stick no smooth !!

### ISSUE THREAD

**Issue by Hellogamesart** [Lime3DS/Lime-3DS-Emulator#379]
### Issue

Android version Lime3ds 2117.1 C-stick no smooth !!

**Comment by ghost** [comment]
Why did you spam the issue three times? 

![Screenshot_20240819_080638_YouTube.jpg](https://github.com/user-attachments/assets/76959514-07d9-42ef-adef-14f2ba4df5af)

**Comment by OpenSauce04** [comment]
Duplicate of #377
