### ISSUE TITLE
Touchscreen Buttons

### ISSUE THREAD

**Issue by Papermanzero** [Lime3DS/Lime-3DS-Emulator#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The original Citra had the option to map touchscreen coordinates to controller or keyboard buttons. It would be great to port this feature also to Lime3DS.

### Why would this feature be useful?

It is helpful for games to map touchscreen buttons to buttons to control camera, items, views etc. without the usage of a mouse.

**Comment by Daisouji** [comment]
![image](https://github.com/user-attachments/assets/3a22bab8-61a5-45da-b568-fe8f0f459d90)

**Comment by Papermanzero** [comment]
Where did you found the window? 🙈

**Comment by Daisouji** [comment]
Configure -> Controls -> Configure Motion/Touch -> Configure and just plot your points.
