### ISSUE TITLE
my second screen in pokemon x and y dont work in API grafics openGL

### ISSUE THREAD

**Issue by mouyzy** [Lime3DS/Lime-3DS-Emulator#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

i dont use this

### Description of Issue

![image](https://github.com/user-attachments/assets/9cd3887f-f046-4057-971b-bb0e3388fe66)
my second screen dont work in API openGL

### Expected Behavior

i entre in the game but my second screen dont work in api open gl in other like my softeware is work but the fps is so low and vulkan dont work in my pc 

### Reproduction Steps

i put the apia in open gl and my second screen dont work 

### Log File

![image](https://github.com/user-attachments/assets/45d587fb-9114-4bcd-aff2-9536ec80ec8e)

### System Configuration

CPU:                  idk 
GPU/Driver:
RAM:
OS:

**Comment by Jaizu** [comment]
Same here.
Window 11
Lime3DS 2117.1
Ryzen 5 5600
RX 6700 XT (24.7.1)

**Comment by OpenSauce04** [comment]
Please fill out the issue form correctly.

**Comment by ghost** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Affected Build(s)
> i dont use this
> 
> ### Description of Issue
> ![image](https://private-user-images.githubusercontent.com/179415639/361264136-9cd3887f-f046-4057-971b-bb0e3388fe66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjkxMDUsIm5iZiI6MTcyNDY2ODgwNSwicGF0aCI6Ii8xNzk0MTU2MzkvMzYxMjY0MTM2LTljZDM4ODdmLWYwNDYtNDA1Ny05NzFiLWJiMGUzMzg4ZmU2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxMDQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTQxMWQ0YzMwOThmYjcyN2RlMGQ2MGE4N2Q5NWEwMDQzNmUyYWIwYTIzY2YyNTZiNmI4NzliZmI3MDE4ZjlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IOH4ogIqk9m40ydUhXRWj0tLQd2_e4U5tSzI2oApbhc) my second screen dont work in API openGL
> 
> ### Expected Behavior
> i entre in the game but my second screen dont work in api open gl in other like my softeware is work but the fps is so low and vulkan dont work in my pc
> 
> ### Reproduction Steps
> i put the apia in open gl and my second screen dont work
> 
> ### Log File
> ![image](https://private-user-images.githubusercontent.com/179415639/361264303-45d587fb-9114-4bcd-aff2-9536ec80ec8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjkxMDUsIm5iZiI6MTcyNDY2ODgwNSwicGF0aCI6Ii8xNzk0MTU2MzkvMzYxMjY0MzAzLTQ1ZDU4N2ZiLTkxMTQtNGJjZC1hZmYyLTk1MzZlYzgwZWM4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxMDQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Nzk1ODQwMTMzNmFjNzkzODM0ZTdlZDg1MTEzYWU2ZDRhYThkYmQ0M2EyZTQwZjk2MzgzZmEzY2QzZWYzY2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xNnJgQ6fWZxmz1D7e6irGdRYEMM_P3Nny33lWwi1bUE)
> 
> ### System Configuration
> CPU: idk GPU/Driver: RAM: OS:

Log file is so me
