### ISSUE TITLE
Remove telemetry features

### ISSUE THREAD

**Issue by OpenSauce04** [Lime3DS/Lime-3DS-Emulator#40]
### Issue

We do not and will not use the telemetry feature that Citra originally had. This feature should be disabled and the backend code for it should be removed

**Comment by rtiangha** [comment]
Well, I helped write the one being used over in PabloMK7's fork. It nukes the web tab though (since there's no Citra Web Server to use Citra Web Services with making that tab pretty much useless).

If people are fine with that, I can see if I can adapt that pull request for use over here.
