### ISSUE TITLE
Auto frameskip is required

### ISSUE THREAD

**Issue by fight-fly** [Lime3DS/Lime-3DS-Emulator#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Have a option to do this.

### Why would this feature be useful?

Player who play emulator s should be aware of this feature.

Looking forward to future developers implementing this feature.

tx.

**Comment by OpenSauce04** [comment]
Please open a new issue where you more thoroughly describe the feature you are requesting. At the moment it isn't clear what you are referring to
