### ISSUE TITLE
Resolution 0.5x is required.

### ISSUE THREAD

**Issue by fight-fly** [Lime3DS/Lime-3DS-Emulator#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Add a item 0.5x to the configure ui, and implement this feature.

### Why would this feature be useful?

It should bring a different experience for certain devices and games.

Thank you.

**Comment by OpenSauce04** [comment]
Thanks for your suggestion, however this feature will not be implemented.
