### ISSUE TITLE
Hone menu shortcut in games list

### ISSUE THREAD

**Issue by BlurrySquire** [Lime3DS/Lime-3DS-Emulator#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

A shortcut in the games list that launches the home menu. There should be an entry for each home menu installed since I believe you can install multiple home menus (different regions). I think they should have their own section (like system tiles, installed titles and just roms) in the game list.

### Why would this feature be useful?

This is useful because you can easily launch the home menu. It can be a bit annoying to have to go to the menu and launch it there.

**Comment by OpenSauce04** [comment]
I believe that this functionality would be redundant given the existing method of launching the home menu.
