### ISSUE TITLE
Internal Updater for Lime3DS

### ISSUE THREAD

**Issue by Gabrielcnnunes** [Lime3DS/Lime-3DS-Emulator#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Would be good to download and install updates with an internal updater like the old Citra had. With an option to automatic know when there is new updates for Lime3DS, without clicking in check update button.

### Why would this feature be useful?

Quick and easy to update the emulator.

**Comment by ghost** [comment]
Kind of a duplicate of https://github.com/Lime3DS/Lime3DS/issues/321

Reason i say kinda is  because only an update checker is planned , the update checker might point you to an installer for the latest version of the app

The installer is planned for 2118, and the update checker for 2119
