### ISSUE TITLE
Lime 3DS is not launching

### ISSUE THREAD

**Issue by AARAVJAMWAL** [Lime3DS/Lime-3DS-Emulator#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2117.1

### Description of Issue

I have installed the latest version of lime 3ds but my emulators is not even launching. 

### Expected Behavior

.

### Reproduction Steps

.

### Log File

.

### System Configuration

CPU: Ryzen 5 2500u
GPU/Driver: Vega 8 Mobile 23.19.14.04 
RAM:12 GB
OS: Windows 11

**Comment by OpenSauce04** [comment]
Please fill out the issue form properly.
