### ISSUE TITLE
Online Functionality

### ISSUE THREAD

**Issue by TwistedTempest** [Lime3DS/Lime-3DS-Emulator#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Thanks to the work of [PabloMK7](https://github.com/PabloMK7) there exists a fork of Citra capable of online multiplayer by communicating with the Nintendo (and Pretendo if [this issue](https://github.com/PabloMK7/citra/issues/44) is resolved) networks. If possible, would it make sense to borrow this functionality and add it to the official Lime3DS build?

### Why would this feature be useful?

It would enable communication with real 3DS systems, and since the Nintendo Network is soon to be defunct it would rely on a third-party, open source server, so legal issues would likely not be present.

**Comment by OpenSauce04** [comment]
This is definitely something we should look into down the line

**Comment by OpenSauce04** [comment]
Superseded by #47
