### ISSUE TITLE
Add Custom CPU tick option

### ISSUE THREAD

**Issue by Alewood0** [Lime3DS/Lime-3DS-Emulator#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

This feature exists in "Mandarine3DS" and enables certain games to be played at full speed.

### Why would this feature be useful?

This feature would allow users to play "Lord of Magna: Maiden Heaven" at full speed as it currently runs at 5fps and 10% speed on most android devices

**Comment by ghost** [comment]
The main mentainer has made it clear that he doesn't want "stable" hacks from Mandarine

That also includes this feature,  at least in the current implementation that is on Mandarine 

Not fully out of the picture,  but it ain't happening any time soon
