### ISSUE TITLE
Allow for immersive mode on Android 

### ISSUE THREAD

**Issue by TheParagone** [Lime3DS/Lime-3DS-Emulator#424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Currently Lime doesn't allow for usage of the screen past the camera notch. This could be allowed with android immersive mode or similar. As far as I know this isn't hard to implement on most apps and is already implemented in other unofficial builds.

I'll add an example of how it works currently (notice the left side of the screen where not even virtual buttons go into).
![Screenshot_2024-09-08-12-18-07-27_5e472b6cae810a6c81a1cdbb210ab99c](https://github.com/user-attachments/assets/9e503f5a-3909-4360-a152-17639476c050)

### Why would this feature be useful?

You would gain around 10% of screen real estate while not requiring much work.

**Comment by fallingSparr0w** [comment]
This is already in the works
https://github.com/Lime3DS/Lime3DS/pull/419

**Comment by TheParagone** [comment]
[Here](https://developer.android.com/develop/ui/views/layout/immersive) is the official API and how to implement it.

**Comment by TheParagone** [comment]
> This is already in the works #419

My bad, didn't find the specific thread, I'll close this one.
