### ISSUE TITLE
Backport Qt version to allow Lime to work on old Windows OS versions

### ISSUE THREAD

**Issue by Darthagnon** [Lime3DS/Lime-3DS-Emulator#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Qt 6 dropped Win7 support, and does not work universally on Win10 - some versions of Qt 6 work only on newer versions of Win10. As it is only used for the GUI and not for the backend, would it be possible to regress the Qt version to Qt 5, or to use [a version of Qt 6 that has compatibility patches for older releases of Win10, Win8 and Win7](https://github.com/crystalidea/qt6windows7)?

### Why would this feature be useful?

Old releases of Citra ran on all versions of Windows, before the jump to Qt6. It would be nice to allow its successor to run on older machines or gaming machines intentionally locked to older/more performant versions of Windows.

**Comment by fallingSparr0w** [comment]
This is unlikely, as if development for old windows versions was continued, it would take more time and possibly not allow for large scale improvements.

**Comment by rtiangha** [comment]
You have a GitHub account, so what you could do is fork the repository, enable the Actions tab, edit the main `CMakeLists.txt` file and change the QT version. Push the changes back (or use the web editor; it'll push the changes when you save) and GitHub will build a new version for you and you can see if it will work. You might need to set `ENABLE_QT6` in that same file to `OFF` if you really want to try QT5.

**Comment by rtiangha** [comment]
Another thing you could try is replacing the QT dlls that come bundled with Lime3DS with those from the link you provided. Might work, might not (currently, Lime3DS is compiled against 6.7.2 on Windows so that version might work better, if at all).

**Comment by OpenSauce04** [comment]
Thanks for the suggestion, but this will not be implemented as we have no interest in supporting Windows versions before Windows 10. I would suggest following the steps mentioned above.
