### ISSUE TITLE
pokemon x closes by itself 

### ISSUE THREAD

**Issue by Raffadanttas** [Lime3DS/Lime-3DS-Emulator#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2118

### Description of Issue

when I'm playing pokemon x after an hour the game just closes 

### Expected Behavior

Go to pokemon x and see

### Reproduction Steps

1 - open pokemon x and play 
2 - when pass one hour the game will close

### Log File

Nothing

### System Configuration

CPU: SAMSUNG Exynos 1380
GPU/Driver: Mali-G68 MP5
RAM: 8gb
OS: Android 14

**Comment by ghost** [comment]
This issue is not only causing in Pokémon X but with all games.

I tested Lego Marvel Avengers leaving the game for approximately 10 minutes untouched , I only just rotated the screen, the game got crashed.

**Comment by i0x404** [comment]
Can you provide log files please?

**Comment by OpenSauce04** [comment]
I will mark this issue as Stale pending the addition of a log file. Please add a comment to this issue which contains it.

**Comment by Raffadanttas** [comment]
I delete the log 🥲

Em qua., 18 de set. de 2024, 15:03, OpenSauce ***@***.***>
escreveu:

**Comment by OpenSauce04** [comment]
Please create a new issue with the log attached if the issue happens again
