### ISSUE TITLE
Support for TWL_FIRM, NTR_FIRM and AGB_FIRM

### ISSUE THREAD

**Issue by WindowsNinetyTen** [Lime3DS/Lime-3DS-Emulator#431]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What feature are you suggesting?

I think that it would be useful if emulation of the 3DS hardware responsible for the TWL_FIRM (DSi Mode), NTR_FIRM (DS Mode) and AGB_FIRM (GBA Mode) were added. The DSi and DS Modes would still be able to support GBA connectivity and emulate the DS Rumble Pak using the phone's vibrator, and the GBA Mode would still be able to emulate the GameCube-GBA Cable, Link Cable and Wireless Adaptor using the phone's hardware, the rumble in games using the phone's vibrator and the motion sensor using the phone's own motion sensor.

### Why would this feature be useful?

It would reduce the need for multiple emulators for these games, as well as providing a more authentic 3DS experience. Plus, with the 3DS Circle Pads, this emulator could be used to play Super Mario 64 DS with analogue controls, using a patch for the ROM.

**Comment by fallingSparr0w** [comment]
This is not planned. Maybe once everything works the same way as the physical hardware, it could be looked into.

**Comment by OpenSauce04** [comment]
We do not plan to add support for DS or GBA emulation.

**Comment by WindowsNinetyTen** [comment]
By the way, JaffaCat, your username looks familiar. Are you the same user who administrates SquirttheCat?
