### ISSUE TITLE
Low and unstable framerate

### ISSUE THREAD

**Issue by misoroico** [Lime3DS/Lime-3DS-Emulator#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3DS 2118

### Description of Issue

Independently of the game or settings that the game never goes above 25 fps and even then it is extremely unstable, although i have installed every driver update i could and already have C++ runtime installed and updated there is no sign of it working as supposed to, i even deactivated all external backgroud apps i could and nothing changed, even switching from msvc to msys2 doesn't work

### Expected Behavior

For whatever reason my pc wont let me had videos rn, but it was just a video of how bad the framerate was

### Reproduction Steps

I dont really understand what could cause the issue in the first place so i don't know how to replicate it

### Log File

[lime3ds_log.old.txt](https://github.com/user-attachments/files/16971547/lime3ds_log.old.txt)
[citra_log.txt.old.txt](https://github.com/user-attachments/files/16971548/citra_log.txt.old.txt)
[citra_log.txt](https://github.com/user-attachments/files/16971549/citra_log.txt)

### System Configuration

CPU:AMD Ryzen 5 3600 6-core
GPU/Driver: Rtx 2060
RAM:16 gb ddr4
OS: Windows 10

**Comment by fallingSparr0w** [comment]
The low frame rate is caused by setting your audio type to LLE, which is what you have apparently done. Reverting it to HLE should fix the issue. In future, please don't change random settings like this unless you know what they do.

**Comment by misoroico** [comment]
> The low frame rate is caused by setting your audio type to LLE, which is what you have apparently done. Reverting it to HLE should fix the issue. In future, please don't change random settings like this unless you know what they do.

Thanks for the information, I'll try it when I get home

**Comment by RiskiVR** [comment]
> The low frame rate is caused by setting your audio type to LLE, which is what you have apparently done. Reverting it to HLE should fix the issue. In future, please don't change random settings like this unless you know what they do.

This fixed it for me, thanks for mentioning it ^^
I had no idea audio emulation was this expensive.
