### ISSUE TITLE
Lime 3ds antutu

### ISSUE THREAD

**Issue by 1601game** [Lime3DS/Lime-3DS-Emulator#434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Im suggesting a version of lime 3ds antutu that have a package that is com.antutu.ABenchMark

### Why would this feature be useful?

Im suggesting that because can make so much devices work really better the why  is a tricking that is running a benchmark app, and will boost performance on some device like old sansungs and notebooks. Just like citra that is already dead 
HERE THE LINK
https://objects.githubusercontent.com/github-production-release-asset-2e65be/196913509/e7b25c45-d6c4-45cb-a0df-aed817567a78?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240912%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240912T183842Z&X-Amz-Expires=300&X-Amz-Signature=cd0a6dec7ebb1a7d684d5fe348a04a0f12410d07eff5d837c1d9e2b102911b02&X-Amz-SignedHeaders=host&actor_id=165434894&key_id=0&repo_id=196913509&response-content-disposition=attachment%3B%20filename%3DCitra_MMJ_20240520_Antutu.apk&response-content-type=application%2Fvnd.android.package-archive

**Comment by 1601game** [comment]
If that really come to the devs im really gonna Feel greatfull

**Comment by OpenSauce04** [comment]
Thanks for your suggestion, however we have no interest in implementing this. Feel free to adjust the value yourself then build and use the resulting apk.

**Comment by ghost** [comment]
I'll test if this is even worth doing and maybe i fork it if it really helps
