### ISSUE TITLE
all pokemon type water glitch white

### ISSUE THREAD

**Issue by Alsacety** [Lime3DS/Lime-3DS-Emulator#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3ds 2118

### Description of Issue

![Screenshot_2024-09-14-22-25-38-809_io github lime3ds android](https://github.com/user-attachments/assets/fe9261b7-08d4-42c5-8f8b-7db388124e7a)

### Expected Behavior

help fix

### Reproduction Steps

all pokemon type water glitch white

### Log File

![Screenshot_2024-09-14-22-25-38-809_io github lime3ds android](https://github.com/user-attachments/assets/de47fa3b-388c-4bd6-9838-a1c32d2bc2e5)

### System Configuration

CPU:Snapdragon 680
GPU/Driver:Octa-core Max 2.40GHz
RAM:6
OS:1.0.5.0 TGCMIXM

**Comment by Alsacety** [comment]
pokemon alpha Sapphire 1.4

**Comment by Alsacety** [comment]
xiaomi note 11

**Comment by OpenSauce04** [comment]
Please fill out the issue form correctly.
