### ISSUE TITLE
Vulkan popup error

### ISSUE THREAD

**Issue by sonic-linux** [Lime3DS/Lime-3DS-Emulator#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2118

### Description of Issue

I keep encountering this popup whenever I launch Lime; my system doesn't support Vulkan, and I'm using OpenGL, so I wouldn't expect this error to appear at all.
![Screenshot (6)](https://github.com/user-attachments/assets/82749dc3-36f8-4e28-a641-ba2b6220d6c3)

### Expected Behavior

no error popup

### Reproduction Steps

simply launching the app

### Log File

[lime3ds_log.txt](https://github.com/user-attachments/files/17010691/lime3ds_log.txt)

### System Configuration

CPU: Intel Core i7-5500U
GPU/Driver: NVIDIA GeForce 820M
RAM: 8GB
OS: Windows 11 24h2

**Comment by sonic-linux** [comment]
I found this line in the log file. 

[   2.187102] Frontend <Error> lime_qt\util\graphics_device_info.cpp:GetVulkanPhysicalDevices:45: Error occured while querying for physical devices: Vulkan 1.1 is required, but only 1.0 is supported by instance!

Is there a method to query Vulkan devices silently without displaying the error popup?

**Comment by BlurrySquire** [comment]
This is just it checking for graphics API support. So it will check if you have Vulkan and OpenGL support. I don't think there is a way to make this silent unless we change it to show once on initial setup and never again as a setting/config option.

**Comment by OpenSauce04** [comment]
@BlurrySquire Why wouldn't we be able to simply have this only show up if Vulkan is selected as the issue author implied?

**Comment by sonic-linux** [comment]
It appears that the issue is not limited to Lime but extends to Citra as well. I have discovered that the oldest version of Citra which does not display the popup is version 1893 Nightly. Any subsequent version, including the pabloMK7 Releases, shows the popup. It seems that not many users are troubled by the popup, or perhaps they are not using older systems as emulator devices.
I believe I will use the old version for the sake of convenience.

**Comment by BlurrySquire** [comment]
> @BlurrySquire Why wouldn't we be able to simply have this only show up if Vulkan is selected as the issue author implied?

It may be possible but would require the graphics detection code to be run before starting a game then because what if they have it set to opengl (on boot it only checks for opengl) then change it to vulkan before loading a game (only opengl was checked so we would then have to check for vulkan). But this could be the other way round where it was vulkan then changed to opengl.

There is also the option to change graphics API for specific games which would get in the way.

I think it would be easier to make it so the pop up has an option called "don't show again" and when checking for graphics devices we just see if the user has that config set in the settings. If they have the popup disabled then it won't show.

**Comment by sonic-linux** [comment]
I believe this thread should have been labeled as a feature rather than a bug. Mainly because I have not encountered any real bugs, everything in Lime just works seamlessly.

**Comment by ghost** [comment]
> I think it would be easier to make it so the pop up has an option called "don't show again" and when checking for graphics devices we just see if the user has that config set in the settings. If they have the popup disabled then it won't show.

Can't we just re-run the check once the graphics API setting key is detected as updated?

Does it really run at boot every time you open the emulator lmao who designed this shi 

An info popup when changing to Vullkan API both globally or in per game config is enough

**Comment by sonic-linux** [comment]
Consider implementing it similarly to the Dolphin emulator: if a user selects the Vulkan API in the settings and their system does not support it, as in my case, it will display an error when a is game launched. However, it does not show any error upon simply launching the app, even if Vulkan has been selected.

**Comment by sonic-linux** [comment]
This means Lime3DS should only display the error when the game is launched and the Vulkan API is selected.
that's where the query should happen.

**Comment by BlurrySquire** [comment]
> Can't we just re-run the check once the graphics API setting key is detected as updated?
> 
> Does it really run at boot every time you open the emulator lmao who designed this shi 
> 
> An info popup when changing to Vullkan API both globally or in per game config is enough 

This actually makes a lot more sense. I feel it would be better to go with this approach where the check is run before running a game and when changing the graphics API.

It also does seem like it is ran every time Lime3DS starts up from looking at the logs.

**Comment by OpenSauce04** [comment]
We'll be going with kleidis's solution. It seems like the obvious best option.

**Comment by sonic-linux** [comment]
cool guess I'll be waiting for update and finally ditch this old Citra emu

**Comment by Link4Electronics** [comment]
On linux I have this problem with the last version 2118.2
![image](https://github.com/user-attachments/assets/d35bc4ca-5928-4cc9-a117-8a479fd36c0f)
and it doesn't let me use neither Vulkan nor OpenGL
Last working version is 2116, 2117 start showing the warning.
![image](https://github.com/user-attachments/assets/e1beaccf-b5b8-421f-ac90-d26efad64c62)

**Comment by sonic-linux** [comment]
Thanks to the developers, the issue has been resolved in version 2119. Now, I'm excited for the new project that you're developing with PabloMK7.
