### ISSUE TITLE
Option to disable Discord RPC entirely

### ISSUE THREAD

**Issue by BlurrySquire** [Lime3DS/Lime-3DS-Emulator#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The ability to completely disable the Discord RPC rather than just stopping it from showing the game being played. However, I think we should keep the option to disable showing the game played.

### Why would this feature be useful?

I think this would offer more customisability and the Discord activity thing can be a bit buggy when you try disabling it in the Discord settings.

**Comment by OpenSauce04** [comment]
What is a use-case for this that isn't covered by just setting your status to invisible?

**Comment by BlurrySquire** [comment]
> What is a use-case for this that isn't covered by just setting your status to invisible?

This might be a very specific use case but I go onto do not disturb to avoid getting notified for pings and I just don't want some apps coming up on my status.

**Comment by OpenSauce04** [comment]
In my opinion, this is really too niche to be considered.

If a user is, for whatever reason, particularly serious about this, they may wish to compile the emulator without Discord support using the `USE_DISCORD_PRESENCE` cmake option.

**Comment by ghost** [comment]
I was gonna add this but it seems the current option drops it entirely lol
Once i disable it the RPC connection goes away

**Comment by BlurrySquire** [comment]
Not sure then, from my experience it just stopped showing the game I was playing.
