### ISSUE TITLE
xBRZ not working properly as it did previously in Citra

### ISSUE THREAD

**Issue by alex100306** [Lime3DS/Lime-3DS-Emulator#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2118

### Description of Issue

The xBRZ filter seems to just have sharp pixels instead of the expected smoothing. I use the Auto (Window Size) internal resolution. This seems to mostly affect the bottom screen.
![xBRZ-in-Lime](https://github.com/user-attachments/assets/87fa5393-b8c0-47e8-bbb4-64287adf34af)

### Expected Behavior

The expected behavior (as it was in Citra) is for a smoothed out image. Same settings with the internal res being Auto.
![xBRZ-in-Citra](https://github.com/user-attachments/assets/63f6f44e-d7fa-4d64-b2b3-8ba8e19448c2)

### Reproduction Steps

Open a game and enable xBRZ texture filtering.

### Log File

[lime3ds_log.txt](https://github.com/user-attachments/files/17080803/lime3ds_log.txt)

### System Configuration

CPU:11th Gen Intel Core i5-1135G7
GPU/Driver:Intel Iris Xe Graphics/Mesa drivers
RAM: 8gb
OS: Arch Linux

**Comment by fallingSparr0w** [comment]
Your log says you are using the MMPX filter, not xBRZ.

**Comment by alex100306** [comment]
Then there must be some sort off issue in the UI because MMPX isn't an option and it shows xBRZ as selected.

**Comment by alex100306** [comment]
Here is a picture of the dropdown since I can't take a screenshot without clicking out of the box.
![PXL_20240920_211718110 MP](https://github.com/user-attachments/assets/b061796b-9cb9-42f3-970d-1440bbbb1bd4)

Edit: After setting it to ScaleForce the log shows it as xBRZ. Seems like the options in the dropdown are misaligned from where they should be.

**Comment by rtiangha** [comment]
Yeah; I think it's misaligned. This is the order the backend lists them as:

```
enum class TextureFilter : u32 {
    NoFilter = 0,
    Anime4K = 1,
    Bicubic = 2,
    ScaleForce = 3,
    xBRZ = 4,
    MMPX = 5,
};
```
I assume MMPX is Nearest Neighbor(?). Anyway, it's an easy fix, but just as a sanity check, does choosing the second last option in the drop down give you the expected xBRZ result (visually, I mean)?

Edit: Actually, upon further reflection, I think it's supposed to be MMPX and not Nearest Neighbor as a) they're two totally different algorithms, and b) Nearest Neighbor is a label that's used in the Texture Filtering drop down (so this is probably a copy/paste bug). Anyway, I'll submit a PR changing the drop down to match the order and labels of the backend code.

Edit 2: It's listed correctly in the Android frontend (both in order and in labelling), so yeah, no idea what happened back then. Easy fix, though.

**Comment by alex100306** [comment]
As for your question, yes selecting ScaleForce (option above xBRZ) does result in the xBRZ filter being applied (confirmed in the log file). And I'm glad it's an easy fix! I don't understand how this happened either seeing as it was correct back in Citra.

**Comment by OpenSauce04** [comment]
I'll throw this in as a last minute addition for 2118.1 considering how simple the fix is and how significant of an issue this resolves
