### ISSUE TITLE
Artic Base integration: 3DS Controller without Rom streaming

### ISSUE THREAD

**Issue by LiderKonmils** [Lime3DS/Lime-3DS-Emulator#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I want to request the possibility to connect to Artic Base Server to use the 3DS as a controller (with the full support of Gyroscope/Touch screen) but without the need to stream the rom itself from the physical 3DS to a PC (so, with dumped rom instead).

### Why would this feature be useful?

Why not use Artic Base as it is right now:
-Loading times. Having to wait 2 minutes each time you change room in a game is a real pain in the a**.

Why not just play on a real 3DS?
-Screen size, mods, 4k patches, possibility of streaming to Twitch/Youtube

Why not use Streaming from NTR CFW to PC?
-The wifi chipset of the 3DS will never be enough to stream gameplay with decent fps.

Why not use other apps?
-Nothing seems to be really compatible. I found 3dsController (who don't support Touchscreen and Gyro), CTroll3D (who have been abandonned since 2021 and need to be compilled for Windows, wich i'm not enough skilled for that), and Artic Base...

Why not ask PabloMK7 to add it? He's the one who created the app.
-The only thing he seem to be able to say on it's github when someone ask for a feature is "this is outside the scope of the tool"...

**Comment by OpenSauce04** [comment]
This is something that would need to come from Artic Base itself, not the emulator. Despite your reasoning in the issue description, this really does need to go through the Artic Base project first.

We can come back to this if it is ever implemented.
