### ISSUE TITLE
Fullscreen on game boot

### ISSUE THREAD

**Issue by Tsubasa0504** [Lime3DS/Lime-3DS-Emulator#458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Add an option to make games automatically be booted fullscreen.

### Why would this feature be useful?

When you are using frontends like ES-DE, you would find it better to automatically be fullscreen instead of having to use the keyboard to make it fullscreen.

**Comment by ghost** [comment]
I'll see if i can add this

**Comment by OpenSauce04** [comment]
The obvious solution is a launch parameter, right?

Was this something that the SDL executable was capable of? If so, we will lump this in with porting over those features, which is planned for 2119 anyway.

**Comment by ghost** [comment]
> Was this something that the SDL executable was capable of? 

A way to permanently set the lauch fullscreen? Idk, but i don't think so

I only know you can launch it with -f

**Comment by ghost** [comment]
I was just thinking of adding a new UIsetting, but that might not be the best for the cli ?

**Comment by OpenSauce04** [comment]
The use case the issue author gave was launching through a frontend, which would make the command line parameter approach obvious. I don't think a setting is the correct approach for addressing this.

As you mentioned, the SDL executable did have the ability to launch games in fullscreen. Because of that, this issue will be superseded by a PR which tracks the process of porting over SDL executable functionality.

**Comment by ghost** [comment]
> I don't think a setting is the correct approach for addressing this.
> 

Both ways could work, but yeah, a launch param is better for this certain usage

Although a GUI setting still would be nice for GUI users because I'm shocked, it's even missing in the first place

I'll leave it to you to add both

**Comment by ghost** [comment]
> As you mentioned, the SDL executable did have the ability to launch games in fullscreen. Because of that, this issue will be superseded by a PR which tracks the process of porting over SDL executable functionality.

Then it's a good idea to rename the issue to something along the lines of "Port SDL functionality to QT"and add it to 2119 milestones and a priority tag since we basically promised this

**Comment by QuirkyKirkHax** [comment]
Hey, while I think a parameter for this would be genuinely awesome to see, I want to throw in a temporary solution for front ends here.  If you happen to be using Launchbox, go to your emulators, select Lime3DS, and edit the "Exit Script" section.  Type the following into the box, no quotes:

"Process, Close, {{{StartupEXE}}}"

Open Lime3DS itself, make sure the fullscreen option is checked under View, and close.  From here, you can open your games inside of Launchbox/BigBox, and close it via the hotkey configured in Launchbox.  Normally this would exit fullscreen first, but with that exit script, it kills the process instead, leaving your fullscreen option intact.

But yeah, please add a parameter or something for this lol.

**Comment by OpenSauce04** [comment]
This should be covered under https://github.com/Lime3DS/Lime3DS/issues/462, so closing as duplicate
