### ISSUE TITLE
Pictures taken with 3DS Camera App also show up in Camera Roll

### ISSUE THREAD

**Issue by WindowsNinetyTen** [Lime3DS/Lime-3DS-Emulator#463]
### Issue

Is it normal that when I take a picture using the 3DS Camera App, it shows up in my phone's Camera Roll? I'm a little worried about privacy. Is there a way to allow it to use the Camera without saving to the Camera Roll?

**Comment by OpenSauce04** [comment]
When Lime3DS saves an image, it is saved as a garden variety jpeg to the Lime3DS user folder.
It is likely that your phone simply picked up on this image's existence and is displaying it to you, IE this isn't anything to do with us.

**Comment by rtiangha** [comment]
@WindowsNinetyTen FYI, if you don't want any photos taken with the 3DS emulator's camera to show up in your Android photo gallery, add a file named `.nomedia` to your root Lime3DS user folder and reboot your phone. The presence of a .nomedia file will prevent that folder from being indexed by the OS; that's just a general Android thing that you can easily do yourself.
