### ISSUE TITLE
Starfox 3DS Upside down Levels

### ISSUE THREAD

**Issue by NuelGFX** [Lime3DS/Lime-3DS-Emulator#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

all versions

### Description of Issue

Aquas, Solar, Andross levels are bugged and upside down. 

### Expected Behavior

level loads loads and the 3d scenery should be upright. 

### Reproduction Steps

can be reproduced when loading into those levels, bug is constant. 

### Log File

n/a

### System Configuration

CPU:snapdragon Gen 3
GPU/Driver:Adreno 750
RAM:12gb 
OS:android 14

**Comment by TheRealWario** [comment]
duplicate of #52, you can simply leave a comment there if you want this to get more attention. For now, can you close this issue?

**Comment by NuelGFX** [comment]
closing due to duplicate ticket.
