### ISSUE TITLE
Request: Add Xaudio2 and GBA Games Support

### ISSUE THREAD

**Issue by HelloZero2000** [Lime3DS/Lime-3DS-Emulator#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Adding Xaudio2 and GBA games support so able to play GBA games.

### Why would this feature be useful?

Since Citra is shutdown it won't able to add Xaudio2 and GBA games support.

**Comment by fallingSparr0w** [comment]
GBA support is not planned.

**Comment by HelloZero2000** [comment]
I believe he/she planned this if he/she do.

**Comment by HelloZero2000** [comment]
> GBA support is not planned.


I believe he/she planned this if he/she do.

**Comment by HelloZero2000** [comment]
then how about Xaudio2 support is also not planned sir @OpenSauce04
