### ISSUE TITLE
(android) customizable ui text colors

### ISSUE THREAD

**Issue by Coderst1** [Lime3DS/Lime-3DS-Emulator#482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Having the ui text color for Lime3DS be customizable to what the user wants

### Why would this feature be useful?

A nice little feature so that users can have different colors for their ui text

**Comment by OpenSauce04** [comment]
Does this not already exist? What specifically are you referring to?

**Comment by Coderst1** [comment]
> Does this not already exist? What specifically are you referring to?

I'm mainly referring to text color. Sorry for being a bit confusing, I had put this down at night so I'll change the title to match what I mean.

**Comment by OpenSauce04** [comment]
Which text do you mean? Just the general text across the whole app?

**Comment by Coderst1** [comment]
Yeah, since the only color we can use is white right now

**Comment by OpenSauce04** [comment]
I really don't think this is something that should be configurable. The overall theme of the app sure, but the text colour is something that is very well established to either be black or white depending on which is most ledgible. I don't think there is a valid use case for this that doesn't make the interface look horrendous.

**Comment by Coderst1** [comment]
Okey. That's fine then as it was just an idea anyways.
