### ISSUE TITLE
Two separate windows

### ISSUE THREAD

**Issue by Papermanzero** [Lime3DS/Lime-3DS-Emulator#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

It would be good to get two separate windows for top screen and bttm screen. So you can shift the second screen to another monitor. Maybe a combination would be also good to have the hybrid layout on one screen and the bttm screen on the second screen. This would be helpful if you use a tablet/phone as second monitor. So you can use the touchscreen functions like on the real 3DS

### Why would this feature be useful?

Flexibility to present the 3DS windows. And accurate emulation of the Bttm in a real touch monitor (for instance with the support of Weylus (https://github.com/H-M-H/Weylus)

**Comment by Papermanzero** [comment]
Here an example how it could look like if Lime supports two separate windows
![IMG_4801](https://github.com/Lime3DS/Lime3DS/assets/10263536/3b74a484-3fb5-4289-b786-3b96653ec19b)

**Comment by OpenSauce04** [comment]
This is already a feature. See View --> Screen Layout --> Separate Windows
