### ISSUE TITLE
Rename lime3ds.exe to Lime3DS.exe to match the official capitalisation

### ISSUE THREAD

**Issue by extherian** [Lime3DS/Lime-3DS-Emulator#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

lime3ds.exe and lime3ds-room.exe don't match the capitalisation seen in the actual user interface, as well as in the Lime3DS folder created by the installer. For perspective, the Dolphin project uses Dolphin.exe and Dolphin-Updater.exe with proper capitalisation. 

### Why would this feature be useful?

It would save me having to rename the lime3ds.exe file to Lime3DS.exe every time I have to download a new release. It should be possible to implement this change with only minimal alterations to the codebase.

**Comment by OpenSauce04** [comment]
This is such a non-issue.
