### ISSUE TITLE
exynos 2400

### ISSUE THREAD

**Issue by RafaelVerga** [Lime3DS/Lime-3DS-Emulator#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2111

### Description of Issue

I'm using a galaxy s24, with an exynos 2400 processor, I tried to open countless games, the emulator tries to open, but after 10 seconds it gives up and returns to the main menu

### Expected Behavior

the correct thing would be for the game to at least open

### Reproduction Steps

https://github.com/user-attachments/assets/8c5c5c6c-b2f1-46e9-bb97-4e986ae05cfe

### Log File

[lime3ds_log.old.txt](https://github.com/user-attachments/files/17335459/lime3ds_log.old.txt)
[lime3ds_log.txt](https://github.com/user-attachments/files/17335460/lime3ds_log.txt)

### System Configuration

CPU: exynos 2400
GPU/Driver: angle on vulkan 1.3.231
RAM: 12
OS: android

**Comment by OpenSauce04** [comment]
It seems that these roms are bad dumps. I can assume from the filenames that these files are likely pirated. Please dump your games from a 3DS console you own.
