### ISSUE TITLE
Github backup with Radicle

### ISSUE THREAD

**Issue by Ganipotes** [Lime3DS/Lime-3DS-Emulator#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The Github of the project could be taken down like it was for Citra. 

Even if it was more because of Yuzu than Citra, it would be better to have a backup in [Radicle](https://radicle.xyz/).

There is no built-in mirroring, but you can set up a cron job to pull from Github and push to Radicle periodically.

### Why would this feature be useful?

[Radicle](https://radicle.xyz/) is a peer-to-peer system, which makes it decentralized and resistant to take-down.

**Comment by OpenSauce04** [comment]
We have no concerns of a takedown. Thanks for the suggestion.
