### ISSUE TITLE
Torrents for each release

### ISSUE THREAD

**Issue by dillbyrne** [Lime3DS/Lime-3DS-Emulator#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

For each release on github add the files and publish a torrent so the community can seed them.

### Why would this feature be useful?

It ensures the code can't be nuked from orbit and we have the tech to do it so why not. It doesn't hurt to be prepared and have a backup.

**Comment by fallingSparr0w** [comment]
We have no concerns of a takedown, as described with https://github.com/Lime3DS/Lime3DS/issues/512. Thanks for the suggestion.
