### ISSUE TITLE
Pokemon ultra moon (I just play it) crash before loading.

### ISSUE THREAD

**Issue by urSarah** [Lime3DS/Lime-3DS-Emulator#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3DS 2109

### Description of Issue

When I open the game it freezes on the loading screen.

### Expected Behavior

The game works after loading.

### Reproduction Steps

1. Open the lime
2. Click on the game
3. The loading screen appears
4. Stays on the loading screen forever
5. Force quit the window
6. Crash

### Log File

[lime3ds_log.txt](https://github.com/user-attachments/files/17591287/lime3ds_log.txt)

### System Configuration

CPU: Intel© Core™ i7-3770
GPU/Driver: IvyBridge GT2 [HD Graphics 4000]
RAM: 8GB
OS: Linux Mint 21.3

**Comment by OpenSauce04** [comment]
It seems from the log that the emulator doesn't even have time to write an error before it just gives up. I have my doubts that the hardware you listed is even capable of handling 3DS emulation, so the best thing I can put this up to is an underpowered machine unfortunately.

**Comment by urSarah** [comment]
but it was working even though it was lagging
