### ISSUE TITLE
Crash on MacOS ARM

### ISSUE THREAD

**Issue by JustaRandom** [Lime3DS/Lime-3DS-Emulator#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Latest build 2106

### Description of Issue

Monster hunter 3 ultimate crash after initial launch.

### Expected Behavior

Able to play on original version Citra. Everything works there.

### Reproduction Steps

At launch

### Log File

https://paaster.io/35c1ivRHyBqTmq4uEf6JE#fReL6UxHxgWRuWZWcZwTcGb-NN-CIM1HDaTSrZm7xLc

### System Configuration

CPU: M2 mac
GPU/Driver:
RAM: 32
OS: sonoma 14.4.1

**Comment by darkuser89** [comment]
3D games don't seem to work anymore :-(
Even the system apps like Mii Maker no longer work.

tested on M1 Max and M3 Pro 

Edit: v2106 is the problem in 2105 everything works

**Comment by OpenSauce04** [comment]
Does this happen with all renderers?

**Comment by JustaRandom** [comment]
Tried all the renderers options one by one and it is crashing at the same point.
Just for info, I do not have any other option that vulkan api, no opengl, and the software one is bad.

**Comment by OpenSauce04** [comment]
This is going to be very difficult to debug because none of the maintainers have access to an ARM Mac :/
I can't even see anything between 2105 and 2106 that could be causing a crash specifically on ARM MacOS
Have you tried deleting Citra's home directory?

**Comment by JustaRandom** [comment]
Deleting the citra folder with all configs still crash.
Tried to change renders still crash.

**Comment by rtiangha** [comment]
Have you tried deleting the contents of the shaders directory and retrying? I'm not sure where it is on a Mac, but in Windows, it's something like `Citra\user\shaders\` in the Roaming directory.

**Comment by OpenSauce04** [comment]
> Have you tried deleting the contents of the shaders directory and retrying?

Deleting the Citra home directory was attempted earlier in the thread to no avail. This folder contains Citra's shader cache

**Comment by OpenSauce04** [comment]
@rtiangha Would you mind joining the Lime3DS discord server so that we can discuss this issue?
We've made progress and have figured out the commit where the issue first appeared, which was one of yours, but I'm still totally confused on why this is happening
We have people with the hardware to test this issue when fixes are attempted

**Comment by rtiangha** [comment]
Probably worthwhile to port over [this fix](https://github.com/PabloMK7/citra/pull/67) from PabloMK7's build. I'll send a Pull Request soon once I get to a computer.
