### ISSUE TITLE
Add Haptic Feedback support

### ISSUE THREAD

**Issue by SpikyEchidna** [Lime3DS/Lime-3DS-Emulator#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Always on or toggle-able haptic feedback for on-screen controls

### Why would this feature be useful?

While using on-screen touch controls, haptic feedback would make the experience feel more immersive, as you don't have to worry about misclicking a button. This would be useful for both Android and desktop on-screen controls.

**Comment by ayrudev** [comment]
Ongoing PR #56

**Comment by OpenSauce04** [comment]
Released in 2108
