### ISSUE TITLE
Texture Support?

### ISSUE THREAD

**Issue by 8-Pit** [Lime3DS/Lime-3DS-Emulator#541]
Hello, I am currently working on a Texture Pack for Yo-kai Watch 2, created with Citra's texture dump feature. I've tested it a little on Lime3DS, but when starting it I mostly intended to use it on Citra. Will the textures be usable in this emulator without too much hassle? Will the naming scheme stay the same? If neither, will there be some sort of tool to convert texture packs for use with this emulator?
Not just for my texture pack, but also for the dozens of Texture Packs already created by others (Such as the excellent HD Texture Packs by Henriko Magnifico).

Would be great if I didn't have to throw away months of work.

**Comment by fallingSparr0w** [comment]
Yes 8-Pit, Azahar should have existing features of Citra and Lime3DS unless specified.
