### ISSUE TITLE
Add ability to set more than one custom screen layout and per-game settings in Android version

### ISSUE THREAD

**Issue by palop4l** [Lime3DS/Lime-3DS-Emulator#542]
The layout feature particularly custom layout placement on Lime3DS android is great. Hopefully, Azahar team have plans to improve this feature such as more than one custom layout and per-game custom layout (and settings too).

**Comment by OpenSauce04** [comment]
If you are going to request a specific change, please specify it rather than simply stating "I hope this is improved". We don't know what you are thinking.

**Comment by palop4l** [comment]
Should i edit the title? It's on my original comment. Then again, my bad, i should be very clear in the first place.

Well, to be more specific, the current custom screen layout on Lime3DS only let you make 1 custom layout per orientation. It would be great if devs improve on this by letting us set up few more.

I can use few custom layout per game. For example, in MH4U & MHXX i mostly play using controller. With the 20:9 cheat code, i basically max out the main screen in custom layout to my device resolution and set the second screen parameters to 0. Treating the game as single screen experience and swapping to second screen with L3 on controller when i need it. Works very great for me.

But, i would also like to have second custom layout where i can see both screen with the screen placement i set myself. But i can't do that since currently the feature only let me make one custom layout.

If i need a new layout, i need to change the parameter for new one basically deleting my old layout and will need to reinput the old parameter back if i want to use my old layout. This, i think is a pain and would be great if devs let us set more than one custom layout profile.

Layout for specific game often doesn't feel great on another game. Hence why i think per-game custom layout would be great addition. Not just layout, each game for example need different set of settings for them to run best on our device (renderer, internal resolution, etc). I think per-game configuration where we set setting, layout, etc for each game is even better. Afterall, per-game configuration already exist on Lime3DS PC version so having it on Android too would be awesome.

That's about it i think, sorry if it's too long. Keep doing amazing work, Azahar team!
