### ISSUE TITLE
External display support for Android 

### ISSUE THREAD

**Issue by RageDeadworth** [Lime3DS/Lime-3DS-Emulator#543]
Could you please consider implementing external display support for the new emulator the same way Drastic has for Android.
![i8h0vkuacor51](https://github.com/user-attachments/assets/a0c93adf-6601-4fd3-93f3-42d04a3bfb09)

**Comment by ghost** [comment]
Isn't it a duplicate of https://github.com/azahar-emu/azahar/issues/351

**Comment by imxaander** [comment]
> Isn't it a duplicate of #351

yep

**Comment by RageDeadworth** [comment]
> > Isn't it a duplicate of #351
> 
> yep
Given that lime 3ds is no longer a thing and now it's Azahar, I thought we might have to submit new suggestions for the new emulator development.
