### ISSUE TITLE
In the keybinds settings there is 2 exit options, 'Exit Citra' & 'Exit Lime'

### ISSUE THREAD

**Issue by BlurrySquire** [Lime3DS/Lime-3DS-Emulator#55]
### Issue

We need to remove 'Exit Citra'.

![image](https://github.com/Lime3DS/Lime3DS/assets/114335081/0d9e4e2b-86ca-441c-8497-a5803720ad9f)

**Comment by OpenSauce04** [comment]
This has been fixed
