### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by B-Nerd** [Lime3DS/Lime-3DS-Emulator#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

multiplayer support via pretendo network so that people can still play together after the shutdown of the nintendo servers

### Why would this feature be useful?

multiplayer makes the games that support it better & that also means lime gets better 
here is a link to the pretendo network site https://pretendo.network/

**Comment by OpenSauce04** [comment]
Duplicate of #47
