### ISSUE TITLE
Allow changing the data folder path

### ISSUE THREAD

**Issue by NeverSm1le** [Lime3DS/Lime-3DS-Emulator#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

By default, the data folder is located in AppData\Roaming\Citra. There's an option to change that path of NAND and SDMC yet no way to change this whole data folder

### Why would this feature be useful?

I think this would unify and cut down many similar settings, there're options to set path for SDMC, NAND, Screenshots right now, it's better to unify them as one.

**Comment by Daisouji** [comment]
make a folder named "user" in the same directory as the executable lime3ds.exe
