### ISSUE TITLE
please upload app on F-droid or Izzyondroid

### ISSUE THREAD

**Issue by Gamer750** [Lime3DS/Lime-3DS-Emulator#65]
please upload app on F-droid or Izzyondroid

**Comment by NeverSm1le** [comment]
That depends on the owner of those repo, meanwhile you can use Obtainium

**Comment by OpenSauce04** [comment]
We already have plans to upload to F-Droid

**Comment by ayrudev** [comment]
F-Droid release is planned on our [To-Do](https://github.com/orgs/Lime3DS/projects/1) list

**Comment by davidhedlund** [comment]
Apr 22, 2024 from https://github.com/azahar-emu/azahar/issues/132#issuecomment-2069143611
> We have investigated this already, and have decided that it isn't possible, or at the very least isn't practically viable
