### ISSUE TITLE
Support 

### ISSUE THREAD

**Issue by Abhin939** [Lime3DS/Lime-3DS-Emulator#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Please add support for 32 bit devices.( Armv7)

### Why would this feature be useful?

But adding this 32 bit devices users can at least test the game sin our devices, if good we can continue playing in this emulator. A lot of 32 bit devices users are there waiting for such an emulator

**Comment by OpenSauce04** [comment]
If your device is still running 32 bit ARM, there is no chance that it would be capable of emulating 3DS games even if the emulator did support that architecture
