### ISSUE TITLE
Android Notification Icon and Tab for Lime3DS not working

### ISSUE THREAD

**Issue by Someguy1519** [Lime3DS/Lime-3DS-Emulator#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Android Notification icon and tab that says "Lime3DS is running" for Lime3DS

### Why would this feature be useful?

To prevent the emulator from restarting when it's running in the background. One can just tap on the notification tab to return to the game.

**Comment by ayrudev** [comment]
Im pretty sure this is already a thing, could you explain it further?

**Comment by Someguy1519** [comment]
> Im pretty sure this is already a thing, could you explain it further?

![Screenshot_20240412_095019_Nova Launcher](https://github.com/Lime3DS/Lime3DS/assets/27980228/1622b27c-3711-4c89-a01a-d58c6dbe6588)
![Screenshot_20240412_094946_Nova Launcher](https://github.com/Lime3DS/Lime3DS/assets/27980228/85bde9aa-4923-4350-a737-a4d1f4363ee8)
![Screenshot_20240412_095248_Nova Launcher](https://github.com/Lime3DS/Lime3DS/assets/27980228/83ea3e6b-91b0-4437-8c59-086bcc5533dd)

This is what I'm talking about. The feature seems to be missing from Lime3DS.

**Comment by ayrudev** [comment]
Weird, this was working a few versions before, we'll look into it later

**Comment by stepsy** [comment]
The notification icons are gone because of this PR 
https://github.com/PabloMK7/citra/pull/56
Lime3ds merged from GPUCODE.
Gpucode disabled foreground services.
https://github.com/PabloMK7/citra/commit/0cc094e7c8841e979851db744624ecf2f7758370
I was testing the PR with him on discord dms.
