### ISSUE TITLE
Mario & Luigi Superstar Saga DX Crash at credits

### ISSUE THREAD

**Issue by rzayon** [Lime3DS/Lime-3DS-Emulator#76]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Lime3DS 2108

### Description of Issue

The game crashes after beating the game at a specific point of the credits, shown in the image (which blocks the final quest in bowser's minion for exemple)

![image_2024-04-12_173616786](https://github.com/Lime3DS/Lime3DS/assets/116463984/1286fc9e-fabd-444d-85de-e86f873c21a8)

### Expected Behavior

It should just complete the credits

### Reproduction Steps

Kill the final boss, leave the castle and watch the credits until it crashes

### Log File

[citra_log.txt](https://github.com/Lime3DS/Lime3DS/files/14960897/citra_log.txt)

### System Configuration

CPU: AMD Ryzen 2700U
GPU/Driver: AMD Radeon RX Vega 10
RAM: 8gb
OS: Windows 10 64bits

**Comment by rishooty** [comment]
I have this same issue on the latest build through AUR
