### ISSUE TITLE
Raspberry Pi Support

### ISSUE THREAD

**Issue by Adame1928** [Lime3DS/Lime-3DS-Emulator#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

RPi5 Vulkan & OpenGL 3.1 for batocera/Linux.

Citra was tested but had a dual screen bug _top screen was duplicated

Latest release crashed when trying Vulkan and OGL 4.3 is required. 

### Why would this feature be useful?

A further system working and supported which has a large community.

**Comment by Adame1928** [comment]
.

**Comment by rtiangha** [comment]
Just chiming in: It might be possible to do this with just the free tools using an ubuntu-latest x86_64 container and cross compiling with gcc (as in, set up a separate action that installs `gcc-aarch64-linux-gnu` and other related tools, similar to how the msvc and msys2 builds are separated).

An example:
https://www.bytebase.com/blog/how-to-cross-compile-with-cgo-use-goreleaser-and-github-action/

Would need some playing around, though.

**Comment by OpenSauce04** [comment]
I'm pretty sure we do already support Linux ARM64 via Flatpak. Does the AppImage format support ARM builds?

**Comment by rtiangha** [comment]
Looks like it does, but it's not enabled by default. Awesome if it were, though. The example covers 32-bit x86; I'm sure there's an arm64 tutorial out there somewhere, though.

https://docs.flatpak.org/en/latest/multiarch.html

**Comment by JakobDev** [comment]
Flathub builds each App for aarch64, and x86_64 unless disabled. Therefore Flathub already has a ARM build of Lime3DS.

>The example covers 32-bit x86; I'm sure there's an arm64 tutorial out there somewhere, though.

This has nothing to do with ARM. This tutorial is about using 32bit on a 64bit System. [Here is a tutorial for cross build](https://developer.puri.sm/Librem5/Apps/Packaging_Apps/Building_Flatpaks/Cross-Building.html). As Flatpak already offers an ARM build, there is no need for you to do it yourself.

**Comment by OpenSauce04** [comment]
I'm going to close this under the pretense that the Raspberry Pi is already technically supported under the Flatpak version
