### ISSUE TITLE
Multiple hotkeys don't work, or have issues

### ISSUE THREAD

**Issue by TheRealWario** [Lime3DS/Lime-3DS-Emulator#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime 2108

### Description of Issue

Hotkeys like the frame advance and toggle 3d hotkeys don't function at all, and hotkeys like the mute function and exit fullscreen hotkeys only work when the focus is on the gamelist window, or simply the main window if single window mode is turned. As well, the normal fullscreen hotkey does not work with the bottom screen if i go into the settings window and click ok to save, where it will force itself out of fullscreen and cant go back.

### Expected Behavior

The fullscreen key should make any of the 2 screens go fullscreen, but going into settings and clicking ok will stop the secondary screen from doing so. The frame advance is supposed to freeze the screen and advance to the next frame, but it does neither. The 3d toggle hotkey should set the 3d to 0, but it does nothing. Ideally, the mute and exit fullscreen hotkeys should work when using any of the 2 screens so you do not need to use the game list window or single window mode. I haven't tested every single hotkey, but they likely have the same issues as these, if they also don't work

### Reproduction Steps

To see the fullscreen bug, boot up a game right after entering Lime, make sure separate windows is the screen layout, click the bottom screen window and use the fullscreen key, go back to the game list window and go to Emulation>Configure..., click ok on the settings window and try to enter fullscreen on the bottom screen again. It wont enter fullscreen anymore, but doing it on the top screen will still work. For the other hotkeys, the mute and exit fullscreen keys only work when the main game list window is active, and no other window. For the 3d toggle and frame advance, no matter what window is active, they don't do anything.

### Log File

[citra_log.txt](https://github.com/Lime3DS/Lime3DS/files/14971402/citra_log.txt)

### System Configuration

CPU: AMD Ryzen 5 5600H
GPU/Driver: NVIDIA GeForce GTX 1650/vulkan
RAM: 24gb
OS: Windows 11 Home 23h2

**Comment by OpenSauce04** [comment]
Due to the wide scope of this issue, I am going to split this into several smaller issues with can be handled independently

**Comment by OpenSauce04** [comment]
Superseded by #276, #277 and #278
