### ISSUE TITLE
Zelda - Ocarina of time 3ds - Crash

### ISSUE THREAD

**Issue by isywybad** [Lime3DS/Lime-3DS-Emulator#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2107

### Description of Issue

Crash and exit of Lime in two cases. each time I reproduce the action
- lost wood forest, as kids, when i try to get a golden skeletal following this steps :  "From the entrance of the Lost Woods, go right, left, right, left, and left" - last left create a crash 
-  Kakariko Village,  Skulltula house, speaking to the second guy (20 Skulletat) create a crash also

### Expected Behavior

Crash and quit

### Reproduction Steps

Both of the step recreate the crash

### Log File

NA

### System Configuration

CPU: Macook pro M1 Max
GPU/Driver: 
RAM:32
OS: 14.4.1 SONOMA

**Comment by isywybad** [comment]
Just instal 2108 and retry ... No more bug in skulltula house.  
Didn't try yet in lost wood.

**Comment by OpenSauce04** [comment]
@isywybad I take this message as an indication that the issue may be fixed?
Please continue to investigate the issue. If there is no response within a week, I will close this issue under the assumption that it was fixed

**Comment by isywybad** [comment]
Test it ... all good for both bugs. no more crashing. Thanks.
