### ISSUE TITLE
Game crashing issues with 2 games I have

### ISSUE THREAD

**Issue by TTVURASCAREDCLOWNLOL** [Lime3DS/Lime-3DS-Emulator#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime 2108

### Description of Issue

Lego Star Wars the clone wars 3 doesn't even boot. It tries and then crashes. And I also have mario and sonic which crashes whenever you try to play an event with a mii Excluding the training which works fine Basically this means the story mode in the game is Not playable because you can't even get past the first event But the rest of the game works as intended when using regular characters.

### Expected Behavior

Lego Star Wars should boot up to the main menu But all that happens is it loads up a spot pass popup then crashes As for Mario and sonic it should let you play any event with a mii Just fine

### Reproduction Steps

I have no idea how to fix this And A save file isnt required Just install the games for yourself and play and you'll see the issues.

### Log File

No log file appears.

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by OpenSauce04** [comment]
We are unable to investigate the issue without a log

**Comment by OpenSauce04** [comment]
We are unable to investigate the issue without a log
