### ISSUE TITLE
Andriod external display

### ISSUE THREAD

**Issue by Usua07** [Lime3DS/Lime-3DS-Emulator#89]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What feature are you suggesting?

In drastic ds emulater andriod is an option to have a second display such as a TV be used as the top screen while the phone is the bottom screen was wanting to know if that could be added in the future

### Why would this feature be useful?

Would make for bigger screens

**Comment by OpenSauce04** [comment]
Superseded by #351
