### ISSUE TITLE
Add CTRPF plugin feature 

### ISSUE THREAD

**Issue by atuy1219** [Lime3DS/Lime-3DS-Emulator#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Allows you to change folders and colors like an action replay supported by 3DS ctrpf

### Why would this feature be useful?

Not only is it easier to migrate from 3DS, but it is also convenient when you use it without migrating.

**Comment by OpenSauce04** [comment]
I'm not sure what you're referring to here. Could you give an example?

**Comment by atuy1219** [comment]
![PXL_20240418_141125954](https://github.com/Lime3DS/Lime3DS/assets/130917473/c31fba77-3ea8-497e-a5c0-9c4c049246d5)
![PXL_20240418_141133257](https://github.com/Lime3DS/Lime3DS/assets/130917473/b3508c23-c012-4414-84a5-94b0072b41e1)
![PXL_20240418_141221391](https://github.com/Lime3DS/Lime3DS/assets/130917473/7b1b1b81-2ae4-458a-ae79-f46828c054a1)
Please be able to change folders and colors as shown in the picture
![Screenshot_20240418-232430](https://github.com/Lime3DS/Lime3DS/assets/130917473/9e1eab9b-d541-43cc-b7b5-fd53b6417474)
You can support folders and notes by doing what you see in the image above (but there are concerns that the notes are already implemented in Lime, so there are two notes function).
To change the color of the text
![Screenshot_20240418-235409](https://github.com/Lime3DS/Lime3DS/assets/130917473/e3794d8f-1395-4896-b3a5-a8a4bfd40d58)
write the code like

I'm not using English as my home country, so I use machine translation. 
Therefore, I apologize for the difficulty in conveying the meaning of the sentence.

**Comment by atuy1219** [comment]
![Screenshot_20240418-233947](https://github.com/Lime3DS/Lime3DS/assets/130917473/4269f710-aefa-4a9e-b312-ff5aae65884c)

The code to change the color of the text didn't show up well

**Comment by atuy1219** [comment]
Reference
https://gbatemp.net/threads/database-ctrpf-ar-cheat-codes.493220/
https://github.com/PabloMK7/CTRPluginFramework-BlankTemplate

**Comment by YGOmod** [comment]
this feature is already available
![Screenshot_20240607_124911_Lime3DS](https://github.com/Lime3DS/Lime3DS/assets/130164085/050db5a3-c2c6-41f5-990c-32276edf1610)

**Comment by atuy1219** [comment]
Oh, I forgot that feature exists.
