### ISSUE TITLE
Save State

### ISSUE THREAD

**Issue by Litbolt123** [Lime3DS/Lime-3DS-Emulator#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

To have the save state function work. I know its built into Lime but it hasn't worked for me, it just crashes the game. Could you get this working properly? Lemonade was going to get rid of it but they went down. Please don't get rid of it :)  I think its a very nice feature.

### Why would this feature be useful?

I think its a very nice feature. You can leave your game and pick it back up anytime. Super nice!

**Comment by OpenSauce04** [comment]
If this is a bug report, please open an issue with the appropriate information

**Comment by Litbolt123** [comment]
Okay 👍
