### ISSUE TITLE
Vulkan renderer crashes when game is boot up

### ISSUE THREAD

**Issue by Ivan951236** [Lime3DS/Lime-3DS-Emulator#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3DS 2109

### Description of Issue

Any game crashes when vulkan renderer is set
If that helps API Version:
AIDA64: 1.2.175
TechPowerUp GPU-Z: 1.2.175

### Expected Behavior

Any 3DS game should boot up as other Vulkan games works just fine

### Reproduction Steps

1. Get NVIDIA GeForce GTX 760
2. Plug it in
3. Open Lime3DS
4. Set Vulkan Renderer
5. Double click on a game in game list
6. Crash!

### Log File

[citra_log.txt](https://github.com/Lime3DS/Lime3DS/files/15014592/citra_log.txt)

### System Configuration

CPU:Intel Core i3-2100
GPU/Driver:NVIDIA Geforce GTX 760/474.82
RAM:8GB DDR3
OS:Windows 10

**Comment by OpenSauce04** [comment]
Mentioning what games you tried would be helpful

**Comment by Ivan951236** [comment]
> Mentioning what games you tried would be helpful

Okay but its only Lime3DS emulator and other 3DS emulator built on Citra that this happends
which means any game crashes in the emulator
However, i tried Super Mario 3D Land and 3DS Home Menu

**Comment by rtiangha** [comment]
Just curious, but does it happen after running one of these builds:
https://github.com/rtiangha/bravely-offline-citra/releases

I've got some Vulkan changes that I'm playing around with from other forks that haven't yet made it into one of the major popular forks (mainly all the Canary changes that never made it into Nightly, plus a new SPIRV TrivialVertexShader and relaxed precision decorators). I'm doubtful it'll fix your issues, but then again, maybe it might.

**Comment by Ivan951236** [comment]
> Just curious, but does it happen after running one of these builds: https://github.com/rtiangha/bravely-offline-citra/releases
> 
> I've got some Vulkan changes that I'm playing around with from other forks that haven't yet made it into one of the major popular forks (mainly all the Canary changes that never made it into Nightly, plus a new SPIRV TrivialVertexShader and relaxed precision decorators). I'm doubtful it'll fix your issues, but then again, maybe it might.

Also happends there
Well i don't think you (Lime3DS Devs) might do it but for compatibly maybe Lime3DS will use Vulkan 1.0 instead

**Comment by rtiangha** [comment]
Did the Vulkan renderer ever work properly on regular Citra? And if so, do you remember the build or nightly number? I believe the Vulkan stuff should be backwards compatible, unless there are some instructions that Citra uses that aren't supported by older Vulkan SDKs (in which case, you might be SOL and have to stick with OpenGL unless you can somehow update your graphic drivers).

While the current Lime3DS release is using Vulkan headers from 1.3.280, the last Citra Nightly release used 1.3.275, which isn't that much of a change.

Edit: And it looks like Vulkan support in Citra started at around 1.3.251 back on June 20, 2023, so yeah, I'd be surprised if it ever worked on your video card. Please chime in if it ever worked on your setup; I'm starting to suspect that Vulkan 1.3 is the bare minimum for Citra.

Double Edit: Although the original announcement claimed [Vulkan 1.1](https://web.archive.org/web/20240229164405/https://citra-emu.org/entry/citra-vulkan-announcement/) so maybe an older build might work with your card. If so, let us know which ones worked; maybe we can track down what might have changed in the last 10 months or so (I do know a couple of extra instructions were added between then so maybe that changed things).

Quick Question: Did the last [Citra Nightly](https://archive.org/details/citra-2104-nightly) work? If so, it might be one of the dependencies that was updated near the beginning of Lime3DS.

**Comment by Ivan951236** [comment]
> Did the Vulkan renderer ever work properly on regular Citra? And if so, do you remember the build or nightly number? I believe the Vulkan stuff should be backwards compatible, unless there are some instructions that Citra uses that aren't supported by older Vulkan SDKs (in which case, you might be SOL and have to stick with OpenGL unless you can somehow update your graphic drivers).
> 
> While the current Lime3DS release is using Vulkan headers from 1.3.280, the last Citra Nightly release used 1.3.275, which isn't that much of a change.
> 
> Edit: And it looks like Vulkan support in Citra started at around 1.3.251 back on June 20, 2023, so yeah, I'd be surprised if it ever worked on your video card. Please chime in if it ever worked on your setup; I'm starting to suspect that Vulkan 1.3 is the bare minimum for Citra.
> 
> Double Edit: Although the original announcement claimed [Vulkan 1.1](https://web.archive.org/web/20240229164405/https://citra-emu.org/entry/citra-vulkan-announcement/) so maybe an older build might work with your card. If so, let us know which ones worked; maybe we can track down what might have changed in the last 10 months or so (I do know a couple of extra instructions were added between then so maybe that changed things).
> 
> Quick Question: Did the last [Citra Nightly](https://archive.org/details/citra-2104-nightly) work? If so, it might be one of the dependencies that was updated near the beginning of Lime3DS.

I also tried regular now down citra and the same happend...
short answer: is no

**Comment by rtiangha** [comment]
Another user had luck with and older version of Citra; something newer than Nightly 1995 but older than the last one of 2104; they found that nothing newer than 2030 worked on their Android device. Could you try some older versions and report back if they work instead?  Here are some old versions:

[https://web.archive.org/web/*/https://github.com/citra-emu/citra-nightly/releases/download*](https://web.archive.org/web/*/https://github.com/citra-emu/citra-nightly/releases/download*)

**Comment by rtiangha** [comment]
Wow, so it looks like it broke just under 2 months after Vulkan support was officially announced. That's...not promising since there've been so many Vulkan changes since. Well, at least we have a date range now. Hopefully something obvious jumps out. Don't suppose anyone out there knows how long things typically stayed in Canary before making it to Nightly?

**Comment by rtiangha** [comment]
Good News: I found it. It was commit fa08df21a50f7de06f39333bd441d2f44c9f7ed8
Bad News: Looks like it was intentional. 🙁

`* vk_platform: Hardcode apiVersion to VK_API_VERSION_1_3`

So there you go. Minimal requirement as of Nov 10, 2023 is Vulkan 1.3. Up until then, it was Vulkan 1.1.

I would suggest the documentation be updated and an FAQ be made for the Lime3DS project, if only to reduce the support burden. CC: @OpenSauce04
